/**
 * Takeoff records: the sheets to measure on, and the measurements taken.
 *
 * A measurement row holds geometry, never a quantity — the number follows from
 * the shape and the scale by arithmetic the engine owns, so this module reads
 * the shape and lets the engine say what it comes to. That is why there is no
 * `quantity` field anywhere below.
 */
import { unwrap, type Query } from './query';
import type { Point } from '@grounup/engine';

export interface SheetRow {
  id: string;
  documentName: string;
  documentVersionId: string;
  storagePath: string;
  pageNumber: number;
  sheetNumber: string | null;
  sheetTitle: string | null;
  discipline: string | null;
  statedScale: string | null;
}

export interface CalibrationRow {
  id: string;
  sheetId: string;
  from: Point;
  to: Point;
  knownDistanceFeet: number;
  basis: 'known_dimension' | 'graphic_scale_bar' | 'stated_scale';
  reference: string | null;
  /** Generated by the database, so it cannot be asserted by a caller. */
  measurementMethod: string;
}

export interface MeasurementRow {
  id: string;
  sheetId: string;
  calibrationId: string | null;
  name: string;
  trade: string | null;
  kind: 'count' | 'linear' | 'area' | 'volume';
  unit: string;
  geometry: Point[];
  deductions: Point[][];
  isClosed: boolean;
  pitchRise: number | null;
  pitchRun: number | null;
  depthFeet: number | null;
  widthFeet: number | null;
  countPer: number;
  multiplier: number;
  appliedLineItemId: string | null;
  appliedQuantity: number | null;
  appliedAt: string | null;
  /** Derived by the database from the timestamps, so it cannot be left stale. */
  staleOnLine: boolean;
}

const one = <T,>(v: unknown): T | null =>
  (Array.isArray(v) ? (v as T[])[0] : (v as T | null)) ?? null;

export const loadSheets: Query<SheetRow[]> = async (client) => {
  const rows = unwrap(await client
    .from('document_sheets')
    .select('id, page_number, sheet_number, sheet_title, discipline, drawing_scale, document_version_id, document_versions(storage_path, documents(name))')
    .order('page_number')
    .limit(500)) as Array<Record<string, unknown>>;
  return rows.map((s) => {
    const ver = one<{ storage_path: string; documents: unknown }>(s.document_versions);
    return {
      id: String(s.id),
      documentName: one<{ name: string }>(ver?.documents)?.name ?? 'Untitled document',
      documentVersionId: String(s.document_version_id),
      storagePath: ver?.storage_path ?? '',
      pageNumber: Number(s.page_number),
      sheetNumber: (s.sheet_number as string | null) ?? null,
      sheetTitle: (s.sheet_title as string | null) ?? null,
      discipline: (s.discipline as string | null) ?? null,
      statedScale: (s.drawing_scale as string | null) ?? null,
    };
  });
};

export const loadCalibrations: Query<CalibrationRow[]> = async (client) => {
  const rows = unwrap(await client
    .from('takeoff_calibrations')
    .select('id, document_sheet_id, from_x, from_y, to_x, to_y, known_distance_feet, basis, reference, measurement_method')
    .order('created_at', { ascending: false })) as Array<Record<string, unknown>>;
  return rows.map((c) => ({
    id: String(c.id),
    sheetId: String(c.document_sheet_id),
    from: { x: Number(c.from_x), y: Number(c.from_y) },
    to: { x: Number(c.to_x), y: Number(c.to_y) },
    knownDistanceFeet: Number(c.known_distance_feet),
    basis: c.basis as CalibrationRow['basis'],
    reference: (c.reference as string | null) ?? null,
    measurementMethod: String(c.measurement_method),
  }));
};

export const loadMeasurements: Query<MeasurementRow[]> = async (client) => {
  const rows = unwrap(await client
    .from('takeoff_measurements')
    .select('id, document_sheet_id, calibration_id, name, trade, kind, unit, geometry, deductions, is_closed, pitch_rise, pitch_run, depth_feet, width_feet, count_per, multiplier, applied_line_item_id, applied_quantity, applied_at, updated_at')
    .order('created_at', { ascending: false })
    .limit(500)) as Array<Record<string, unknown>>;
  return rows.map((m) => ({
    id: String(m.id),
    sheetId: String(m.document_sheet_id),
    calibrationId: (m.calibration_id as string | null) ?? null,
    name: String(m.name),
    trade: (m.trade as string | null) ?? null,
    kind: m.kind as MeasurementRow['kind'],
    unit: String(m.unit),
    geometry: (m.geometry as Point[]) ?? [],
    deductions: (m.deductions as Point[][]) ?? [],
    isClosed: Boolean(m.is_closed),
    pitchRise: m.pitch_rise == null ? null : Number(m.pitch_rise),
    pitchRun: m.pitch_run == null ? null : Number(m.pitch_run),
    depthFeet: m.depth_feet == null ? null : Number(m.depth_feet),
    widthFeet: m.width_feet == null ? null : Number(m.width_feet),
    countPer: Number(m.count_per ?? 1),
    multiplier: Number(m.multiplier ?? 1),
    appliedLineItemId: (m.applied_line_item_id as string | null) ?? null,
    appliedQuantity: m.applied_quantity == null ? null : Number(m.applied_quantity),
    appliedAt: (m.applied_at as string | null) ?? null,
    staleOnLine: m.applied_at != null
      && new Date(String(m.updated_at)) > new Date(String(m.applied_at)),
  }));
};

/** Save a calibration. The database generates the measurement method from it. */
export async function saveCalibration(
  client: { from: (t: string) => { insert: (v: unknown) => { select: (c: string) => { single: () => PromiseLike<{ data: unknown; error: { message: string } | null }> } } } },
  input: {
    companyId: string; sheetId: string; from: Point; to: Point;
    knownDistanceFeet: number; basis: CalibrationRow['basis']; reference: string | null;
  },
): Promise<string> {
  const { data, error } = await client.from('takeoff_calibrations').insert({
    company_id: input.companyId,
    document_sheet_id: input.sheetId,
    from_x: input.from.x, from_y: input.from.y,
    to_x: input.to.x, to_y: input.to.y,
    known_distance_feet: input.knownDistanceFeet,
    basis: input.basis,
    reference: input.reference,
  }).select('id').single();
  if (error) throw new Error(error.message);
  return String((data as { id: string }).id);
}
