/**
 * Takeoff records: the sheets to measure on, and the measurements taken.
 *
 * A measurement row holds geometry, never a quantity — the number follows from
 * the shape and the scale by arithmetic the engine owns, so this module reads
 * the shape and lets the engine say what it comes to. That is why there is no
 * `quantity` field anywhere below.
 */
import { unwrap, type Query } from './query';
import type { Point } from '@grounup/engine';

/**
 * A sheet, as the picker and the viewer both see it.
 *
 * Read from `my_plan_sheets` (migration 0171) so the name shown here, the name
 * in search and the name on anything printed are one string built in one place.
 */
export type { PlanSheet } from './sheets';
export { loadPlanSheets } from './sheets';

export interface CalibrationRow {
  id: string;
  sheetId: string;
  from: Point;
  to: Point;
  knownDistanceFeet: number;
  basis: 'known_dimension' | 'graphic_scale_bar' | 'stated_scale';
  reference: string | null;
  /** Generated by the database, so it cannot be asserted by a caller. */
  measurementMethod: string;
}

export interface MeasurementRow {
  id: string;
  sheetId: string;
  calibrationId: string | null;
  name: string;
  trade: string | null;
  /**
   * A basin is its own shape, not a volume with a depth: its sides slope, so
   * the floor is smaller than the top and the arithmetic is prismoidal.
   */
  kind: 'count' | 'linear' | 'area' | 'volume' | 'basin';
  unit: string;
  geometry: Point[];
  deductions: Point[][];
  isClosed: boolean;
  pitchRise: number | null;
  pitchRun: number | null;
  depthFeet: number | null;
  widthFeet: number | null;
  countPer: number;
  multiplier: number;
  /**
   * The cuts of a basin, floor upward. Carried because a basin's quantity is
   * prismoidal and cannot be recovered from the outline alone.
   */
  lifts: Array<{
    depth_feet: number; side_slope_run: number;
    bench_width_feet?: number; label?: string;
  }>;
  freeboardFeet: number | null;
  /** The thing this shape measures, which decides the color it is drawn in. */
  conditionId: string | null;
  appliedLineItemId: string | null;
  appliedQuantity: number | null;
  appliedAt: string | null;
  /** Derived by the database from the timestamps, so it cannot be left stale. */
  staleOnLine: boolean;
}

const one = <T,>(v: unknown): T | null =>
  (Array.isArray(v) ? (v as T[])[0] : (v as T | null)) ?? null;

/*
 * The narrow slices of the Supabase client these writers actually use. Written
 * structurally rather than importing SupabaseClient so a test can pass a stub,
 * and loose enough that the real client satisfies them: supabase-js types
 * `insert` against the table's own row shape, which a stricter signature here
 * would reject.
 */
type InsertCapable = {
  from: (t: string) => {
    insert: (v: Record<string, unknown>) => {
      select: (c: string) => {
        single: () => PromiseLike<{ data: unknown; error: { message: string } | null }>;
      };
    };
  };
};
type RpcCapable = {
  rpc: (fn: string, args: Record<string, unknown>) =>
    PromiseLike<{ data: unknown; error: { message: string } | null }>;
};

export const loadCalibrations: Query<CalibrationRow[]> = async (client) => {
  const rows = unwrap(await client
    .from('takeoff_calibrations')
    .select('id, document_sheet_id, from_x, from_y, to_x, to_y, known_distance_feet, basis, reference, measurement_method')
    .order('created_at', { ascending: false })) as Array<Record<string, unknown>>;
  return rows.map((c) => ({
    id: String(c.id),
    sheetId: String(c.document_sheet_id),
    from: { x: Number(c.from_x), y: Number(c.from_y) },
    to: { x: Number(c.to_x), y: Number(c.to_y) },
    knownDistanceFeet: Number(c.known_distance_feet),
    basis: c.basis as CalibrationRow['basis'],
    reference: (c.reference as string | null) ?? null,
    measurementMethod: String(c.measurement_method),
  }));
};

export const loadMeasurements: Query<MeasurementRow[]> = async (client) => {
  const rows = unwrap(await client
    .from('takeoff_measurements')
    .select('id, document_sheet_id, calibration_id, name, trade, kind, unit, geometry, deductions, is_closed, pitch_rise, pitch_run, depth_feet, width_feet, count_per, multiplier, lifts, freeboard_feet, condition_id, applied_line_item_id, applied_quantity, applied_at, updated_at')
    .order('created_at', { ascending: false })
    .limit(500)) as Array<Record<string, unknown>>;
  return rows.map((m) => ({
    id: String(m.id),
    sheetId: String(m.document_sheet_id),
    calibrationId: (m.calibration_id as string | null) ?? null,
    name: String(m.name),
    trade: (m.trade as string | null) ?? null,
    kind: m.kind as MeasurementRow['kind'],
    unit: String(m.unit),
    geometry: (m.geometry as Point[]) ?? [],
    deductions: (m.deductions as Point[][]) ?? [],
    isClosed: Boolean(m.is_closed),
    pitchRise: m.pitch_rise == null ? null : Number(m.pitch_rise),
    pitchRun: m.pitch_run == null ? null : Number(m.pitch_run),
    depthFeet: m.depth_feet == null ? null : Number(m.depth_feet),
    widthFeet: m.width_feet == null ? null : Number(m.width_feet),
    countPer: Number(m.count_per ?? 1),
    multiplier: Number(m.multiplier ?? 1),
    lifts: (m.lifts as MeasurementRow['lifts']) ?? [],
    freeboardFeet: m.freeboard_feet == null ? null : Number(m.freeboard_feet),
    conditionId: (m.condition_id as string | null) ?? null,
    appliedLineItemId: (m.applied_line_item_id as string | null) ?? null,
    appliedQuantity: m.applied_quantity == null ? null : Number(m.applied_quantity),
    appliedAt: (m.applied_at as string | null) ?? null,
    staleOnLine: m.applied_at != null
      && new Date(String(m.updated_at)) > new Date(String(m.applied_at)),
  }));
};

/** Save a calibration. The database generates the measurement method from it. */
export async function saveCalibration(
  client: InsertCapable,
  input: {
    companyId: string; sheetId: string; from: Point; to: Point;
    knownDistanceFeet: number; basis: CalibrationRow['basis']; reference: string | null;
  },
): Promise<string> {
  const { data, error } = await client.from('takeoff_calibrations').insert({
    company_id: input.companyId,
    document_sheet_id: input.sheetId,
    from_x: input.from.x, from_y: input.from.y,
    to_x: input.to.x, to_y: input.to.y,
    known_distance_feet: input.knownDistanceFeet,
    basis: input.basis,
    reference: input.reference,
  }).select('id').single();
  if (error) throw new Error(error.message);
  return String((data as { id: string }).id);
}

/** One measurement behind a line's quantity. */
export interface LineMeasurement {
  id: string;
  lineItemId: string;
  name: string;
  kind: string;
  unit: string;
  appliedQuantity: number;
  appliedAt: string | null;
  sheetLabel: string;
  documentName: string;
  /** The tracing moved after it was applied, so the line may be behind it. */
  retracedSinceApplied: boolean;
}

/**
 * What a line's quantity is made of.
 *
 * A total nobody can break down is a total nobody can check. Before migration
 * 0177 a line held whichever measurement was applied last, so there was nothing
 * to break down — and this is also the list that shows the same run was traced
 * twice.
 */
export const loadLineMeasurements = (lineItemId: string): Query<LineMeasurement[]> =>
  async (client) => {
    const rows = unwrap(await client
      .from('my_line_measurements')
      .select('id, line_item_id, name, kind, unit, applied_quantity, applied_at, sheet_label, document_name, retraced_since_applied')
      .eq('line_item_id', lineItemId)
      .order('applied_at')) as Array<Record<string, unknown>>;
    return rows.map((r) => ({
      id: String(r.id),
      lineItemId: String(r.line_item_id),
      name: String(r.name),
      kind: String(r.kind),
      unit: String(r.unit),
      appliedQuantity: Number(r.applied_quantity ?? 0),
      appliedAt: (r.applied_at as string | null) ?? null,
      sheetLabel: String(r.sheet_label ?? ''),
      documentName: String(r.document_name ?? ''),
      retracedSinceApplied: Boolean(r.retraced_since_applied),
    }));
  };

/**
 * Take a measurement back off its line, keeping the tracing.
 *
 * The shape stays on the sheet and stays measured; the line falls by that much.
 * Without it, correcting a misapplied measurement meant deleting the tracing.
 */
export async function unapplyTakeoff(
  client: RpcCapable, measurementId: string,
): Promise<void> {
  const { error } = await client.rpc('unapply_takeoff', { p_measurement: measurementId });
  if (error) throw new Error(error.message);
}

/**
 * A URL the viewer can fetch for a sheet's document.
 *
 * Signed rather than public: plan sets are a customer's competitive position
 * before they are drawings, and the storage bucket is private for that reason.
 * The signature is short-lived because a leaked URL should stop working.
 */
export async function sheetUrl(
  client: {
    storage: { from: (b: string) => { createSignedUrl: (p: string, s: number) =>
      PromiseLike<{ data: { signedUrl: string } | null; error: { message: string } | null }> } };
  },
  bucket: string,
  storagePath: string,
): Promise<string> {
  const { data, error } = await client.storage.from(bucket).createSignedUrl(storagePath, 3600);
  if (error) throw new Error(error.message);
  if (!data?.signedUrl) throw new Error('That sheet has no file behind it.');
  return data.signedUrl;
}

/** Estimate lines a measurement can be applied to. */
export interface LineOption {
  id: string;
  /** The version it belongs to, so the screen knows which estimate it is on. */
  estimateVersionId: string;
  description: string;
  estimateNumber: string;
  versionNumber: number;
  unit: string;
  measuredQuantity: number;
}

export const loadOpenEstimateLines: Query<LineOption[]> = async (client) => {
  const rows = unwrap(await client
    .from('estimate_line_items')
    .select('id, estimate_version_id, description, unit, measured_quantity, estimate_versions!inner(version_number, status, estimates!estimate_versions_estimate_id_fkey(number))')
    // Only a draft can take a quantity: an issued version is frozen by RULE-009
    // and offering it would produce a refusal the estimator cannot act on.
    .eq('estimate_versions.status', 'draft')
    .order('sort_order')
    .limit(300)) as Array<Record<string, unknown>>;
  return rows.map((l) => {
    const ver = one<{ version_number: number; estimates: unknown }>(l.estimate_versions);
    return {
      id: String(l.id),
      estimateVersionId: String(l.estimate_version_id),
      description: String(l.description),
      estimateNumber: one<{ number: string }>(ver?.estimates)?.number ?? '—',
      versionNumber: Number(ver?.version_number ?? 0),
      unit: String(l.unit),
      measuredQuantity: Number(l.measured_quantity ?? 0),
    };
  });
};

/**
 * Save a measurement and put its quantity on an estimate line.
 *
 * Two steps that must not half-happen: a measurement with no line is a wasted
 * trace, and a line carrying a takeoff quantity with no measurement behind it
 * looks sourced and is not. The second step is a database function so the line
 * update and the measurement update land together — and so `measurement_method`
 * comes from the calibration rather than from here.
 */
export async function applyMeasurement(
  client: InsertCapable & RpcCapable,
  input: {
    companyId: string; sheetId: string; calibrationId: string | null;
    name: string; trade: string | null;
    kind: MeasurementRow['kind']; unit: string;
    geometry: Point[]; deductions: Point[][]; isClosed: boolean;
    pitchRise: number | null; pitchRun: number | null;
    depthFeet: number | null; widthFeet: number | null;
    countPer: number; multiplier: number;
    /**
     * The cuts a basin is made of, top down. Empty for every other kind — the
     * schema refuses lifts on a measurement nothing would read them for,
     * because inputs that look considered and are not are worse than absent.
     */
    lifts?: ReadonlyArray<{
      depth_feet: number; side_slope_run: number;
      bench_width_feet?: number; label?: string;
    }>;
    freeboardFeet?: number | null;
    lineItemId: string; quantity: number; engineVersion: string;
  },
): Promise<string> {
  const measurementId = await saveMeasurement(client, input);

  const { error: applyError } = await client.rpc('apply_takeoff_to_line', {
    p_measurement: measurementId,
    p_line_item: input.lineItemId,
    p_quantity: input.quantity,
    p_engine_version: input.engineVersion,
  });
  if (applyError) throw new Error(applyError.message);
  return measurementId;
}

/**
 * Keep a shape without deciding yet what it belongs to.
 *
 * `applied_line_item_id` has been nullable since migration 0061, and nothing
 * ever wrote a row that used it: the only way to end a measurement was to apply
 * it to an estimate line, which cleared the canvas. So taking six measurements
 * off one sheet meant six trips through the apply panel, in the order the
 * estimate happened to be in rather than the order the drawing reads — and a
 * shape not applied was gone the moment the tool changed.
 *
 * A takeoff is not done in that order. You measure what is in front of you,
 * then decide where it goes.
 */
export async function saveMeasurement(
  client: { from: (t: string) => { insert: (v: Record<string, unknown>) => {
    select: (c: string) => { single: () =>
      PromiseLike<{ data: unknown; error: { message: string } | null }> } } } },
  input: {
    companyId: string; sheetId: string; calibrationId: string | null;
    name: string; trade: string | null;
    kind: MeasurementRow['kind']; unit: string;
    geometry: Point[]; deductions: Point[][]; isClosed: boolean;
    pitchRise: number | null; pitchRun: number | null;
    depthFeet: number | null; widthFeet: number | null;
    countPer: number; multiplier: number;
    lifts?: ReadonlyArray<{
      depth_feet: number; side_slope_run: number;
      bench_width_feet?: number; label?: string;
    }>;
    freeboardFeet?: number | null;
  },
): Promise<string> {
  const { data, error } = await client.from('takeoff_measurements').insert({
    company_id: input.companyId,
    document_sheet_id: input.sheetId,
    calibration_id: input.calibrationId,
    name: input.name,
    trade: input.trade,
    kind: input.kind,
    unit: input.unit,
    geometry: input.geometry,
    deductions: input.deductions,
    is_closed: input.isClosed,
    pitch_rise: input.pitchRise,
    pitch_run: input.pitchRun,
    depth_feet: input.depthFeet,
    width_feet: input.widthFeet,
    count_per: input.countPer,
    multiplier: input.multiplier,
    lifts: input.lifts ?? [],
    freeboard_feet: input.freeboardFeet ?? null,
  }).select('id').single();
  if (error) throw new Error(error.message);
  return String((data as { id: string }).id);
}

/**
 * The plan sets nobody can take off, and the way back.
 *
 * A document uploaded before migration 0135 has no sheets, because nothing in
 * the platform ever created one — so it does not appear on the takeoff screen
 * and nothing says why. It is not broken and it is not listed: it is simply
 * absent, which is the hardest kind of missing to notice.
 */
export interface UnsheetedPlanSet {
  documentVersionId: string;
  documentName: string;
  fileName: string;
  documentType: string;
  pageCount: number | null;
  createdAt: string;
}

export const loadPlanSetsWithoutSheets: Query<UnsheetedPlanSet[]> = async (client) => {
  const rows = unwrap(await client
    .from('my_plan_sets_without_sheets')
    .select('document_version_id, document_name, file_name, document_type, page_count, created_at')
    .order('created_at')
    .limit(200)) as Array<Record<string, unknown>>;
  return rows.map((r) => ({
    documentVersionId: String(r.document_version_id),
    documentName: String(r.document_name ?? 'Untitled document'),
    fileName: String(r.file_name ?? ''),
    documentType: String(r.document_type ?? 'plan_set'),
    pageCount: r.page_count == null ? null : Number(r.page_count),
    createdAt: String(r.created_at),
  }));
};

/**
 * Say how many pages a plan set has, and get its sheets.
 *
 * Returns how many sheets were made, which is zero when they already existed —
 * so pressing it twice is a no-op rather than a second set of pages.
 */
export async function setDocumentPageCount(
  client: RpcCapable, documentVersionId: string, pages: number,
): Promise<number> {
  const { data, error } = await client.rpc('set_document_page_count', {
    p_version: documentVersionId, p_pages: pages,
  });
  if (error) throw new Error(error.message);
  return Number(data ?? 0);
}

/**
 * Put a measurement that was already taken onto an estimate line.
 *
 * The other half of keeping a shape. `saveMeasurement` writes one with no line
 * item on it, because a takeoff is done in the order the drawing reads rather
 * than the order the estimate is in — and without this, a kept measurement
 * could be looked at and never used, which is a shape saved into a drawer.
 *
 * The measurement already carries its geometry, its calibration and how it was
 * measured; only the quantity and the line are decided here. `measurement_method`
 * is read from the calibration inside the function and never accepted from the
 * caller, because it decides the line's confidence and its approval gate.
 */
export async function applySavedMeasurement(
  client: RpcCapable,
  input: { measurementId: string; lineItemId: string; quantity: number; engineVersion: string },
): Promise<void> {
  const { error } = await client.rpc('apply_takeoff_to_line', {
    p_measurement: input.measurementId,
    p_line_item: input.lineItemId,
    p_quantity: input.quantity,
    p_engine_version: input.engineVersion,
  });
  if (error) throw new Error(error.message);
}

/**
 * Take a measurement off the sheet.
 *
 * A mis-traced shape has to be removable or the sheet fills with attempts and
 * nobody can tell which one the estimate is standing on.
 */
export async function deleteMeasurement(
  client: { from: (t: string) => { delete: () => { eq: (c: string, v: string) =>
    PromiseLike<{ error: { message: string } | null }> } } },
  measurementId: string,
): Promise<void> {
  const { error } = await client.from('takeoff_measurements').delete().eq('id', measurementId);
  if (error) throw new Error(error.message);
}
