-- =============================================================================
-- 0008 — The sequences the catalog was still asking for
--
-- The product master names a work sequence for every service it carries, and
-- seed 0006 supplied nineteen of them. It asked for fifty-four. The missing
-- thirty-five covered 512 services — every landscaping service in the catalog,
-- all the roofing, the masonry, the framing, the siding, the exterior work, the
-- HVAC equipment sets and the concrete flatwork.
--
-- Those services loaded anyway, because a named, CSI-coded service somebody can
-- build up by hand beats one that is not there. But they arrived with no
-- breakdown: an estimator picking "Install irrigation mainline" got an empty
-- line and the order of the work in their own head.
--
-- These are the thirty-five, written the way each trade actually runs. Not
-- generated from the file — the file only had the codes — so they are a claim
-- about how work goes rather than a transformation of somebody else's data, and
-- they are worth reading before they are trusted. Irrigation is layout, trench,
-- mainline, laterals, valves, controller, pressure test, flush, backfill,
-- program. Roofing is stage, tear off, inspect the deck, underlayment,
-- flashing, field, penetrations, edge metal, magnet sweep, warranty.
--
-- **No production rates.** Nineteen rates came with seed 0006 because somebody
-- had stated them. Nobody has stated these, and inventing a rate for "flashing
-- and details" would put a number in front of an estimator that reads as
-- knowledge and is a guess.
--
-- Steps are shared where the work genuinely is the same. "Layout" is one task
-- the whole library points at, not thirty-five copies — so a company that
-- measures its own layout production measures it once.
-- =============================================================================

insert into tasks (code, name, category, default_unit, production_required,
                   crew_required, equipment_required, status, source) values
  ('TSK-TT-VERIFY-OPENING-AND-STRUCTURAL', 'Verify opening and structural support', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SET-CURB-OR-HOUSEKEEPING-PAD', 'Set curb or housekeeping pad', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-RIG-AND-SET-THE-UNIT', 'Rig and set the unit', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CONNECT-DUCTWORK', 'Connect ductwork', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CONNECT-REFRIGERANT-AND-CONDEN', 'Connect refrigerant and condensate', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-ELECTRICAL-CONNECTION-AND-DISC', 'Electrical connection and disconnect', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-INSTALL-AND-POINT-CONTROLS', 'Install and point controls', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-STARTUP-AND-COMMISSION', 'Startup and commission', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-TEST-ADJUST-AND-BALANCE', 'Test, adjust and balance', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-DOCUMENTATION-AND-CLOSEOUT', 'Documentation and closeout', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-LAYOUT-AND-VERIFY-ELEVATIONS', 'Layout and verify elevations', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SUBGRADE-PREP-AND-COMPACT', 'Subgrade prep and compact', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SET-FORMS-AND-EDGES', 'Set forms and edges', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-PLACE-REINFORCEMENT', 'Place reinforcement', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-PLACE-CONCRETE', 'Place concrete', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SCREED-AND-FLOAT', 'Screed and float', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-BROOM-OR-TROWEL-FINISH', 'Broom or trowel finish', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CURE-AND-PROTECT', 'Cure and protect', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SAWCUT-AND-SEAL-JOINTS', 'Sawcut and seal joints', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-STRIP-FORMS-AND-CLEAN', 'Strip forms and clean', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-PROTECT-AND-MASK', 'Protect and mask', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-PATCH-AND-SKIM', 'Patch and skim', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-PRIME-SURFACES', 'Prime surfaces', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-INSTALL-TRIM-AND-CASING', 'Install trim and casing', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-PAINT-FINISH-COATS', 'Paint finish coats', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SET-FIXTURES-AND-HARDWARE', 'Set fixtures and hardware', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-TOUCH-UP', 'Touch up', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-FINAL-CLEAN', 'Final clean', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-PUNCH-WALK', 'Punch walk', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-STAGE-AND-PROTECT', 'Stage and protect', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-TEAR-OFF-EXISTING', 'Tear off existing', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-INSPECT-AND-REPAIR-DECK', 'Inspect and repair deck', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-INSTALL-UNDERLAYMENT', 'Install underlayment', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-FLASHING-AND-DETAILS', 'Flashing and details', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-INSTALL-FIELD-ROOFING', 'Install field roofing', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SEAL-PENETRATIONS', 'Seal penetrations', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-EDGE-METAL-AND-TRIM', 'Edge metal and trim', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CLEANUP-AND-MAGNET-SWEEP', 'Cleanup and magnet sweep', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-WARRANTY-AND-CLOSEOUT', 'Warranty and closeout', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SITE-AND-PAD-PREPARATION', 'Site and pad preparation', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SET-THE-GENERATOR', 'Set the generator', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-FUEL-SYSTEM-AND-CONTAINMENT', 'Fuel system and containment', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CONDUIT-AND-FEEDERS', 'Conduit and feeders', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-TRANSFER-SWITCH', 'Transfer switch', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-GROUNDING-AND-BONDING', 'Grounding and bonding', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-TERMINATIONS', 'Terminations', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-STARTUP-AND-LOAD-BANK-TEST', 'Startup and load bank test', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-COMMISSIONING-DOCUMENTS', 'Commissioning documents', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-OWNER-TRAINING-AND-CLOSEOUT', 'Owner training and closeout', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-LAYOUT-AND-LOCATE-UTILITIES', 'Layout and locate utilities', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-TRENCH', 'Trench', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-INSTALL-MAINLINE', 'Install mainline', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-INSTALL-LATERALS-AND-HEADS', 'Install laterals and heads', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-VALVES-AND-MANIFOLDS', 'Valves and manifolds', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CONTROLLER-AND-WIRING', 'Controller and wiring', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-PRESSURE-TEST', 'Pressure test', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-FLUSH-AND-ADJUST-HEADS', 'Flush and adjust heads', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-BACKFILL-AND-RESTORE', 'Backfill and restore', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-PROGRAM-AND-HAND-OVER', 'Program and hand over', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-LAYOUT-ON-DECK', 'Layout on deck', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SET-PLATES', 'Set plates', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-FRAME-WALLS', 'Frame walls', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SHEATHE-WALLS', 'Sheathe walls', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-FRAME-OPENINGS', 'Frame openings', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-FLOOR-AND-ROOF-STRUCTURE', 'Floor and roof structure', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-BRACING', 'Bracing', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-STRAPS-AND-HARDWARE', 'Straps and hardware', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-VERIFY-PLUMB-AND-LINE', 'Verify plumb and line', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CLEANUP', 'Cleanup', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-LAYOUT', 'Layout', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-EXCAVATE', 'Excavate', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-BASE-AND-COMPACT', 'Base and compact', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SET-UNITS', 'Set units', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-BACKFILL-AND-COMPACT', 'Backfill and compact', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CAP-AND-FINISH', 'Cap and finish', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CLEAN-AND-INSPECT', 'Clean and inspect', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-LAYOUT-AND-DRY-BOND', 'Layout and dry bond', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-MORTAR-AND-STAGING-SETUP', 'Mortar and staging setup', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-LAY-LEADS', 'Lay leads', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-LAY-FIELD', 'Lay field', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-REINFORCE-AND-GROUT', 'Reinforce and grout', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-TOOL-JOINTS', 'Tool joints', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CUT-AND-FIT', 'Cut and fit', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CLEAN-MASONRY', 'Clean masonry', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-PROTECT-AND-CURE', 'Protect and cure', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-INSPECT-AND-ASSESS', 'Inspect and assess', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-PRUNE', 'Prune', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-WEED-AND-CULTIVATE', 'Weed and cultivate', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-MULCH', 'Mulch', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-FERTILIZE', 'Fertilize', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-TREAT-AS-NEEDED', 'Treat as needed', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-IRRIGATION-CHECK', 'Irrigation check', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-DEBRIS-REMOVAL', 'Debris removal', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-WALKTHROUGH', 'Walkthrough', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-LAYOUT-PLANT-LOCATIONS', 'Layout plant locations', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-DIG-PITS', 'Dig pits', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-AMEND-SOIL', 'Amend soil', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SET-PLANTS', 'Set plants', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-BACKFILL', 'Backfill', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-STAKE-AS-NEEDED', 'Stake as needed', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-MULCH-RINGS', 'Mulch rings', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-WATER-IN', 'Water in', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-WARRANTY-WALK', 'Warranty walk', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-MOW', 'Mow', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-EDGE', 'Edge', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-TRIM-AND-DETAIL', 'Trim and detail', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-BLOW-AND-CLEAR', 'Blow and clear', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-WEED-BEDS', 'Weed beds', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CHECK-IRRIGATION', 'Check irrigation', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SITE-REPORT', 'Site report', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-LAYOUT-AND-STAKE', 'Layout and stake', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-STRIP', 'Strip', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-ROUGH-GRADE', 'Rough grade', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-IMPORT-AND-SPREAD-TOPSOIL', 'Import and spread topsoil', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-FINE-GRADE', 'Fine grade', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-VERIFY-DRAINAGE', 'Verify drainage', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-COMPACT-AND-ROLL', 'Compact and roll', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CLEAN', 'Clean', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-LAYOUT-AND-LOCATE', 'Layout and locate', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-BED-THE-TRENCH', 'Bed the trench', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SET-PIPE-AND-STRUCTURES', 'Set pipe and structures', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CONNECT-OUTLETS', 'Connect outlets', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-TEST-FLOW', 'Test flow', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-RESTORE-SURFACE', 'Restore surface', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SET-EDGING', 'Set edging', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-PLACE-SURFACE', 'Place surface', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-COMPACT-AND-LEVEL', 'Compact and level', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-JOINT-AND-SEAL', 'Joint and seal', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-TEAR-OFF-AS-NEEDED', 'Tear off as needed', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-REPAIR-SHEATHING', 'Repair sheathing', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-WATER-RESISTIVE-BARRIER', 'Water resistive barrier', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-FLASHING', 'Flashing', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-TRIM', 'Trim', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SIDING-FIELD', 'Siding field', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CAULK-AND-SEAL', 'Caulk and seal', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-DEMO-AND-CLEAR', 'Demo and clear', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SUBGRADE-PREPARATION', 'Subgrade preparation', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-INSTALL', 'Install', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-INSPECT-AND-LAY-OUT', 'Inspect and lay out', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-INSTALL-SILT-FENCE-AND-WATTLES', 'Install silt fence and wattles', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-INLET-PROTECTION', 'Inlet protection', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-STABILIZE-SLOPES', 'Stabilize slopes', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SEED-AND-BLANKET', 'Seed and blanket', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-MONITOR-AND-MAINTAIN', 'Monitor and maintain', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-REMOVE-AT-CLOSEOUT', 'Remove at closeout', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SOIL-PREPARATION', 'Soil preparation', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-AMEND-AND-TILL', 'Amend and till', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SEED-OR-LAY-SOD', 'Seed or lay sod', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-ROLL', 'Roll', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SET-WATERING-SCHEDULE', 'Set watering schedule', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-FIRST-MOW', 'First mow', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-REPAIR-THIN-AREAS', 'Repair thin areas', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-BEDDING-COURSE', 'Bedding course', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SET-PAVERS-OR-STONE', 'Set pavers or stone', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CUT-EDGES', 'Cut edges', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-JOINT-SAND', 'Joint sand', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-COMPACT-AND-CLEAN', 'Compact and clean', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SEAL', 'Seal', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CLEAR', 'Clear', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-REMOVE-DEBRIS', 'Remove debris', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SOIL-TEST', 'Soil test', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-AMEND', 'Amend', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-BASE-COURSE', 'Base course', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-PROOF-ROLL', 'Proof roll', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-PLACE-SURFACE-COURSE', 'Place surface course', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-COMPACT', 'Compact', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-JOINTS-AND-SEAMS', 'Joints and seams', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-STRIPING', 'Striping', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-STAKE-AND-SECURE', 'Stake and secure', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SURVEY-AND-DEVICE-LAYOUT', 'Survey and device layout', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-ROUGH-PATHWAYS-AND-BOXES', 'Rough pathways and boxes', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-PULL-CABLE', 'Pull cable', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-MOUNT-DEVICES', 'Mount devices', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-TERMINATE', 'Terminate', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-HEAD-END-AND-PROGRAMMING', 'Head end and programming', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-TEST-AND-VERIFY', 'Test and verify', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-OWNER-TRAINING', 'Owner training', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-PREPARE-BEDS', 'Prepare beds', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-MULCH-AND-FINISH', 'Mulch and finish', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SET-POSTS', 'Set posts', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CONCRETE-FOOTINGS', 'Concrete footings', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CURE', 'Cure', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-HANG-RAILS-AND-PANELS', 'Hang rails and panels', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-GATES-AND-HARDWARE', 'Gates and hardware', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-ADJUST-AND-ALIGN', 'Adjust and align', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-FLIGHT-PLAN-AND-PERMISSIONS', 'Flight plan and permissions', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SITE-BRIEF-AND-SAFETY', 'Site brief and safety', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CAPTURE', 'Capture', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-REVIEW-ON-SITE', 'Review on site', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-PROCESS-AND-EDIT', 'Process and edit', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-DELIVER', 'Deliver', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SURVEY-AND-PATHWAY-LAYOUT', 'Survey and pathway layout', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-INSTALL-PATHWAYS', 'Install pathways', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-LABEL', 'Label', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CERTIFY-AND-TEST', 'Certify and test', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-AS-BUILT-DOCUMENTATION', 'As-built documentation', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CLOSEOUT', 'Closeout', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-PAVING', 'Paving', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SIGNAGE-AND-WHEEL-STOPS', 'Signage and wheel stops', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-LEVELING-PAD', 'Leveling pad', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-DRAINAGE-STONE-AND-PIPE', 'Drainage stone and pipe', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-GEOGRID-AS-REQUIRED', 'Geogrid as required', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-CAP-UNITS', 'Cap units', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SET-FORMS', 'Set forms', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-REINFORCE', 'Reinforce', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-FINISH', 'Finish', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-STRIP-FORMS', 'Strip forms', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-FOOTINGS', 'Footings', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-ANCHOR', 'Anchor', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-ADJUST-AND-LEVEL', 'Adjust and level', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-PROTECT-AND-ISOLATE', 'Protect and isolate', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SELECTIVE-DEMOLITION', 'Selective demolition', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SHORE-AS-NEEDED', 'Shore as needed', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-FRAME-NEW-WORK', 'Frame new work', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SHEATHE', 'Sheathe', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-INSTALL-PIPE-AND-HEADS', 'Install pipe and heads', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-VALVES-AND-CONTROLLER', 'Valves and controller', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-DISCONNECT-UTILITIES', 'Disconnect utilities', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-SORT-AND-HAUL-DEBRIS', 'Sort and haul debris', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v2'),
  ('TSK-TT-VERIFY-SCOPE-REMOVED', 'Verify scope removed', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v2')
on conflict do nothing;

insert into assemblies (code, name, assembly_type, quantity_unit, status, source) values
  ('ASM-TT-HVAC-EQP', 'HVAC Equipment Template', 'HVAC', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-CONC-FLT', 'Concrete Flatwork Template', 'Concrete', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-RMOD-FINI', 'Remodel Finishes Template', 'Residential Remodel', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-ROOF-STD', 'Roofing Template', 'Roofing', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-GEN-STD', 'Power Generation Template', 'Power Generation', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-LAND-IRRG', 'Irrigation Template', 'Landscaping', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-FRME-STD', 'Framing Template', 'Carpentry', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-LAND-FEAT', 'Landscape Feature Template', 'Landscaping', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-MASN-STD', 'Masonry Template', 'Masonry', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-LAND-CARE', 'Landscape Care Template', 'Landscaping', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-LAND-PLNT', 'Planting Template', 'Landscaping', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-LAND-MAINT', 'Landscape Maintenance Template', 'Landscaping', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-LAND-GRAD', 'Landscape Grading Template', 'Landscaping', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-LAND-DRNG', 'Landscape Drainage Template', 'Landscaping', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-LAND-SURF', 'Landscape Surfacing Template', 'Landscaping', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-SIDE-STD', 'Siding Template', 'Roofing', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-EXTR-GEN', 'Exterior Improvement Template', 'Exterior Improvements', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-LAND-EROS', 'Erosion Control Template', 'Landscaping', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-LAND-TURF', 'Turf Template', 'Landscaping', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-LAND-HARD', 'Hardscape Template', 'Landscaping', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-LAND-PREP', 'Landscape Preparation Template', 'Landscaping', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-EXTR-PAVE', 'Exterior Paving Template', 'Exterior Improvements', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-LAND-EDGE', 'Edging Template', 'Landscaping', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-SECU-STD', 'Security Systems Template', 'Electrical', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-EXTR-LAND', 'Exterior Landscape Template', 'Exterior Improvements', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-EXTR-FENCE', 'Fencing Template', 'Landscaping', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-DRN-MEDIA', 'Drone Media Template', 'Drone', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-COMM-STD', 'Communications Template', 'Electrical', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-EXTR-PARK', 'Parking Template', 'Exterior Improvements', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-EXTR-WALL', 'Retaining Wall Template', 'Exterior Improvements', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-EXTR-CONC', 'Exterior Concrete Template', 'Exterior Improvements', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-EXTR-FURN', 'Site Furnishings Template', 'Exterior Improvements', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-RMOD-FRME', 'Remodel Framing Template', 'Residential Remodel', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-EXTR-IRR', 'Exterior Irrigation Template', 'Exterior Improvements', 'LS', 'active', 'GrounUp task templates v2'),
  ('ASM-TT-RMOD-DEMO', 'Remodel Demolition Template', 'Residential Remodel', 'LS', 'active', 'GrounUp task templates v2')
on conflict do nothing;

insert into assembly_components (company_id, assembly_id, component_kind, task_id,
                                 quantity_per_unit, sort_order)
select null, a.id, 'task', t.id, 1, v.sort
from (values
  ('ASM-TT-HVAC-EQP', 'TSK-TT-VERIFY-OPENING-AND-STRUCTURAL', 10),
  ('ASM-TT-HVAC-EQP', 'TSK-TT-SET-CURB-OR-HOUSEKEEPING-PAD', 20),
  ('ASM-TT-HVAC-EQP', 'TSK-TT-RIG-AND-SET-THE-UNIT', 30),
  ('ASM-TT-HVAC-EQP', 'TSK-TT-CONNECT-DUCTWORK', 40),
  ('ASM-TT-HVAC-EQP', 'TSK-TT-CONNECT-REFRIGERANT-AND-CONDEN', 50),
  ('ASM-TT-HVAC-EQP', 'TSK-TT-ELECTRICAL-CONNECTION-AND-DISC', 60),
  ('ASM-TT-HVAC-EQP', 'TSK-TT-INSTALL-AND-POINT-CONTROLS', 70),
  ('ASM-TT-HVAC-EQP', 'TSK-TT-STARTUP-AND-COMMISSION', 80),
  ('ASM-TT-HVAC-EQP', 'TSK-TT-TEST-ADJUST-AND-BALANCE', 90),
  ('ASM-TT-HVAC-EQP', 'TSK-TT-DOCUMENTATION-AND-CLOSEOUT', 100),
  ('ASM-TT-CONC-FLT', 'TSK-TT-LAYOUT-AND-VERIFY-ELEVATIONS', 10),
  ('ASM-TT-CONC-FLT', 'TSK-TT-SUBGRADE-PREP-AND-COMPACT', 20),
  ('ASM-TT-CONC-FLT', 'TSK-TT-SET-FORMS-AND-EDGES', 30),
  ('ASM-TT-CONC-FLT', 'TSK-TT-PLACE-REINFORCEMENT', 40),
  ('ASM-TT-CONC-FLT', 'TSK-TT-PLACE-CONCRETE', 50),
  ('ASM-TT-CONC-FLT', 'TSK-TT-SCREED-AND-FLOAT', 60),
  ('ASM-TT-CONC-FLT', 'TSK-TT-BROOM-OR-TROWEL-FINISH', 70),
  ('ASM-TT-CONC-FLT', 'TSK-TT-CURE-AND-PROTECT', 80),
  ('ASM-TT-CONC-FLT', 'TSK-TT-SAWCUT-AND-SEAL-JOINTS', 90),
  ('ASM-TT-CONC-FLT', 'TSK-TT-STRIP-FORMS-AND-CLEAN', 100),
  ('ASM-TT-RMOD-FINI', 'TSK-TT-PROTECT-AND-MASK', 10),
  ('ASM-TT-RMOD-FINI', 'TSK-TT-PATCH-AND-SKIM', 20),
  ('ASM-TT-RMOD-FINI', 'TSK-TT-PRIME-SURFACES', 30),
  ('ASM-TT-RMOD-FINI', 'TSK-TT-INSTALL-TRIM-AND-CASING', 40),
  ('ASM-TT-RMOD-FINI', 'TSK-TT-PAINT-FINISH-COATS', 50),
  ('ASM-TT-RMOD-FINI', 'TSK-TT-SET-FIXTURES-AND-HARDWARE', 60),
  ('ASM-TT-RMOD-FINI', 'TSK-TT-TOUCH-UP', 70),
  ('ASM-TT-RMOD-FINI', 'TSK-TT-FINAL-CLEAN', 80),
  ('ASM-TT-RMOD-FINI', 'TSK-TT-PUNCH-WALK', 90),
  ('ASM-TT-ROOF-STD', 'TSK-TT-STAGE-AND-PROTECT', 10),
  ('ASM-TT-ROOF-STD', 'TSK-TT-TEAR-OFF-EXISTING', 20),
  ('ASM-TT-ROOF-STD', 'TSK-TT-INSPECT-AND-REPAIR-DECK', 30),
  ('ASM-TT-ROOF-STD', 'TSK-TT-INSTALL-UNDERLAYMENT', 40),
  ('ASM-TT-ROOF-STD', 'TSK-TT-FLASHING-AND-DETAILS', 50),
  ('ASM-TT-ROOF-STD', 'TSK-TT-INSTALL-FIELD-ROOFING', 60),
  ('ASM-TT-ROOF-STD', 'TSK-TT-SEAL-PENETRATIONS', 70),
  ('ASM-TT-ROOF-STD', 'TSK-TT-EDGE-METAL-AND-TRIM', 80),
  ('ASM-TT-ROOF-STD', 'TSK-TT-CLEANUP-AND-MAGNET-SWEEP', 90),
  ('ASM-TT-ROOF-STD', 'TSK-TT-WARRANTY-AND-CLOSEOUT', 100),
  ('ASM-TT-GEN-STD', 'TSK-TT-SITE-AND-PAD-PREPARATION', 10),
  ('ASM-TT-GEN-STD', 'TSK-TT-SET-THE-GENERATOR', 20),
  ('ASM-TT-GEN-STD', 'TSK-TT-FUEL-SYSTEM-AND-CONTAINMENT', 30),
  ('ASM-TT-GEN-STD', 'TSK-TT-CONDUIT-AND-FEEDERS', 40),
  ('ASM-TT-GEN-STD', 'TSK-TT-TRANSFER-SWITCH', 50),
  ('ASM-TT-GEN-STD', 'TSK-TT-GROUNDING-AND-BONDING', 60),
  ('ASM-TT-GEN-STD', 'TSK-TT-TERMINATIONS', 70),
  ('ASM-TT-GEN-STD', 'TSK-TT-STARTUP-AND-LOAD-BANK-TEST', 80),
  ('ASM-TT-GEN-STD', 'TSK-TT-COMMISSIONING-DOCUMENTS', 90),
  ('ASM-TT-GEN-STD', 'TSK-TT-OWNER-TRAINING-AND-CLOSEOUT', 100),
  ('ASM-TT-LAND-IRRG', 'TSK-TT-LAYOUT-AND-LOCATE-UTILITIES', 10),
  ('ASM-TT-LAND-IRRG', 'TSK-TT-TRENCH', 20),
  ('ASM-TT-LAND-IRRG', 'TSK-TT-INSTALL-MAINLINE', 30),
  ('ASM-TT-LAND-IRRG', 'TSK-TT-INSTALL-LATERALS-AND-HEADS', 40),
  ('ASM-TT-LAND-IRRG', 'TSK-TT-VALVES-AND-MANIFOLDS', 50),
  ('ASM-TT-LAND-IRRG', 'TSK-TT-CONTROLLER-AND-WIRING', 60),
  ('ASM-TT-LAND-IRRG', 'TSK-TT-PRESSURE-TEST', 70),
  ('ASM-TT-LAND-IRRG', 'TSK-TT-FLUSH-AND-ADJUST-HEADS', 80),
  ('ASM-TT-LAND-IRRG', 'TSK-TT-BACKFILL-AND-RESTORE', 90),
  ('ASM-TT-LAND-IRRG', 'TSK-TT-PROGRAM-AND-HAND-OVER', 100),
  ('ASM-TT-FRME-STD', 'TSK-TT-LAYOUT-ON-DECK', 10),
  ('ASM-TT-FRME-STD', 'TSK-TT-SET-PLATES', 20),
  ('ASM-TT-FRME-STD', 'TSK-TT-FRAME-WALLS', 30),
  ('ASM-TT-FRME-STD', 'TSK-TT-SHEATHE-WALLS', 40),
  ('ASM-TT-FRME-STD', 'TSK-TT-FRAME-OPENINGS', 50),
  ('ASM-TT-FRME-STD', 'TSK-TT-FLOOR-AND-ROOF-STRUCTURE', 60),
  ('ASM-TT-FRME-STD', 'TSK-TT-BRACING', 70),
  ('ASM-TT-FRME-STD', 'TSK-TT-STRAPS-AND-HARDWARE', 80),
  ('ASM-TT-FRME-STD', 'TSK-TT-VERIFY-PLUMB-AND-LINE', 90),
  ('ASM-TT-FRME-STD', 'TSK-TT-CLEANUP', 100),
  ('ASM-TT-LAND-FEAT', 'TSK-TT-LAYOUT', 10),
  ('ASM-TT-LAND-FEAT', 'TSK-TT-EXCAVATE', 20),
  ('ASM-TT-LAND-FEAT', 'TSK-TT-BASE-AND-COMPACT', 30),
  ('ASM-TT-LAND-FEAT', 'TSK-TT-SET-UNITS', 40),
  ('ASM-TT-LAND-FEAT', 'TSK-TT-BACKFILL-AND-COMPACT', 50),
  ('ASM-TT-LAND-FEAT', 'TSK-TT-CAP-AND-FINISH', 60),
  ('ASM-TT-LAND-FEAT', 'TSK-TT-CLEAN-AND-INSPECT', 70),
  ('ASM-TT-MASN-STD', 'TSK-TT-LAYOUT-AND-DRY-BOND', 10),
  ('ASM-TT-MASN-STD', 'TSK-TT-MORTAR-AND-STAGING-SETUP', 20),
  ('ASM-TT-MASN-STD', 'TSK-TT-LAY-LEADS', 30),
  ('ASM-TT-MASN-STD', 'TSK-TT-LAY-FIELD', 40),
  ('ASM-TT-MASN-STD', 'TSK-TT-REINFORCE-AND-GROUT', 50),
  ('ASM-TT-MASN-STD', 'TSK-TT-TOOL-JOINTS', 60),
  ('ASM-TT-MASN-STD', 'TSK-TT-CUT-AND-FIT', 70),
  ('ASM-TT-MASN-STD', 'TSK-TT-CLEAN-MASONRY', 80),
  ('ASM-TT-MASN-STD', 'TSK-TT-PROTECT-AND-CURE', 90),
  ('ASM-TT-LAND-CARE', 'TSK-TT-INSPECT-AND-ASSESS', 10),
  ('ASM-TT-LAND-CARE', 'TSK-TT-PRUNE', 20),
  ('ASM-TT-LAND-CARE', 'TSK-TT-WEED-AND-CULTIVATE', 30),
  ('ASM-TT-LAND-CARE', 'TSK-TT-MULCH', 40),
  ('ASM-TT-LAND-CARE', 'TSK-TT-FERTILIZE', 50),
  ('ASM-TT-LAND-CARE', 'TSK-TT-TREAT-AS-NEEDED', 60),
  ('ASM-TT-LAND-CARE', 'TSK-TT-IRRIGATION-CHECK', 70),
  ('ASM-TT-LAND-CARE', 'TSK-TT-DEBRIS-REMOVAL', 80),
  ('ASM-TT-LAND-CARE', 'TSK-TT-WALKTHROUGH', 90),
  ('ASM-TT-LAND-PLNT', 'TSK-TT-LAYOUT-PLANT-LOCATIONS', 10),
  ('ASM-TT-LAND-PLNT', 'TSK-TT-DIG-PITS', 20),
  ('ASM-TT-LAND-PLNT', 'TSK-TT-AMEND-SOIL', 30),
  ('ASM-TT-LAND-PLNT', 'TSK-TT-SET-PLANTS', 40),
  ('ASM-TT-LAND-PLNT', 'TSK-TT-BACKFILL', 50),
  ('ASM-TT-LAND-PLNT', 'TSK-TT-STAKE-AS-NEEDED', 60),
  ('ASM-TT-LAND-PLNT', 'TSK-TT-MULCH-RINGS', 70),
  ('ASM-TT-LAND-PLNT', 'TSK-TT-WATER-IN', 80),
  ('ASM-TT-LAND-PLNT', 'TSK-TT-WARRANTY-WALK', 90),
  ('ASM-TT-LAND-MAINT', 'TSK-TT-MOW', 10),
  ('ASM-TT-LAND-MAINT', 'TSK-TT-EDGE', 20),
  ('ASM-TT-LAND-MAINT', 'TSK-TT-TRIM-AND-DETAIL', 30),
  ('ASM-TT-LAND-MAINT', 'TSK-TT-BLOW-AND-CLEAR', 40),
  ('ASM-TT-LAND-MAINT', 'TSK-TT-WEED-BEDS', 50),
  ('ASM-TT-LAND-MAINT', 'TSK-TT-CHECK-IRRIGATION', 60),
  ('ASM-TT-LAND-MAINT', 'TSK-TT-SITE-REPORT', 70),
  ('ASM-TT-LAND-GRAD', 'TSK-TT-LAYOUT-AND-STAKE', 10),
  ('ASM-TT-LAND-GRAD', 'TSK-TT-STRIP', 20),
  ('ASM-TT-LAND-GRAD', 'TSK-TT-ROUGH-GRADE', 30),
  ('ASM-TT-LAND-GRAD', 'TSK-TT-IMPORT-AND-SPREAD-TOPSOIL', 40),
  ('ASM-TT-LAND-GRAD', 'TSK-TT-FINE-GRADE', 50),
  ('ASM-TT-LAND-GRAD', 'TSK-TT-VERIFY-DRAINAGE', 60),
  ('ASM-TT-LAND-GRAD', 'TSK-TT-COMPACT-AND-ROLL', 70),
  ('ASM-TT-LAND-GRAD', 'TSK-TT-CLEAN', 80),
  ('ASM-TT-LAND-DRNG', 'TSK-TT-LAYOUT-AND-LOCATE', 10),
  ('ASM-TT-LAND-DRNG', 'TSK-TT-TRENCH', 20),
  ('ASM-TT-LAND-DRNG', 'TSK-TT-BED-THE-TRENCH', 30),
  ('ASM-TT-LAND-DRNG', 'TSK-TT-SET-PIPE-AND-STRUCTURES', 40),
  ('ASM-TT-LAND-DRNG', 'TSK-TT-CONNECT-OUTLETS', 50),
  ('ASM-TT-LAND-DRNG', 'TSK-TT-BACKFILL-AND-COMPACT', 60),
  ('ASM-TT-LAND-DRNG', 'TSK-TT-TEST-FLOW', 70),
  ('ASM-TT-LAND-DRNG', 'TSK-TT-RESTORE-SURFACE', 80),
  ('ASM-TT-LAND-SURF', 'TSK-TT-LAYOUT', 10),
  ('ASM-TT-LAND-SURF', 'TSK-TT-EXCAVATE', 20),
  ('ASM-TT-LAND-SURF', 'TSK-TT-BASE-AND-COMPACT', 30),
  ('ASM-TT-LAND-SURF', 'TSK-TT-SET-EDGING', 40),
  ('ASM-TT-LAND-SURF', 'TSK-TT-PLACE-SURFACE', 50),
  ('ASM-TT-LAND-SURF', 'TSK-TT-COMPACT-AND-LEVEL', 60),
  ('ASM-TT-LAND-SURF', 'TSK-TT-JOINT-AND-SEAL', 70),
  ('ASM-TT-LAND-SURF', 'TSK-TT-CLEAN', 80),
  ('ASM-TT-SIDE-STD', 'TSK-TT-STAGE-AND-PROTECT', 10),
  ('ASM-TT-SIDE-STD', 'TSK-TT-TEAR-OFF-AS-NEEDED', 20),
  ('ASM-TT-SIDE-STD', 'TSK-TT-REPAIR-SHEATHING', 30),
  ('ASM-TT-SIDE-STD', 'TSK-TT-WATER-RESISTIVE-BARRIER', 40),
  ('ASM-TT-SIDE-STD', 'TSK-TT-FLASHING', 50),
  ('ASM-TT-SIDE-STD', 'TSK-TT-TRIM', 60),
  ('ASM-TT-SIDE-STD', 'TSK-TT-SIDING-FIELD', 70),
  ('ASM-TT-SIDE-STD', 'TSK-TT-CAULK-AND-SEAL', 80),
  ('ASM-TT-SIDE-STD', 'TSK-TT-CLEAN', 90),
  ('ASM-TT-SIDE-STD', 'TSK-TT-PUNCH-WALK', 100),
  ('ASM-TT-EXTR-GEN', 'TSK-TT-LAYOUT', 10),
  ('ASM-TT-EXTR-GEN', 'TSK-TT-DEMO-AND-CLEAR', 20),
  ('ASM-TT-EXTR-GEN', 'TSK-TT-SUBGRADE-PREPARATION', 30),
  ('ASM-TT-EXTR-GEN', 'TSK-TT-INSTALL', 40),
  ('ASM-TT-EXTR-GEN', 'TSK-TT-BACKFILL-AND-RESTORE', 50),
  ('ASM-TT-EXTR-GEN', 'TSK-TT-CLEAN', 60),
  ('ASM-TT-EXTR-GEN', 'TSK-TT-PUNCH-WALK', 70),
  ('ASM-TT-LAND-EROS', 'TSK-TT-INSPECT-AND-LAY-OUT', 10),
  ('ASM-TT-LAND-EROS', 'TSK-TT-INSTALL-SILT-FENCE-AND-WATTLES', 20),
  ('ASM-TT-LAND-EROS', 'TSK-TT-INLET-PROTECTION', 30),
  ('ASM-TT-LAND-EROS', 'TSK-TT-STABILIZE-SLOPES', 40),
  ('ASM-TT-LAND-EROS', 'TSK-TT-SEED-AND-BLANKET', 50),
  ('ASM-TT-LAND-EROS', 'TSK-TT-MONITOR-AND-MAINTAIN', 60),
  ('ASM-TT-LAND-EROS', 'TSK-TT-REMOVE-AT-CLOSEOUT', 70),
  ('ASM-TT-LAND-TURF', 'TSK-TT-SOIL-PREPARATION', 10),
  ('ASM-TT-LAND-TURF', 'TSK-TT-AMEND-AND-TILL', 20),
  ('ASM-TT-LAND-TURF', 'TSK-TT-FINE-GRADE', 30),
  ('ASM-TT-LAND-TURF', 'TSK-TT-SEED-OR-LAY-SOD', 40),
  ('ASM-TT-LAND-TURF', 'TSK-TT-ROLL', 50),
  ('ASM-TT-LAND-TURF', 'TSK-TT-SET-WATERING-SCHEDULE', 60),
  ('ASM-TT-LAND-TURF', 'TSK-TT-FIRST-MOW', 70),
  ('ASM-TT-LAND-TURF', 'TSK-TT-REPAIR-THIN-AREAS', 80),
  ('ASM-TT-LAND-HARD', 'TSK-TT-LAYOUT', 10),
  ('ASM-TT-LAND-HARD', 'TSK-TT-EXCAVATE', 20),
  ('ASM-TT-LAND-HARD', 'TSK-TT-BASE-AND-COMPACT', 30),
  ('ASM-TT-LAND-HARD', 'TSK-TT-BEDDING-COURSE', 40),
  ('ASM-TT-LAND-HARD', 'TSK-TT-SET-PAVERS-OR-STONE', 50),
  ('ASM-TT-LAND-HARD', 'TSK-TT-CUT-EDGES', 60),
  ('ASM-TT-LAND-HARD', 'TSK-TT-JOINT-SAND', 70),
  ('ASM-TT-LAND-HARD', 'TSK-TT-COMPACT-AND-CLEAN', 80),
  ('ASM-TT-LAND-HARD', 'TSK-TT-SEAL', 90),
  ('ASM-TT-LAND-PREP', 'TSK-TT-CLEAR', 10),
  ('ASM-TT-LAND-PREP', 'TSK-TT-STRIP', 20),
  ('ASM-TT-LAND-PREP', 'TSK-TT-REMOVE-DEBRIS', 30),
  ('ASM-TT-LAND-PREP', 'TSK-TT-ROUGH-GRADE', 40),
  ('ASM-TT-LAND-PREP', 'TSK-TT-SOIL-TEST', 50),
  ('ASM-TT-LAND-PREP', 'TSK-TT-AMEND', 60),
  ('ASM-TT-LAND-PREP', 'TSK-TT-VERIFY-DRAINAGE', 70),
  ('ASM-TT-EXTR-PAVE', 'TSK-TT-LAYOUT', 10),
  ('ASM-TT-EXTR-PAVE', 'TSK-TT-EXCAVATE', 20),
  ('ASM-TT-EXTR-PAVE', 'TSK-TT-BASE-COURSE', 30),
  ('ASM-TT-EXTR-PAVE', 'TSK-TT-PROOF-ROLL', 40),
  ('ASM-TT-EXTR-PAVE', 'TSK-TT-PLACE-SURFACE-COURSE', 50),
  ('ASM-TT-EXTR-PAVE', 'TSK-TT-COMPACT', 60),
  ('ASM-TT-EXTR-PAVE', 'TSK-TT-JOINTS-AND-SEAMS', 70),
  ('ASM-TT-EXTR-PAVE', 'TSK-TT-STRIPING', 80),
  ('ASM-TT-EXTR-PAVE', 'TSK-TT-CLEAN', 90),
  ('ASM-TT-LAND-EDGE', 'TSK-TT-LAYOUT', 10),
  ('ASM-TT-LAND-EDGE', 'TSK-TT-TRENCH', 20),
  ('ASM-TT-LAND-EDGE', 'TSK-TT-SET-EDGING', 30),
  ('ASM-TT-LAND-EDGE', 'TSK-TT-STAKE-AND-SECURE', 40),
  ('ASM-TT-LAND-EDGE', 'TSK-TT-BACKFILL', 50),
  ('ASM-TT-LAND-EDGE', 'TSK-TT-CLEAN', 60),
  ('ASM-TT-SECU-STD', 'TSK-TT-SURVEY-AND-DEVICE-LAYOUT', 10),
  ('ASM-TT-SECU-STD', 'TSK-TT-ROUGH-PATHWAYS-AND-BOXES', 20),
  ('ASM-TT-SECU-STD', 'TSK-TT-PULL-CABLE', 30),
  ('ASM-TT-SECU-STD', 'TSK-TT-MOUNT-DEVICES', 40),
  ('ASM-TT-SECU-STD', 'TSK-TT-TERMINATE', 50),
  ('ASM-TT-SECU-STD', 'TSK-TT-HEAD-END-AND-PROGRAMMING', 60),
  ('ASM-TT-SECU-STD', 'TSK-TT-TEST-AND-VERIFY', 70),
  ('ASM-TT-SECU-STD', 'TSK-TT-OWNER-TRAINING', 80),
  ('ASM-TT-SECU-STD', 'TSK-TT-DOCUMENTATION-AND-CLOSEOUT', 90),
  ('ASM-TT-EXTR-LAND', 'TSK-TT-LAYOUT', 10),
  ('ASM-TT-EXTR-LAND', 'TSK-TT-PREPARE-BEDS', 20),
  ('ASM-TT-EXTR-LAND', 'TSK-TT-INSTALL', 30),
  ('ASM-TT-EXTR-LAND', 'TSK-TT-MULCH-AND-FINISH', 40),
  ('ASM-TT-EXTR-LAND', 'TSK-TT-WATER-IN', 50),
  ('ASM-TT-EXTR-LAND', 'TSK-TT-CLEAN', 60),
  ('ASM-TT-EXTR-FENCE', 'TSK-TT-LAYOUT-AND-LOCATE-UTILITIES', 10),
  ('ASM-TT-EXTR-FENCE', 'TSK-TT-SET-POSTS', 20),
  ('ASM-TT-EXTR-FENCE', 'TSK-TT-CONCRETE-FOOTINGS', 30),
  ('ASM-TT-EXTR-FENCE', 'TSK-TT-CURE', 40),
  ('ASM-TT-EXTR-FENCE', 'TSK-TT-HANG-RAILS-AND-PANELS', 50),
  ('ASM-TT-EXTR-FENCE', 'TSK-TT-GATES-AND-HARDWARE', 60),
  ('ASM-TT-EXTR-FENCE', 'TSK-TT-ADJUST-AND-ALIGN', 70),
  ('ASM-TT-EXTR-FENCE', 'TSK-TT-CLEAN', 80),
  ('ASM-TT-DRN-MEDIA', 'TSK-TT-FLIGHT-PLAN-AND-PERMISSIONS', 10),
  ('ASM-TT-DRN-MEDIA', 'TSK-TT-SITE-BRIEF-AND-SAFETY', 20),
  ('ASM-TT-DRN-MEDIA', 'TSK-TT-CAPTURE', 30),
  ('ASM-TT-DRN-MEDIA', 'TSK-TT-REVIEW-ON-SITE', 40),
  ('ASM-TT-DRN-MEDIA', 'TSK-TT-PROCESS-AND-EDIT', 50),
  ('ASM-TT-DRN-MEDIA', 'TSK-TT-DELIVER', 60),
  ('ASM-TT-COMM-STD', 'TSK-TT-SURVEY-AND-PATHWAY-LAYOUT', 10),
  ('ASM-TT-COMM-STD', 'TSK-TT-INSTALL-PATHWAYS', 20),
  ('ASM-TT-COMM-STD', 'TSK-TT-PULL-CABLE', 30),
  ('ASM-TT-COMM-STD', 'TSK-TT-TERMINATE', 40),
  ('ASM-TT-COMM-STD', 'TSK-TT-LABEL', 50),
  ('ASM-TT-COMM-STD', 'TSK-TT-CERTIFY-AND-TEST', 60),
  ('ASM-TT-COMM-STD', 'TSK-TT-AS-BUILT-DOCUMENTATION', 70),
  ('ASM-TT-COMM-STD', 'TSK-TT-CLOSEOUT', 80),
  ('ASM-TT-EXTR-PARK', 'TSK-TT-LAYOUT', 10),
  ('ASM-TT-EXTR-PARK', 'TSK-TT-SUBGRADE-PREPARATION', 20),
  ('ASM-TT-EXTR-PARK', 'TSK-TT-BASE-COURSE', 30),
  ('ASM-TT-EXTR-PARK', 'TSK-TT-PAVING', 40),
  ('ASM-TT-EXTR-PARK', 'TSK-TT-STRIPING', 50),
  ('ASM-TT-EXTR-PARK', 'TSK-TT-SIGNAGE-AND-WHEEL-STOPS', 60),
  ('ASM-TT-EXTR-PARK', 'TSK-TT-CLEAN', 70),
  ('ASM-TT-EXTR-WALL', 'TSK-TT-LAYOUT', 10),
  ('ASM-TT-EXTR-WALL', 'TSK-TT-EXCAVATE', 20),
  ('ASM-TT-EXTR-WALL', 'TSK-TT-LEVELING-PAD', 30),
  ('ASM-TT-EXTR-WALL', 'TSK-TT-SET-UNITS', 40),
  ('ASM-TT-EXTR-WALL', 'TSK-TT-DRAINAGE-STONE-AND-PIPE', 50),
  ('ASM-TT-EXTR-WALL', 'TSK-TT-GEOGRID-AS-REQUIRED', 60),
  ('ASM-TT-EXTR-WALL', 'TSK-TT-BACKFILL-AND-COMPACT', 70),
  ('ASM-TT-EXTR-WALL', 'TSK-TT-CAP-UNITS', 80),
  ('ASM-TT-EXTR-WALL', 'TSK-TT-CLEAN', 90),
  ('ASM-TT-EXTR-CONC', 'TSK-TT-LAYOUT', 10),
  ('ASM-TT-EXTR-CONC', 'TSK-TT-SET-FORMS', 20),
  ('ASM-TT-EXTR-CONC', 'TSK-TT-REINFORCE', 30),
  ('ASM-TT-EXTR-CONC', 'TSK-TT-PLACE-CONCRETE', 40),
  ('ASM-TT-EXTR-CONC', 'TSK-TT-FINISH', 50),
  ('ASM-TT-EXTR-CONC', 'TSK-TT-CURE', 60),
  ('ASM-TT-EXTR-CONC', 'TSK-TT-STRIP-FORMS', 70),
  ('ASM-TT-EXTR-CONC', 'TSK-TT-CLEAN', 80),
  ('ASM-TT-EXTR-FURN', 'TSK-TT-LAYOUT', 10),
  ('ASM-TT-EXTR-FURN', 'TSK-TT-FOOTINGS', 20),
  ('ASM-TT-EXTR-FURN', 'TSK-TT-SET-UNITS', 30),
  ('ASM-TT-EXTR-FURN', 'TSK-TT-ANCHOR', 40),
  ('ASM-TT-EXTR-FURN', 'TSK-TT-ADJUST-AND-LEVEL', 50),
  ('ASM-TT-EXTR-FURN', 'TSK-TT-CLEAN', 60),
  ('ASM-TT-RMOD-FRME', 'TSK-TT-PROTECT-AND-ISOLATE', 10),
  ('ASM-TT-RMOD-FRME', 'TSK-TT-SELECTIVE-DEMOLITION', 20),
  ('ASM-TT-RMOD-FRME', 'TSK-TT-SHORE-AS-NEEDED', 30),
  ('ASM-TT-RMOD-FRME', 'TSK-TT-FRAME-NEW-WORK', 40),
  ('ASM-TT-RMOD-FRME', 'TSK-TT-SHEATHE', 50),
  ('ASM-TT-RMOD-FRME', 'TSK-TT-VERIFY-PLUMB-AND-LINE', 60),
  ('ASM-TT-RMOD-FRME', 'TSK-TT-CLEAN', 70),
  ('ASM-TT-EXTR-IRR', 'TSK-TT-LAYOUT-AND-LOCATE-UTILITIES', 10),
  ('ASM-TT-EXTR-IRR', 'TSK-TT-TRENCH', 20),
  ('ASM-TT-EXTR-IRR', 'TSK-TT-INSTALL-PIPE-AND-HEADS', 30),
  ('ASM-TT-EXTR-IRR', 'TSK-TT-VALVES-AND-CONTROLLER', 40),
  ('ASM-TT-EXTR-IRR', 'TSK-TT-PRESSURE-TEST', 50),
  ('ASM-TT-EXTR-IRR', 'TSK-TT-BACKFILL-AND-RESTORE', 60),
  ('ASM-TT-EXTR-IRR', 'TSK-TT-PROGRAM-AND-HAND-OVER', 70),
  ('ASM-TT-RMOD-DEMO', 'TSK-TT-PROTECT-AND-ISOLATE', 10),
  ('ASM-TT-RMOD-DEMO', 'TSK-TT-DISCONNECT-UTILITIES', 20),
  ('ASM-TT-RMOD-DEMO', 'TSK-TT-SELECTIVE-DEMOLITION', 30),
  ('ASM-TT-RMOD-DEMO', 'TSK-TT-SORT-AND-HAUL-DEBRIS', 40),
  ('ASM-TT-RMOD-DEMO', 'TSK-TT-CLEAN', 50),
  ('ASM-TT-RMOD-DEMO', 'TSK-TT-VERIFY-SCOPE-REMOVED', 60)
) as v(assembly_code, task_code, sort)
join assemblies a on a.code = v.assembly_code and a.company_id is null
join tasks t on t.code = v.task_code and t.company_id is null
on conflict do nothing;

/*
 * And the services that were waiting for them.
 *
 * `default_assembly_id` was left null on every product-master service whose
 * sequence did not exist yet. This is the join the file always intended, run
 * now that the other side is here — from the file's own
 * `reusable_task_template_code`, not from a guess about which sequence suits
 * which service.
 *
 * Only rows that are still unlinked are touched. A service somebody has since
 * pointed at their own assembly keeps it.
 */
update services s
   set default_assembly_id = a.id,
       updated_at = now()
  from (values
  ('SVC-PM-00310', 'ASM-TT-COMM-STD'),
  ('SVC-PM-00311', 'ASM-TT-COMM-STD'),
  ('SVC-PM-00312', 'ASM-TT-COMM-STD'),
  ('SVC-PM-00313', 'ASM-TT-COMM-STD'),
  ('SVC-PM-00314', 'ASM-TT-COMM-STD'),
  ('SVC-PM-00003', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00004', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00005', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00006', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00007', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00008', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00009', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00010', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00011', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00012', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00013', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00014', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00015', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00016', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00017', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00018', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00019', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00020', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00021', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00022', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00023', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00024', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00025', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00026', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00027', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00028', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00029', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00030', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00031', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00032', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00033', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00034', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00035', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00036', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00037', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00038', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00039', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00040', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00041', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00042', 'ASM-TT-CONC-FLT'),
  ('SVC-PM-00816', 'ASM-TT-DRN-MEDIA'),
  ('SVC-PM-00817', 'ASM-TT-DRN-MEDIA'),
  ('SVC-PM-00831', 'ASM-TT-DRN-MEDIA'),
  ('SVC-PM-00838', 'ASM-TT-DRN-MEDIA'),
  ('SVC-PM-00847', 'ASM-TT-DRN-MEDIA'),
  ('SVC-PM-00848', 'ASM-TT-DRN-MEDIA'),
  ('SVC-PM-00355', 'ASM-TT-GEN-STD'),
  ('SVC-PM-00356', 'ASM-TT-GEN-STD'),
  ('SVC-PM-00479', 'ASM-TT-SECU-STD'),
  ('SVC-PM-00480', 'ASM-TT-SECU-STD'),
  ('SVC-PM-00481', 'ASM-TT-SECU-STD'),
  ('SVC-PM-00482', 'ASM-TT-SECU-STD'),
  ('SVC-PM-00483', 'ASM-TT-SECU-STD'),
  ('SVC-PM-00484', 'ASM-TT-SECU-STD'),
  ('SVC-PM-00485', 'ASM-TT-SECU-STD'),
  ('SVC-PM-00486', 'ASM-TT-SECU-STD'),
  ('SVC-PM-01157', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01158', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01159', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01170', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01184', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01215', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01221', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01293', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01300', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01310', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01311', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01365', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01391', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01402', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01403', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01414', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01483', 'ASM-TT-EXTR-FENCE'),
  ('SVC-PM-01491', 'ASM-TT-EXTR-FENCE'),
  ('SVC-PM-01493', 'ASM-TT-EXTR-FENCE'),
  ('SVC-PM-01499', 'ASM-TT-EXTR-FENCE'),
  ('SVC-PM-01501', 'ASM-TT-EXTR-FENCE'),
  ('SVC-PM-01508', 'ASM-TT-EXTR-FENCE'),
  ('SVC-PM-01532', 'ASM-TT-EXTR-FENCE'),
  ('SVC-PM-01494', 'ASM-TT-EXTR-GEN'),
  ('SVC-PM-01495', 'ASM-TT-EXTR-GEN'),
  ('SVC-PM-01496', 'ASM-TT-EXTR-GEN'),
  ('SVC-PM-01498', 'ASM-TT-EXTR-GEN'),
  ('SVC-PM-01506', 'ASM-TT-EXTR-GEN'),
  ('SVC-PM-01509', 'ASM-TT-EXTR-GEN'),
  ('SVC-PM-01511', 'ASM-TT-EXTR-GEN'),
  ('SVC-PM-01515', 'ASM-TT-EXTR-GEN'),
  ('SVC-PM-01521', 'ASM-TT-EXTR-GEN'),
  ('SVC-PM-01524', 'ASM-TT-EXTR-GEN'),
  ('SVC-PM-01525', 'ASM-TT-EXTR-GEN'),
  ('SVC-PM-01528', 'ASM-TT-EXTR-GEN'),
  ('SVC-PM-01529', 'ASM-TT-EXTR-GEN'),
  ('SVC-PM-01503', 'ASM-TT-EXTR-IRR'),
  ('SVC-PM-01502', 'ASM-TT-EXTR-LAND'),
  ('SVC-PM-01504', 'ASM-TT-EXTR-LAND'),
  ('SVC-PM-01505', 'ASM-TT-EXTR-LAND'),
  ('SVC-PM-01507', 'ASM-TT-EXTR-LAND'),
  ('SVC-PM-01518', 'ASM-TT-EXTR-LAND'),
  ('SVC-PM-01520', 'ASM-TT-EXTR-LAND'),
  ('SVC-PM-01522', 'ASM-TT-EXTR-LAND'),
  ('SVC-PM-01530', 'ASM-TT-EXTR-LAND'),
  ('SVC-PM-01523', 'ASM-TT-EXTR-PARK'),
  ('SVC-PM-01526', 'ASM-TT-EXTR-PARK'),
  ('SVC-PM-01531', 'ASM-TT-EXTR-PARK'),
  ('SVC-PM-01484', 'ASM-TT-EXTR-PAVE'),
  ('SVC-PM-01485', 'ASM-TT-EXTR-PAVE'),
  ('SVC-PM-01486', 'ASM-TT-EXTR-PAVE'),
  ('SVC-PM-01487', 'ASM-TT-EXTR-PAVE'),
  ('SVC-PM-01488', 'ASM-TT-EXTR-PAVE'),
  ('SVC-PM-01489', 'ASM-TT-EXTR-PAVE'),
  ('SVC-PM-01497', 'ASM-TT-EXTR-PAVE'),
  ('SVC-PM-01500', 'ASM-TT-EXTR-PAVE'),
  ('SVC-PM-01510', 'ASM-TT-EXTR-PAVE'),
  ('SVC-PM-01516', 'ASM-TT-EXTR-PAVE'),
  ('SVC-PM-01517', 'ASM-TT-EXTR-PAVE'),
  ('SVC-PM-01492', 'ASM-TT-EXTR-WALL'),
  ('SVC-PM-01519', 'ASM-TT-EXTR-WALL'),
  ('SVC-PM-01527', 'ASM-TT-EXTR-WALL'),
  ('SVC-PM-01512', 'ASM-TT-EXTR-CONC'),
  ('SVC-PM-01513', 'ASM-TT-EXTR-CONC'),
  ('SVC-PM-01490', 'ASM-TT-EXTR-FURN'),
  ('SVC-PM-01514', 'ASM-TT-EXTR-FURN'),
  ('SVC-PM-00064', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00065', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00066', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00067', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00068', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00069', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00070', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00071', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00072', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00073', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00074', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00075', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00076', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00077', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00078', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00079', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00080', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00081', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00082', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00083', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00084', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00085', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00086', 'ASM-TT-FRME-STD'),
  ('SVC-PM-00357', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00358', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00359', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00360', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00361', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00362', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00363', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00364', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00365', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00366', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00367', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00368', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00369', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00370', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00371', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00372', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00373', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00374', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00375', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00376', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00377', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00378', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00379', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00380', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00381', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00382', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00383', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00384', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00385', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00386', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00387', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00388', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00389', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00390', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00391', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00392', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00393', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00394', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00395', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00396', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-00397', 'ASM-TT-HVAC-EQP'),
  ('SVC-PM-01974', 'ASM-TT-LAND-DRNG'),
  ('SVC-PM-01969', 'ASM-TT-LAND-DRNG'),
  ('SVC-PM-01970', 'ASM-TT-LAND-DRNG'),
  ('SVC-PM-01980', 'ASM-TT-LAND-DRNG'),
  ('SVC-PM-01979', 'ASM-TT-LAND-DRNG'),
  ('SVC-PM-01972', 'ASM-TT-LAND-DRNG'),
  ('SVC-PM-01982', 'ASM-TT-LAND-DRNG'),
  ('SVC-PM-01978', 'ASM-TT-LAND-DRNG'),
  ('SVC-PM-01971', 'ASM-TT-LAND-DRNG'),
  ('SVC-PM-01976', 'ASM-TT-LAND-DRNG'),
  ('SVC-PM-01973', 'ASM-TT-LAND-DRNG'),
  ('SVC-PM-01977', 'ASM-TT-LAND-DRNG'),
  ('SVC-PM-01975', 'ASM-TT-LAND-DRNG'),
  ('SVC-PM-01981', 'ASM-TT-LAND-DRNG'),
  ('SVC-PM-01968', 'ASM-TT-LAND-DRNG'),
  ('SVC-PM-01934', 'ASM-TT-LAND-EDGE'),
  ('SVC-PM-01940', 'ASM-TT-LAND-EDGE'),
  ('SVC-PM-01941', 'ASM-TT-LAND-EDGE'),
  ('SVC-PM-01937', 'ASM-TT-LAND-EDGE'),
  ('SVC-PM-01936', 'ASM-TT-LAND-EDGE'),
  ('SVC-PM-01942', 'ASM-TT-LAND-EDGE'),
  ('SVC-PM-01938', 'ASM-TT-LAND-EDGE'),
  ('SVC-PM-01935', 'ASM-TT-LAND-EDGE'),
  ('SVC-PM-01933', 'ASM-TT-LAND-EDGE'),
  ('SVC-PM-01939', 'ASM-TT-LAND-EDGE'),
  ('SVC-PM-02019', 'ASM-TT-LAND-EROS'),
  ('SVC-PM-02023', 'ASM-TT-LAND-EROS'),
  ('SVC-PM-02022', 'ASM-TT-LAND-EROS'),
  ('SVC-PM-02024', 'ASM-TT-LAND-EROS'),
  ('SVC-PM-02015', 'ASM-TT-LAND-EROS'),
  ('SVC-PM-02014', 'ASM-TT-LAND-EROS'),
  ('SVC-PM-02026', 'ASM-TT-LAND-EROS'),
  ('SVC-PM-02025', 'ASM-TT-LAND-EROS'),
  ('SVC-PM-02017', 'ASM-TT-LAND-EROS'),
  ('SVC-PM-02021', 'ASM-TT-LAND-EROS'),
  ('SVC-PM-02020', 'ASM-TT-LAND-EROS'),
  ('SVC-PM-02016', 'ASM-TT-LAND-EROS'),
  ('SVC-PM-02018', 'ASM-TT-LAND-EROS'),
  ('SVC-PM-02050', 'ASM-TT-LAND-MAINT'),
  ('SVC-PM-02057', 'ASM-TT-LAND-MAINT'),
  ('SVC-PM-02060', 'ASM-TT-LAND-MAINT'),
  ('SVC-PM-02054', 'ASM-TT-LAND-MAINT'),
  ('SVC-PM-02048', 'ASM-TT-LAND-MAINT'),
  ('SVC-PM-02062', 'ASM-TT-LAND-MAINT'),
  ('SVC-PM-02053', 'ASM-TT-LAND-MAINT'),
  ('SVC-PM-02049', 'ASM-TT-LAND-MAINT'),
  ('SVC-PM-02051', 'ASM-TT-LAND-MAINT'),
  ('SVC-PM-02055', 'ASM-TT-LAND-MAINT'),
  ('SVC-PM-02052', 'ASM-TT-LAND-MAINT'),
  ('SVC-PM-02061', 'ASM-TT-LAND-MAINT'),
  ('SVC-PM-02058', 'ASM-TT-LAND-MAINT'),
  ('SVC-PM-02047', 'ASM-TT-LAND-MAINT'),
  ('SVC-PM-02059', 'ASM-TT-LAND-MAINT'),
  ('SVC-PM-02056', 'ASM-TT-LAND-MAINT'),
  ('SVC-PM-01950', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01967', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01951', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01952', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01955', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01965', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01947', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01966', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01944', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01964', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01943', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01963', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01946', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01961', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01945', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01954', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01962', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01960', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01958', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01959', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01957', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01949', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01956', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01948', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-01953', 'ASM-TT-LAND-IRRG'),
  ('SVC-PM-02029', 'ASM-TT-LAND-FEAT'),
  ('SVC-PM-02043', 'ASM-TT-LAND-FEAT'),
  ('SVC-PM-02045', 'ASM-TT-LAND-FEAT'),
  ('SVC-PM-02039', 'ASM-TT-LAND-FEAT'),
  ('SVC-PM-02037', 'ASM-TT-LAND-FEAT'),
  ('SVC-PM-02034', 'ASM-TT-LAND-FEAT'),
  ('SVC-PM-02031', 'ASM-TT-LAND-FEAT'),
  ('SVC-PM-02027', 'ASM-TT-LAND-FEAT'),
  ('SVC-PM-02044', 'ASM-TT-LAND-FEAT'),
  ('SVC-PM-02040', 'ASM-TT-LAND-FEAT'),
  ('SVC-PM-02046', 'ASM-TT-LAND-FEAT'),
  ('SVC-PM-02036', 'ASM-TT-LAND-FEAT'),
  ('SVC-PM-02035', 'ASM-TT-LAND-FEAT'),
  ('SVC-PM-02038', 'ASM-TT-LAND-FEAT'),
  ('SVC-PM-02041', 'ASM-TT-LAND-FEAT'),
  ('SVC-PM-02032', 'ASM-TT-LAND-FEAT'),
  ('SVC-PM-02030', 'ASM-TT-LAND-FEAT'),
  ('SVC-PM-02042', 'ASM-TT-LAND-FEAT'),
  ('SVC-PM-02028', 'ASM-TT-LAND-FEAT'),
  ('SVC-PM-02033', 'ASM-TT-LAND-FEAT'),
  ('SVC-PM-01919', 'ASM-TT-LAND-SURF'),
  ('SVC-PM-01928', 'ASM-TT-LAND-SURF'),
  ('SVC-PM-01927', 'ASM-TT-LAND-SURF'),
  ('SVC-PM-01932', 'ASM-TT-LAND-SURF'),
  ('SVC-PM-01931', 'ASM-TT-LAND-SURF'),
  ('SVC-PM-01920', 'ASM-TT-LAND-SURF'),
  ('SVC-PM-01926', 'ASM-TT-LAND-SURF'),
  ('SVC-PM-01925', 'ASM-TT-LAND-SURF'),
  ('SVC-PM-01918', 'ASM-TT-LAND-SURF'),
  ('SVC-PM-01924', 'ASM-TT-LAND-SURF'),
  ('SVC-PM-01921', 'ASM-TT-LAND-SURF'),
  ('SVC-PM-01922', 'ASM-TT-LAND-SURF'),
  ('SVC-PM-01929', 'ASM-TT-LAND-SURF'),
  ('SVC-PM-01923', 'ASM-TT-LAND-SURF'),
  ('SVC-PM-01930', 'ASM-TT-LAND-SURF'),
  ('SVC-PM-01904', 'ASM-TT-LAND-PLNT'),
  ('SVC-PM-01911', 'ASM-TT-LAND-PLNT'),
  ('SVC-PM-01912', 'ASM-TT-LAND-PLNT'),
  ('SVC-PM-01901', 'ASM-TT-LAND-PLNT'),
  ('SVC-PM-01902', 'ASM-TT-LAND-PLNT'),
  ('SVC-PM-01909', 'ASM-TT-LAND-PLNT'),
  ('SVC-PM-01905', 'ASM-TT-LAND-PLNT'),
  ('SVC-PM-01907', 'ASM-TT-LAND-PLNT'),
  ('SVC-PM-01906', 'ASM-TT-LAND-PLNT'),
  ('SVC-PM-01903', 'ASM-TT-LAND-PLNT'),
  ('SVC-PM-01916', 'ASM-TT-LAND-PLNT'),
  ('SVC-PM-01917', 'ASM-TT-LAND-PLNT'),
  ('SVC-PM-01900', 'ASM-TT-LAND-PLNT'),
  ('SVC-PM-01908', 'ASM-TT-LAND-PLNT'),
  ('SVC-PM-01913', 'ASM-TT-LAND-PLNT'),
  ('SVC-PM-01910', 'ASM-TT-LAND-PLNT'),
  ('SVC-PM-01914', 'ASM-TT-LAND-PLNT'),
  ('SVC-PM-01915', 'ASM-TT-LAND-PLNT'),
  ('SVC-PM-01991', 'ASM-TT-LAND-HARD'),
  ('SVC-PM-01989', 'ASM-TT-LAND-HARD'),
  ('SVC-PM-01983', 'ASM-TT-LAND-HARD'),
  ('SVC-PM-01992', 'ASM-TT-LAND-HARD'),
  ('SVC-PM-01985', 'ASM-TT-LAND-HARD'),
  ('SVC-PM-01993', 'ASM-TT-LAND-HARD'),
  ('SVC-PM-01994', 'ASM-TT-LAND-HARD'),
  ('SVC-PM-01986', 'ASM-TT-LAND-HARD'),
  ('SVC-PM-01987', 'ASM-TT-LAND-HARD'),
  ('SVC-PM-01984', 'ASM-TT-LAND-HARD'),
  ('SVC-PM-01990', 'ASM-TT-LAND-HARD'),
  ('SVC-PM-01988', 'ASM-TT-LAND-HARD'),
  ('SVC-PM-01868', 'ASM-TT-LAND-PREP'),
  ('SVC-PM-01864', 'ASM-TT-LAND-PREP'),
  ('SVC-PM-01859', 'ASM-TT-LAND-PREP'),
  ('SVC-PM-01863', 'ASM-TT-LAND-PREP'),
  ('SVC-PM-01870', 'ASM-TT-LAND-PREP'),
  ('SVC-PM-01869', 'ASM-TT-LAND-PREP'),
  ('SVC-PM-01862', 'ASM-TT-LAND-PREP'),
  ('SVC-PM-01867', 'ASM-TT-LAND-PREP'),
  ('SVC-PM-01860', 'ASM-TT-LAND-PREP'),
  ('SVC-PM-01865', 'ASM-TT-LAND-PREP'),
  ('SVC-PM-01861', 'ASM-TT-LAND-PREP'),
  ('SVC-PM-01866', 'ASM-TT-LAND-PREP'),
  ('SVC-PM-01878', 'ASM-TT-LAND-GRAD'),
  ('SVC-PM-01873', 'ASM-TT-LAND-GRAD'),
  ('SVC-PM-01874', 'ASM-TT-LAND-GRAD'),
  ('SVC-PM-01872', 'ASM-TT-LAND-GRAD'),
  ('SVC-PM-01886', 'ASM-TT-LAND-GRAD'),
  ('SVC-PM-01883', 'ASM-TT-LAND-GRAD'),
  ('SVC-PM-01884', 'ASM-TT-LAND-GRAD'),
  ('SVC-PM-01871', 'ASM-TT-LAND-GRAD'),
  ('SVC-PM-01882', 'ASM-TT-LAND-GRAD'),
  ('SVC-PM-01877', 'ASM-TT-LAND-GRAD'),
  ('SVC-PM-01879', 'ASM-TT-LAND-GRAD'),
  ('SVC-PM-01880', 'ASM-TT-LAND-GRAD'),
  ('SVC-PM-01881', 'ASM-TT-LAND-GRAD'),
  ('SVC-PM-01885', 'ASM-TT-LAND-GRAD'),
  ('SVC-PM-01875', 'ASM-TT-LAND-GRAD'),
  ('SVC-PM-01876', 'ASM-TT-LAND-GRAD'),
  ('SVC-PM-02001', 'ASM-TT-LAND-CARE'),
  ('SVC-PM-02013', 'ASM-TT-LAND-CARE'),
  ('SVC-PM-01997', 'ASM-TT-LAND-CARE'),
  ('SVC-PM-01998', 'ASM-TT-LAND-CARE'),
  ('SVC-PM-02002', 'ASM-TT-LAND-CARE'),
  ('SVC-PM-02010', 'ASM-TT-LAND-CARE'),
  ('SVC-PM-02011', 'ASM-TT-LAND-CARE'),
  ('SVC-PM-02000', 'ASM-TT-LAND-CARE'),
  ('SVC-PM-02005', 'ASM-TT-LAND-CARE'),
  ('SVC-PM-02006', 'ASM-TT-LAND-CARE'),
  ('SVC-PM-01999', 'ASM-TT-LAND-CARE'),
  ('SVC-PM-02004', 'ASM-TT-LAND-CARE'),
  ('SVC-PM-02012', 'ASM-TT-LAND-CARE'),
  ('SVC-PM-02007', 'ASM-TT-LAND-CARE'),
  ('SVC-PM-01995', 'ASM-TT-LAND-CARE'),
  ('SVC-PM-02003', 'ASM-TT-LAND-CARE'),
  ('SVC-PM-02008', 'ASM-TT-LAND-CARE'),
  ('SVC-PM-02009', 'ASM-TT-LAND-CARE'),
  ('SVC-PM-01996', 'ASM-TT-LAND-CARE'),
  ('SVC-PM-01897', 'ASM-TT-LAND-TURF'),
  ('SVC-PM-01890', 'ASM-TT-LAND-TURF'),
  ('SVC-PM-01898', 'ASM-TT-LAND-TURF'),
  ('SVC-PM-01899', 'ASM-TT-LAND-TURF'),
  ('SVC-PM-01887', 'ASM-TT-LAND-TURF'),
  ('SVC-PM-01888', 'ASM-TT-LAND-TURF'),
  ('SVC-PM-01891', 'ASM-TT-LAND-TURF'),
  ('SVC-PM-01892', 'ASM-TT-LAND-TURF'),
  ('SVC-PM-01889', 'ASM-TT-LAND-TURF'),
  ('SVC-PM-01896', 'ASM-TT-LAND-TURF'),
  ('SVC-PM-01894', 'ASM-TT-LAND-TURF'),
  ('SVC-PM-01895', 'ASM-TT-LAND-TURF'),
  ('SVC-PM-01893', 'ASM-TT-LAND-TURF'),
  ('SVC-PM-00090', 'ASM-TT-MASN-STD'),
  ('SVC-PM-00091', 'ASM-TT-MASN-STD'),
  ('SVC-PM-00092', 'ASM-TT-MASN-STD'),
  ('SVC-PM-00093', 'ASM-TT-MASN-STD'),
  ('SVC-PM-00094', 'ASM-TT-MASN-STD'),
  ('SVC-PM-00095', 'ASM-TT-MASN-STD'),
  ('SVC-PM-00096', 'ASM-TT-MASN-STD'),
  ('SVC-PM-00097', 'ASM-TT-MASN-STD'),
  ('SVC-PM-00098', 'ASM-TT-MASN-STD'),
  ('SVC-PM-00099', 'ASM-TT-MASN-STD'),
  ('SVC-PM-00100', 'ASM-TT-MASN-STD'),
  ('SVC-PM-00101', 'ASM-TT-MASN-STD'),
  ('SVC-PM-00102', 'ASM-TT-MASN-STD'),
  ('SVC-PM-00103', 'ASM-TT-MASN-STD'),
  ('SVC-PM-00104', 'ASM-TT-MASN-STD'),
  ('SVC-PM-00105', 'ASM-TT-MASN-STD'),
  ('SVC-PM-00106', 'ASM-TT-MASN-STD'),
  ('SVC-PM-00107', 'ASM-TT-MASN-STD'),
  ('SVC-PM-00108', 'ASM-TT-MASN-STD'),
  ('SVC-PM-00109', 'ASM-TT-MASN-STD'),
  ('SVC-PM-01671', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01672', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01735', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01736', 'ASM-TT-GEN-STD'),
  ('SVC-PM-00120', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00121', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00122', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00123', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00124', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00125', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00126', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00127', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00268', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00269', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00128', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00129', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00130', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00131', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00133', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00134', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00135', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00270', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00137', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00138', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00139', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00140', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00141', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00271', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00142', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00143', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00144', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00272', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00145', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00146', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00273', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00147', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00148', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00149', 'ASM-TT-RMOD-FINI'),
  ('SVC-PM-00132', 'ASM-TT-RMOD-FRME'),
  ('SVC-PM-00136', 'ASM-TT-RMOD-FRME'),
  ('SVC-PM-00960', 'ASM-TT-RMOD-DEMO'),
  ('SVC-PM-00150', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00151', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00152', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00153', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00154', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00155', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00156', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00157', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00158', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00159', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00160', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00161', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00162', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00163', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00164', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00165', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00166', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00167', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00168', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00169', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00170', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00171', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00172', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00173', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00174', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00175', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00176', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00177', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00178', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00179', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00180', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00181', 'ASM-TT-ROOF-STD'),
  ('SVC-PM-00182', 'ASM-TT-SIDE-STD'),
  ('SVC-PM-00183', 'ASM-TT-SIDE-STD'),
  ('SVC-PM-00184', 'ASM-TT-SIDE-STD'),
  ('SVC-PM-00185', 'ASM-TT-SIDE-STD'),
  ('SVC-PM-00186', 'ASM-TT-SIDE-STD'),
  ('SVC-PM-00187', 'ASM-TT-SIDE-STD'),
  ('SVC-PM-00188', 'ASM-TT-SIDE-STD'),
  ('SVC-PM-00189', 'ASM-TT-SIDE-STD'),
  ('SVC-PM-00190', 'ASM-TT-SIDE-STD'),
  ('SVC-PM-00191', 'ASM-TT-SIDE-STD'),
  ('SVC-PM-00192', 'ASM-TT-SIDE-STD'),
  ('SVC-PM-00193', 'ASM-TT-SIDE-STD'),
  ('SVC-PM-00194', 'ASM-TT-SIDE-STD'),
  ('SVC-PM-00195', 'ASM-TT-SIDE-STD'),
  ('SVC-PM-00196', 'ASM-TT-SIDE-STD'),
  ('SVC-PM-01747', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01748', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01749', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01750', 'ASM-TT-GEN-STD'),
  ('SVC-PM-01751', 'ASM-TT-GEN-STD'),
  ('SVC-PM-00487', 'ASM-TT-GEN-STD'),
  ('SVC-PM-00488', 'ASM-TT-GEN-STD'),
  ('SVC-PM-00489', 'ASM-TT-GEN-STD'),
  ('SVC-PM-00490', 'ASM-TT-GEN-STD')
) as v(service_code, assembly_code)
  join assemblies a on a.code = v.assembly_code and a.company_id is null
 where s.company_id is null
   and s.code = v.service_code
   and s.default_assembly_id is null;
