-- =============================================================================
-- 0009 — A materials catalog, uncosted
--
-- The seed shipped no materials, for a stated reason: a price list belongs to
-- the company that negotiated it, and a national average is worse than nothing
-- because it looks like a number. That reasoning was right about prices and
-- wrong about this file. It holds 342 rows, nine of which name a material
-- already named above them; of the 333 that are left, 5 carry a price and
-- 328 carry nothing at all. It is not a price list. It is a *catalog* — the
-- names, the categories, the units and the waste factors of the materials a
-- contractor buys — and that is exactly what a platform should ship and exactly
-- what every company should then cost for itself.
--
-- So all 333 arrive with `unit_cost` as stated, which for 328 of them is zero.
-- Migration 0121 reads a zero as `not_costed` rather than free, so the engine
-- warns on every line that uses one instead of quietly multiplying by it.
-- Nobody is shown a price the platform invented. Migration 0133 is how the zero
-- stops being zero: clicking the cost on a catalog material copies it into the
-- company's own library and puts their price on the copy.
--
-- **37 of them are filed as EA and probably should not be.** Crushed stone,
-- aggregate base, topsoil and asphalt are sold by the ton or the yard, and the
-- export had them as each. They load exactly as they arrived, because turning
-- EA into TON on a guess puts a per-ton price on a per-each material and every
-- estimate built on one is then wrong by a factor nobody will spot.
-- `app.unit_looks_wrong` flags them and `my_uncosted_materials` is where a
-- person works through them; a seed file is not the place to guess.
--
-- Two corrections are made, and both are about a name rather than a number.
-- The export spells one category two ways — 'Tile & Masonry' and 'Tile & masonry' —
-- and `library_categories` holds one name per kind case-insensitively, so a
-- material filed under the second spelling would point at a category that does
-- not exist. The more common spelling wins. And nothing is dropped: an earlier
-- cut of this file refused four rows — framing lumber, PT lumber, architectural
-- shingles and a solar allowance — because their units were BF, SQ and KW and
-- the platform had no such units. That is a gap in the enum rather than a
-- problem with the lumberyard, and 0132 closed it.
-- =============================================================================

insert into library_categories (company_id, kind, name, sort_order)
select null, 'material_category', v.name, 100
from (values
  ('Aggregate & Stone'),
  ('Allowances'),
  ('Asphalt & Paving'),
  ('Cabinets & Countertops'),
  ('Communications'),
  ('Concrete'),
  ('Disposal & Debris'),
  ('Disposal & Export'),
  ('Doors & Windows'),
  ('Drywall & Interior'),
  ('Drywall & Plaster'),
  ('Electrical'),
  ('Erosion Control'),
  ('Flooring'),
  ('Geotechnical'),
  ('Green / Sustainable'),
  ('HVAC'),
  ('Industrial / Process'),
  ('Insulation'),
  ('Insulation & Moisture'),
  ('Landscaping'),
  ('Lumber & Framing'),
  ('Masonry'),
  ('Misc'),
  ('Other'),
  ('Paint & Coating'),
  ('Paint & Finishes'),
  ('Paving'),
  ('Pipe & Utilities'),
  ('Plumbing'),
  ('Roofing'),
  ('Safety & Protection'),
  ('Safety & Temporary'),
  ('Sheathing & Decking'),
  ('Site Work & Erosion'),
  ('Soil & Fill'),
  ('Specialties'),
  ('Specialty'),
  ('Steel & Structural'),
  ('Structural Steel'),
  ('Tile & Masonry'),
  ('Trim & Millwork')
) as v(name)
on conflict do nothing;

insert into materials (company_id, code, name, category, unit, unit_cost,
                       density_lb_per_cy, default_waste_percent, waste_basis,
                       cost_state, origin, status, source)
select null, v.code, v.name, v.category, v.unit::app.unit_code, v.unit_cost,
       v.density, v.waste,
       case when v.waste > 0 then 'Stated in the source catalog' end,
       case when v.unit_cost > 0 then 'estimated' else 'not_costed' end::app.material_cost_state,
       'catalog', 'active', 'GrounUp material catalog v1'
from (values
  ('MAT-0001', '#304 Aggregate Base', 'Aggregate & Stone', 'EA', 0.0, null, 0.0),
  ('MAT-0002', '#57 Crushed Stone', 'Aggregate & Stone', 'EA', 0.0, null, 0.0),
  ('MAT-0003', '#57 Stone', 'Aggregate & Stone', 'TON', 16.0, null, 0.0),
  ('MAT-0004', '#57 Stone (import)', 'Aggregate & Stone', 'TON', 20.0, 2700, 0.0),
  ('MAT-0005', '304 Limestone Base (import)', 'Aggregate & Stone', 'TON', 0.0, 2700, 0.0),
  ('MAT-0006', '411', 'Aggregate & Stone', 'TON', 20.0, null, 0.0),
  ('MAT-0007', 'Aggregate Base 304', 'Aggregate & Stone', 'TON', 0.0, null, 0.0),
  ('MAT-0008', 'Crusher Run', 'Aggregate & Stone', 'EA', 0.0, null, 0.0),
  ('MAT-0009', 'Gabion Stone', 'Aggregate & Stone', 'EA', 0.0, null, 0.0),
  ('MAT-0010', 'Gravel (general)', 'Aggregate & Stone', 'TON', 0.0, null, 0.0),
  ('MAT-0011', 'Open-Graded Paver Base', 'Aggregate & Stone', 'TON', 0.0, null, 0.0),
  ('MAT-0012', 'Pea Gravel', 'Aggregate & Stone', 'EA', 0.0, null, 0.0),
  ('MAT-0013', 'Recycled Aggregate Base', 'Aggregate & Stone', 'TON', 0.0, null, 0.0),
  ('MAT-0014', 'Riprap Stone', 'Aggregate & Stone', 'EA', 0.0, null, 0.0),
  ('MAT-0015', 'Riprap Stone (erosion control)', 'Aggregate & Stone', 'TON', 0.0, 3000, 0.0),
  ('MAT-0016', 'Sand Bedding', 'Aggregate & Stone', 'EA', 0.0, null, 0.0),
  ('MAT-0017', 'Stone Veneer', 'Aggregate & Stone', 'SF', 0.0, null, 0.0),
  ('MAT-0018', 'Structural Fill (import)', 'Aggregate & Stone', 'TON', 0.0, 3000, 0.0),
  ('MAT-0019', 'Adhesives/Sealants', 'Allowances', 'LF', 0.0, null, 0.0),
  ('MAT-0020', 'Cabinet Allowance (mid-grade)', 'Allowances', 'LF', 0.0, null, 0.0),
  ('MAT-0021', 'Countertop Allowance (quartz/laminate mix)', 'Allowances', 'SF', 0.0, null, 0.0),
  ('MAT-0022', 'Fasteners / Adhesives Allowance', 'Allowances', 'LS', 0.0, null, 0.0),
  ('MAT-0023', 'Asphalt Base Course', 'Asphalt & Paving', 'EA', 0.0, null, 0.0),
  ('MAT-0024', 'Asphalt Surface Course', 'Asphalt & Paving', 'EA', 0.0, null, 0.0),
  ('MAT-0025', 'Cold Patch Asphalt', 'Asphalt & Paving', 'EA', 0.0, null, 0.0),
  ('MAT-0026', 'Prime Coat', 'Asphalt & Paving', 'EA', 0.0, null, 0.0),
  ('MAT-0027', 'Raised Pavement Marker', 'Asphalt & Paving', 'EA', 0.0, null, 0.0),
  ('MAT-0028', 'Sealcoat', 'Asphalt & Paving', 'EA', 0.0, null, 0.0),
  ('MAT-0029', 'Tack Coat', 'Asphalt & Paving', 'EA', 0.0, null, 0.0),
  ('MAT-0030', 'Thermoplastic Marking', 'Asphalt & Paving', 'EA', 0.0, null, 0.0),
  ('MAT-0031', 'Traffic Paint', 'Asphalt & Paving', 'EA', 0.0, null, 0.0),
  ('MAT-0032', 'Base Cabinet', 'Cabinets & Countertops', 'EA', 0.0, null, 0.0),
  ('MAT-0033', 'Granite Countertop', 'Cabinets & Countertops', 'EA', 0.0, null, 0.0),
  ('MAT-0034', 'Laminate Countertop', 'Cabinets & Countertops', 'EA', 0.0, null, 0.0),
  ('MAT-0035', 'Quartz Countertop', 'Cabinets & Countertops', 'EA', 0.0, null, 0.0),
  ('MAT-0036', 'Vanity Cabinet', 'Cabinets & Countertops', 'EA', 0.0, null, 0.0),
  ('MAT-0037', 'Wall Cabinet', 'Cabinets & Countertops', 'EA', 0.0, null, 0.0),
  ('MAT-0038', 'Cat6 Cable', 'Communications', 'EA', 0.0, null, 0.0),
  ('MAT-0039', 'Data Jack', 'Communications', 'EA', 0.0, null, 0.0),
  ('MAT-0040', 'Fiber Cable', 'Communications', 'EA', 0.0, null, 0.0),
  ('MAT-0041', 'Patch Panel', 'Communications', 'EA', 0.0, null, 0.0),
  ('MAT-0042', '3000 PSI Concrete', 'Concrete', 'EA', 0.0, null, 0.0),
  ('MAT-0043', '4000 PSI Concrete', 'Concrete', 'EA', 0.0, null, 0.0),
  ('MAT-0044', '6 inch Concrete Form Tube', 'Concrete', 'EA', 12.5, null, 0.05),
  ('MAT-0045', 'Anchor Bolts / Embeds', 'Concrete', 'EA', 0.0, null, 0.0),
  ('MAT-0046', 'Concrete 3000 PSI', 'Concrete', 'CY', 0.0, null, 0.0),
  ('MAT-0047', 'Concrete 4000 PSI', 'Concrete', 'CY', 0.0, null, 0.0),
  ('MAT-0048', 'Concrete 4500 PSI', 'Concrete', 'CY', 0.0, null, 0.0),
  ('MAT-0049', 'Concrete Curb / Edge Restraint', 'Concrete', 'LF', 0.0, null, 0.0),
  ('MAT-0050', 'Concrete Formwork Allowance', 'Concrete', 'SF', 0.0, null, 0.0),
  ('MAT-0051', 'Curing Compound', 'Concrete', 'EA', 0.0, null, 0.0),
  ('MAT-0052', 'Expansion Joint Filler', 'Concrete', 'EA', 0.0, null, 0.0),
  ('MAT-0053', 'Fiber Reinforced Concrete', 'Concrete', 'EA', 0.0, null, 0.0),
  ('MAT-0054', 'Flowable Fill', 'Concrete', 'EA', 0.0, null, 0.0),
  ('MAT-0055', 'Form Release Agent', 'Concrete', 'EA', 0.0, null, 0.0),
  ('MAT-0056', 'Formwork Allowance', 'Concrete', 'SF', 0.0, null, 0.0),
  ('MAT-0057', 'Grout', 'Concrete', 'EA', 0.0, null, 0.0),
  ('MAT-0058', 'Grout / Drill Seal', 'Concrete', 'GAL', 0.0, null, 0.0),
  ('MAT-0059', 'Rebar (assorted)', 'Concrete', 'LB', 0.0, null, 0.0),
  ('MAT-0060', 'Shotcrete', 'Concrete', 'EA', 0.0, null, 0.0),
  ('MAT-0061', 'Tile Grout (bag)', 'Concrete', 'EA', 0.0, null, 0.0),
  ('MAT-0062', 'Asphalt Millings/Debris (export/recycle)', 'Disposal & Debris', 'TON', 0.0, 2900, 0.0),
  ('MAT-0063', 'C&D Disposal Fee', 'Disposal & Debris', 'TON', 0.0, null, 0.0),
  ('MAT-0064', 'Concrete Debris (export/recycle)', 'Disposal & Debris', 'TON', 0.0, 4050, 0.0),
  ('MAT-0065', 'Disposal/Tipping Fee (C&D)', 'Disposal & Debris', 'TON', 0.0, null, 0.0),
  ('MAT-0066', 'Dredge Spoils Disposal Fee', 'Disposal & Debris', 'TON', 0.0, null, 0.0),
  ('MAT-0067', 'Gabions', 'Disposal & Debris', 'CY', 0.0, null, 0.0),
  ('MAT-0068', 'Gunite Debris (pool demo)', 'Disposal & Debris', 'TON', 0.0, 4050, 0.0),
  ('MAT-0069', 'Hazardous / Regulated Disposal Fee', 'Disposal & Debris', 'TON', 0.0, null, 0.0),
  ('MAT-0070', 'Contaminated Soil Disposal', 'Disposal & Export', 'EA', 0.0, null, 0.0),
  ('MAT-0071', 'Spoil Export / Disposal', 'Disposal & Export', 'EA', 0.0, null, 0.0),
  ('MAT-0072', 'Entry Door Unit', 'Doors & Windows', 'EA', 0.0, null, 0.0),
  ('MAT-0073', 'Exterior Door Allowance', 'Doors & Windows', 'EA', 0.0, null, 0.0),
  ('MAT-0074', 'Hardware Set', 'Doors & Windows', 'EA', 0.0, null, 0.0),
  ('MAT-0075', 'Hollow Metal Door & Frame', 'Doors & Windows', 'EA', 0.0, null, 0.0),
  ('MAT-0076', 'Interior Hollow Core Door', 'Doors & Windows', 'EA', 0.0, null, 0.0),
  ('MAT-0077', 'Sliding Glass Door Unit', 'Doors & Windows', 'EA', 0.0, null, 0.0),
  ('MAT-0078', 'Storefront/Glazing', 'Doors & Windows', 'SF', 0.0, null, 0.0),
  ('MAT-0079', 'Vinyl Window Unit', 'Doors & Windows', 'EA', 0.0, null, 0.0),
  ('MAT-0080', 'Window Allowance', 'Doors & Windows', 'EA', 0.0, null, 0.0),
  ('MAT-0081', 'Window Blind', 'Doors & Windows', 'EA', 0.0, null, 0.0),
  ('MAT-0082', 'Wood Window Unit', 'Doors & Windows', 'EA', 0.0, null, 0.0),
  ('MAT-0083', 'Drywall 1/2 in (4x8)', 'Drywall & Interior', 'EA', 0.0, null, 0.0),
  ('MAT-0084', 'Drywall 5/8 in (4x8)', 'Drywall & Interior', 'EA', 0.0, null, 0.0),
  ('MAT-0085', 'Drywall Tape (roll)', 'Drywall & Interior', 'EA', 0.0, null, 0.0),
  ('MAT-0086', 'Dust Barrier / Poly / Tape', 'Drywall & Interior', 'LS', 0.0, null, 0.0),
  ('MAT-0087', 'Gypsum Board', 'Drywall & Interior', 'SF', 0.0, null, 0.0),
  ('MAT-0088', 'Joint Compound (bucket)', 'Drywall & Interior', 'EA', 0.0, null, 0.0),
  ('MAT-0089', '1/2 in Drywall Board', 'Drywall & Plaster', 'EA', 0.0, null, 0.0),
  ('MAT-0090', '5/8 in Type X Drywall', 'Drywall & Plaster', 'EA', 0.0, null, 0.0),
  ('MAT-0091', 'Corner Bead', 'Drywall & Plaster', 'EA', 0.0, null, 0.0),
  ('MAT-0092', 'Joint Compound', 'Drywall & Plaster', 'EA', 0.0, null, 0.0),
  ('MAT-0093', 'Moisture Resistant Drywall', 'Drywall & Plaster', 'EA', 0.0, null, 0.0),
  ('MAT-0094', 'Plaster Base Coat', 'Drywall & Plaster', 'EA', 0.0, null, 0.0),
  ('MAT-0095', 'Access Control Reader', 'Electrical', 'EA', 0.0, null, 0.0),
  ('MAT-0096', 'Alarm Device', 'Electrical', 'EA', 0.0, null, 0.0),
  ('MAT-0097', 'Breaker', 'Electrical', 'EA', 0.0, null, 0.0),
  ('MAT-0098', 'CCTV Camera', 'Electrical', 'EA', 0.0, null, 0.0),
  ('MAT-0099', 'Conduit', 'Electrical', 'LF', 0.0, null, 0.0),
  ('MAT-0100', 'Device Box', 'Electrical', 'EA', 0.0, null, 0.0),
  ('MAT-0101', 'Duplex Receptacle', 'Electrical', 'EA', 0.0, null, 0.0),
  ('MAT-0102', 'Electrical Device (switch/outlet)', 'Electrical', 'EA', 0.0, null, 0.0),
  ('MAT-0103', 'Electrical Devices/Lighting Allowance', 'Electrical', 'EA', 0.0, null, 0.0),
  ('MAT-0104', 'Electrical Wire 12/2 (NM-B)', 'Electrical', 'LF', 0.0, null, 0.0),
  ('MAT-0105', 'Electrical Wire 14/2 (NM-B)', 'Electrical', 'LF', 0.0, null, 0.0),
  ('MAT-0106', 'EMT Conduit', 'Electrical', 'EA', 0.0, null, 0.0),
  ('MAT-0107', 'GFCI Receptacle', 'Electrical', 'EA', 0.0, null, 0.0),
  ('MAT-0108', 'LED Lighting Allowance', 'Electrical', 'EA', 0.0, null, 0.0),
  ('MAT-0109', 'LED Recessed Fixture', 'Electrical', 'EA', 0.0, null, 0.0),
  ('MAT-0110', 'Light Fixture Allowance', 'Electrical', 'EA', 0.0, null, 0.0),
  ('MAT-0111', 'Light Switch', 'Electrical', 'EA', 0.0, null, 0.0),
  ('MAT-0112', 'Mag Lock', 'Electrical', 'EA', 0.0, null, 0.0),
  ('MAT-0113', 'MC Cable', 'Electrical', 'EA', 0.0, null, 0.0),
  ('MAT-0114', 'Panelboard', 'Electrical', 'EA', 0.0, null, 0.0),
  ('MAT-0115', 'PVC Conduit', 'Electrical', 'EA', 0.0, null, 0.0),
  ('MAT-0116', 'Temp Traffic Devices Allowance', 'Electrical', 'DAY', 0.0, null, 0.0),
  ('MAT-0117', 'THHN Wire', 'Electrical', 'EA', 0.0, null, 0.0),
  ('MAT-0118', 'Wire/Cable', 'Electrical', 'LF', 0.0, null, 0.0),
  ('MAT-0119', 'Filter Sock', 'Erosion Control', 'EA', 0.0, null, 0.0),
  ('MAT-0120', 'Inlet Protection', 'Erosion Control', 'EA', 0.0, null, 0.0),
  ('MAT-0121', 'Broadloom Carpet', 'Flooring', 'EA', 0.0, null, 0.0),
  ('MAT-0122', 'Carpet Tile', 'Flooring', 'EA', 0.0, null, 0.0),
  ('MAT-0123', 'Ceramic/Porcelain Tile (floor)', 'Flooring', 'SF', 0.0, null, 0.0),
  ('MAT-0124', 'Ceramic/Porcelain Tile (wall)', 'Flooring', 'SF', 0.0, null, 0.0),
  ('MAT-0125', 'Engineered Wood Flooring', 'Flooring', 'EA', 0.0, null, 0.0),
  ('MAT-0126', 'Epoxy Flooring', 'Flooring', 'SF', 0.0, null, 0.0),
  ('MAT-0127', 'Floor Protection / Ram Board', 'Flooring', 'SF', 0.0, null, 0.0),
  ('MAT-0128', 'Flooring Adhesive', 'Flooring', 'EA', 0.0, null, 0.0),
  ('MAT-0129', 'Geotextile Fabric (non-woven)', 'Flooring', 'SY', 0.0, null, 0.0),
  ('MAT-0130', 'Hardwood Flooring', 'Flooring', 'EA', 0.0, null, 0.0),
  ('MAT-0131', 'Laminate Flooring', 'Flooring', 'EA', 0.0, null, 0.0),
  ('MAT-0132', 'Luxury Vinyl Plank', 'Flooring', 'EA', 0.0, null, 0.0),
  ('MAT-0133', 'Luxury Vinyl Plank Flooring', 'Flooring', 'SF', 0.0, null, 0.0),
  ('MAT-0134', 'LVP Underlayment', 'Flooring', 'SF', 0.0, null, 0.0),
  ('MAT-0135', 'LVT Flooring', 'Flooring', 'SF', 0.0, null, 0.0),
  ('MAT-0136', 'Rubber Base', 'Flooring', 'EA', 0.0, null, 0.0),
  ('MAT-0137', 'Sheet Vinyl', 'Flooring', 'EA', 0.0, null, 0.0),
  ('MAT-0138', 'Siding (vinyl/fiber cement allowance)', 'Flooring', 'SF', 0.0, null, 0.0),
  ('MAT-0139', 'Tile', 'Flooring', 'SF', 0.0, null, 0.0),
  ('MAT-0140', 'Common Fill', 'Geotechnical', 'EA', 0.0, null, 0.0),
  ('MAT-0141', 'Geogrid', 'Geotechnical', 'EA', 0.0, null, 0.0),
  ('MAT-0142', 'Geotextile Fabric', 'Geotechnical', 'EA', 0.0, null, 0.0),
  ('MAT-0143', 'Lime Stabilization Material', 'Geotechnical', 'EA', 0.0, null, 0.0),
  ('MAT-0144', 'Soil Stabilization Cement', 'Geotechnical', 'EA', 0.0, null, 0.0),
  ('MAT-0145', 'Structural Fill', 'Geotechnical', 'EA', 0.0, null, 0.0),
  ('MAT-0146', 'EV Charger (Level 2) allowance', 'Green / Sustainable', 'EA', 0.0, null, 0.0),
  ('MAT-0147', 'Solar PV System (per kW allowance)', 'Green / Sustainable', 'KW', 0.0, null, 0.0),
  ('MAT-0148', 'Air Handler', 'HVAC', 'EA', 0.0, null, 0.0),
  ('MAT-0149', 'Air Handling Unit (allowance)', 'HVAC', 'EA', 0.0, null, 0.0),
  ('MAT-0150', 'Chiller (allowance)', 'HVAC', 'EA', 0.0, null, 0.0),
  ('MAT-0151', 'Condensate Drain', 'HVAC', 'EA', 0.0, null, 0.0),
  ('MAT-0152', 'Condensing Unit', 'HVAC', 'EA', 0.0, null, 0.0),
  ('MAT-0153', 'Diffuser / Register / Grille', 'HVAC', 'EA', 0.0, null, 0.0),
  ('MAT-0154', 'Ductwork (industrial)', 'HVAC', 'LF', 0.0, null, 0.0),
  ('MAT-0155', 'Flexible Duct', 'HVAC', 'EA', 0.0, null, 0.0),
  ('MAT-0156', 'Furnace', 'HVAC', 'EA', 0.0, null, 0.0),
  ('MAT-0157', 'HVAC Duct Allowance', 'HVAC', 'LF', 0.0, null, 0.0),
  ('MAT-0158', 'HVAC Equipment Allowance', 'HVAC', 'EA', 0.0, null, 0.0),
  ('MAT-0159', 'Mini Split System', 'HVAC', 'EA', 0.0, null, 0.0),
  ('MAT-0160', 'Programmable Thermostat', 'HVAC', 'EA', 0.0, null, 0.0),
  ('MAT-0161', 'Refrigerant Line Set', 'HVAC', 'EA', 0.0, null, 0.0),
  ('MAT-0162', 'Sheet Metal Duct', 'HVAC', 'EA', 0.0, null, 0.0),
  ('MAT-0163', 'VAV / Terminal Units', 'HVAC', 'EA', 0.0, null, 0.0),
  ('MAT-0164', 'Controls Wiring/Parts Allowance', 'Industrial / Process', 'EA', 0.0, null, 0.0),
  ('MAT-0165', 'Generator (allowance)', 'Industrial / Process', 'EA', 0.0, null, 0.0),
  ('MAT-0166', 'Instrumentation / Sensors', 'Industrial / Process', 'EA', 0.0, null, 0.0),
  ('MAT-0167', 'Pumps (allowance)', 'Industrial / Process', 'EA', 0.0, null, 0.0),
  ('MAT-0168', 'Switchgear/Panelboards', 'Industrial / Process', 'EA', 0.0, null, 0.0),
  ('MAT-0169', 'Valves / Fittings Allowance', 'Industrial / Process', 'EA', 0.0, null, 0.0),
  ('MAT-0170', 'Blown Cellulose Insulation', 'Insulation', 'EA', 0.0, null, 0.0),
  ('MAT-0171', 'Closed Cell Spray Foam', 'Insulation', 'EA', 0.0, null, 0.0),
  ('MAT-0172', 'Fiberglass Batt Insulation R13', 'Insulation', 'EA', 0.0, null, 0.0),
  ('MAT-0173', 'Fiberglass Batt Insulation R19', 'Insulation', 'EA', 0.0, null, 0.0),
  ('MAT-0174', 'Mineral Wool Insulation', 'Insulation', 'EA', 0.0, null, 0.0),
  ('MAT-0175', 'Rigid Foam Board', 'Insulation', 'EA', 0.0, null, 0.0),
  ('MAT-0176', '6 mil Vapor Barrier', 'Insulation & Moisture', 'SF', 0.0, null, 0.0),
  ('MAT-0177', 'Fiberglass Batt Insulation R-13', 'Insulation & Moisture', 'SF', 0.0, null, 0.0),
  ('MAT-0178', 'Fiberglass Batt Insulation R-19', 'Insulation & Moisture', 'SF', 0.0, null, 0.0),
  ('MAT-0179', 'Housewrap', 'Insulation & Moisture', 'SF', 0.0, null, 0.0),
  ('MAT-0180', 'Insulation (batts/board)', 'Insulation & Moisture', 'SF', 0.0, null, 0.0),
  ('MAT-0181', 'Decorative Stone', 'Landscaping', 'EA', 0.0, null, 0.0),
  ('MAT-0182', 'Dewatering Filter Bag', 'Landscaping', 'EA', 0.0, null, 0.0),
  ('MAT-0183', 'Grass Seed', 'Landscaping', 'EA', 0.0, null, 0.0),
  ('MAT-0184', 'Grass Seed (bagged)', 'Landscaping', 'LB', 0.0, null, 0.0),
  ('MAT-0185', 'Hydromulch', 'Landscaping', 'EA', 0.0, null, 0.0),
  ('MAT-0186', 'Irrigation Parts Allowance', 'Landscaping', 'SF', 0.0, null, 0.0),
  ('MAT-0187', 'Mulch', 'Landscaping', 'EA', 0.0, null, 0.0),
  ('MAT-0188', 'Mulch (shredded hardwood)', 'Landscaping', 'CY', 0.0, 800, 0.0),
  ('MAT-0189', 'Native Seed Mix', 'Landscaping', 'LB', 0.0, null, 0.0),
  ('MAT-0190', 'Rain Garden Planting Allowance', 'Landscaping', 'SF', 0.0, null, 0.0),
  ('MAT-0191', 'Screened Topsoil', 'Landscaping', 'EA', 0.0, null, 0.0),
  ('MAT-0192', 'Shrub', 'Landscaping', 'EA', 0.0, null, 0.0),
  ('MAT-0193', 'Sod', 'Landscaping', 'EA', 0.0, null, 0.0),
  ('MAT-0194', 'Sod (Kentucky Bluegrass mix)', 'Landscaping', 'SY', 0.0, null, 0.0),
  ('MAT-0195', 'Stormwater Structure (CB/inlet/manhole)', 'Landscaping', 'EA', 0.0, null, 0.0),
  ('MAT-0196', 'Tree', 'Landscaping', 'EA', 0.0, null, 0.0),
  ('MAT-0197', 'Water (dust control / planting)', 'Landscaping', 'GAL', 0.0, null, 0.0),
  ('MAT-0198', '2x10 SPF Joist', 'Lumber & Framing', 'EA', 0.0, null, 0.0),
  ('MAT-0199', '2x4 SPF Stud', 'Lumber & Framing', 'EA', 0.0, null, 0.0),
  ('MAT-0200', '2x4 SPF Stud (8 ft)', 'Lumber & Framing', 'EA', 0.0, null, 0.0),
  ('MAT-0201', '2x6 SPF Stud', 'Lumber & Framing', 'EA', 0.0, null, 0.0),
  ('MAT-0202', '2x6 SPF Stud (8 ft)', 'Lumber & Framing', 'EA', 0.0, null, 0.0),
  ('MAT-0203', 'Engineered I-Joist', 'Lumber & Framing', 'EA', 0.0, null, 0.0),
  ('MAT-0204', 'Framing Lumber', 'Lumber & Framing', 'BF', 0.0, null, 0.0),
  ('MAT-0205', 'Framing Nails', 'Lumber & Framing', 'EA', 0.0, null, 0.0),
  ('MAT-0206', 'LVL Beam', 'Lumber & Framing', 'EA', 0.0, null, 0.0),
  ('MAT-0207', 'LVL Beam (allowance)', 'Lumber & Framing', 'LF', 0.0, null, 0.0),
  ('MAT-0208', 'OSB 7/16 in (4x8)', 'Lumber & Framing', 'EA', 0.0, null, 0.0),
  ('MAT-0209', 'Plywood 3/4 in (4x8)', 'Lumber & Framing', 'EA', 0.0, null, 0.0),
  ('MAT-0210', 'PSL Beam', 'Lumber & Framing', 'EA', 0.0, null, 0.0),
  ('MAT-0211', 'PT Lumber', 'Lumber & Framing', 'BF', 0.0, null, 0.0),
  ('MAT-0212', 'Sheathing (ply/OSB)', 'Lumber & Framing', 'SF', 0.0, null, 0.0),
  ('MAT-0213', 'Clay Brick', 'Masonry', 'EA', 0.0, null, 0.0),
  ('MAT-0214', 'CMU Block', 'Masonry', 'SF', 0.0, null, 0.0),
  ('MAT-0215', 'CMU Block 8in', 'Masonry', 'EA', 0.0, null, 0.0),
  ('MAT-0216', 'Masonry Flashing', 'Masonry', 'LF', 0.0, null, 0.0),
  ('MAT-0217', 'Masonry Mortar', 'Masonry', 'EA', 0.0, null, 0.0),
  ('MAT-0218', 'Thinset Mortar (bag)', 'Masonry', 'EA', 0.0, null, 0.0),
  ('MAT-0219', 'Weep Vents', 'Masonry', 'EA', 0.0, null, 0.0),
  ('MAT-0220', 'Pressure Washing Detergent/Cleaner', 'Misc', 'GAL', 0.0, null, 0.0),
  ('MAT-0221', 'Fiberglass Batt R-13', 'Other', 'SF', 0.0, null, 0.0),
  ('MAT-0222', 'Fiberglass Batt R-19', 'Other', 'SF', 0.0, null, 0.0),
  ('MAT-0223', 'Perforated Drain Pipe', 'Other', 'LF', 0.0, null, 0.0),
  ('MAT-0224', 'T-Grid ACT Ceiling', 'Other', 'SF', 0.0, null, 0.0),
  ('MAT-0225', 'Temp Safety Fence', 'Other', 'LF', 0.0, null, 0.0),
  ('MAT-0226', 'Clear Sealer', 'Paint & Coating', 'EA', 0.0, null, 0.0),
  ('MAT-0227', 'Epoxy Floor Coating', 'Paint & Coating', 'EA', 0.0, null, 0.0),
  ('MAT-0228', 'Exterior Acrylic Paint', 'Paint & Coating', 'EA', 0.0, null, 0.0),
  ('MAT-0229', 'Interior Latex Paint', 'Paint & Coating', 'EA', 0.0, null, 0.0),
  ('MAT-0230', 'Primer', 'Paint & Coating', 'EA', 0.0, null, 0.0),
  ('MAT-0231', 'Stain', 'Paint & Coating', 'EA', 0.0, null, 0.0),
  ('MAT-0232', 'Interior Paint', 'Paint & Finishes', 'GAL', 0.0, null, 0.0),
  ('MAT-0233', 'Interior Primer', 'Paint & Finishes', 'GAL', 0.0, null, 0.0),
  ('MAT-0234', 'Low-VOC Paint', 'Paint & Finishes', 'SF', 0.0, null, 0.0),
  ('MAT-0235', 'Painter''s Caulk', 'Paint & Finishes', 'EA', 0.0, null, 0.0),
  ('MAT-0236', 'Hot Mix Asphalt', 'Paving', 'TON', 0.0, null, 0.0),
  ('MAT-0237', 'Hot Mix Asphalt Surface', 'Paving', 'TON', 0.0, null, 0.0),
  ('MAT-0238', 'Permeable Pavers', 'Paving', 'SF', 0.0, null, 0.0),
  ('MAT-0239', 'Cable Tray', 'Pipe & Utilities', 'LF', 0.0, null, 0.0),
  ('MAT-0240', 'Carbon Steel Pipe (process)', 'Pipe & Utilities', 'LF', 0.0, null, 0.0),
  ('MAT-0241', 'HDPE Pipe', 'Pipe & Utilities', 'LF', 0.0, null, 0.0),
  ('MAT-0242', 'Manhole (allowance)', 'Pipe & Utilities', 'EA', 0.0, null, 0.0),
  ('MAT-0243', 'Manhole/Structure (allowance)', 'Pipe & Utilities', 'EA', 0.0, null, 0.0),
  ('MAT-0244', 'RCP Pipe', 'Pipe & Utilities', 'LF', 0.0, null, 0.0),
  ('MAT-0245', 'Stainless Steel Pipe (process)', 'Pipe & Utilities', 'LF', 0.0, null, 0.0),
  ('MAT-0246', 'Cast Iron Soil Pipe', 'Plumbing', 'EA', 0.0, null, 0.0),
  ('MAT-0247', 'Copper Pipe', 'Plumbing', 'EA', 0.0, null, 0.0),
  ('MAT-0248', 'Lavatory Faucet', 'Plumbing', 'EA', 0.0, null, 0.0),
  ('MAT-0249', 'PEX Tubing', 'Plumbing', 'EA', 0.0, null, 0.0),
  ('MAT-0250', 'Plumbing Fittings Pack', 'Plumbing', 'EA', 0.0, null, 0.0),
  ('MAT-0251', 'Plumbing Fixture Allowance', 'Plumbing', 'EA', 0.0, null, 0.0),
  ('MAT-0252', 'Plumbing Fixtures Allowance', 'Plumbing', 'EA', 0.0, null, 0.0),
  ('MAT-0253', 'PVC Drain Pipe', 'Plumbing', 'EA', 0.0, null, 0.0),
  ('MAT-0254', 'PVC Pipe', 'Plumbing', 'LF', 0.0, null, 0.0),
  ('MAT-0255', 'PVC Pipe (schedule 40) - small dia', 'Plumbing', 'LF', 0.0, null, 0.0),
  ('MAT-0256', 'Shutoff Valve', 'Plumbing', 'EA', 0.0, null, 0.0),
  ('MAT-0257', 'Tankless Water Heater', 'Plumbing', 'EA', 0.0, null, 0.0),
  ('MAT-0258', 'Toilet Fixture', 'Plumbing', 'EA', 0.0, null, 0.0),
  ('MAT-0259', 'Water Heater', 'Plumbing', 'EA', 0.0, null, 0.0),
  ('MAT-0260', 'Architectural Shingles', 'Roofing', 'SQ', 0.0, null, 0.0),
  ('MAT-0261', 'Asphalt Shingles', 'Roofing', 'EA', 0.0, null, 0.0),
  ('MAT-0262', 'Downspout', 'Roofing', 'EA', 0.0, null, 0.0),
  ('MAT-0263', 'EPDM Membrane 60mil', 'Roofing', 'EA', 0.0, null, 0.0),
  ('MAT-0264', 'Green Roof System (tray/media/plants)', 'Roofing', 'SF', 0.0, null, 0.0),
  ('MAT-0265', 'Gutter Coil', 'Roofing', 'EA', 0.0, null, 0.0),
  ('MAT-0266', 'Ice & Water Shield', 'Roofing', 'EA', 0.0, null, 0.0),
  ('MAT-0267', 'Metal Flashing', 'Roofing', 'EA', 0.0, null, 0.0),
  ('MAT-0268', 'Modified Bitumen Cap Sheet', 'Roofing', 'EA', 0.0, null, 0.0),
  ('MAT-0269', 'Roof Flashing', 'Roofing', 'LF', 0.0, null, 0.0),
  ('MAT-0270', 'Roof ISO Board', 'Roofing', 'SF', 0.0, null, 0.0),
  ('MAT-0271', 'Roof Membrane', 'Roofing', 'SF', 0.0, null, 0.0),
  ('MAT-0272', 'Roof Trusses (allowance)', 'Roofing', 'SF', 0.0, null, 0.0),
  ('MAT-0273', 'Roof Underlayment', 'Roofing', 'EA', 0.0, null, 0.0),
  ('MAT-0274', 'Standing Seam Panels', 'Roofing', 'EA', 0.0, null, 0.0),
  ('MAT-0275', 'TPO Membrane 60mil', 'Roofing', 'EA', 0.0, null, 0.0),
  ('MAT-0276', 'Fire Protection (sprinkler) allowance', 'Safety & Protection', 'SF', 0.0, null, 0.0),
  ('MAT-0277', 'Spill Kit', 'Safety & Protection', 'EA', 0.0, null, 0.0),
  ('MAT-0278', 'Termite Treatment Allowance', 'Safety & Protection', 'SF', 0.0, null, 0.0),
  ('MAT-0279', 'Poly Tarp', 'Safety & Temporary', 'EA', 0.0, null, 0.0),
  ('MAT-0280', 'Safety Fence', 'Safety & Temporary', 'EA', 0.0, null, 0.0),
  ('MAT-0281', 'Steel Plate for Temporary Cover', 'Safety & Temporary', 'EA', 0.0, null, 0.0),
  ('MAT-0282', 'Temporary Lumber Blocking', 'Safety & Temporary', 'EA', 0.0, null, 0.0),
  ('MAT-0283', 'OSB Sheathing 7/16', 'Sheathing & Decking', 'EA', 0.0, null, 0.0),
  ('MAT-0284', 'Plywood Sheathing 1/2', 'Sheathing & Decking', 'EA', 0.0, null, 0.0),
  ('MAT-0285', 'Subfloor T&G 3/4', 'Sheathing & Decking', 'EA', 0.0, null, 0.0),
  ('MAT-0286', 'Erosion Control Blanket', 'Site Work & Erosion', 'SY', 0.0, null, 0.0),
  ('MAT-0287', 'Hydromulch / Tackifier', 'Site Work & Erosion', 'ACRE', 0.0, null, 0.0),
  ('MAT-0288', 'Silt Fence', 'Site Work & Erosion', 'LF', 0.0, null, 0.0),
  ('MAT-0289', 'Straw Mulch (bales)', 'Site Work & Erosion', 'EA', 0.0, null, 0.0),
  ('MAT-0290', 'Bioretention Soil Media', 'Soil & Fill', 'CY', 100.0, null, 0.0),
  ('MAT-0291', 'Common Excavated Soil (export/dispose)', 'Soil & Fill', 'TON', 0.0, 2700, 0.0),
  ('MAT-0292', 'Compost Amendment (import)', 'Soil & Fill', 'CY', 0.0, 1200, 0.0),
  ('MAT-0293', 'Concrete Sand / Bedding Sand (import)', 'Soil & Fill', 'TON', 0.0, 2600, 0.0),
  ('MAT-0294', 'Contaminated Soil Disposal Fee', 'Soil & Fill', 'TON', 0.0, null, 0.0),
  ('MAT-0295', 'Screened Topsoil (import)', 'Soil & Fill', 'CY', 0.0, 2000, 0.0),
  ('MAT-0296', 'Wet/Unsuitable Soil (export/dispose)', 'Soil & Fill', 'TON', 0.0, 3200, 0.0),
  ('MAT-0297', 'ADA Sign', 'Specialties', 'EA', 0.0, null, 0.0),
  ('MAT-0298', 'Firestopping', 'Specialties', 'LF', 0.0, null, 0.0),
  ('MAT-0299', 'FRP Panels', 'Specialties', 'SF', 0.0, null, 0.0),
  ('MAT-0300', 'Toilet Partition Set', 'Specialties', 'EA', 0.0, null, 0.0),
  ('MAT-0301', 'Wall Guard', 'Specialties', 'LF', 0.0, null, 0.0),
  ('MAT-0302', 'Containment Liner', 'Specialty', 'EA', 0.0, null, 0.0),
  ('MAT-0303', 'Generator Set', 'Specialty', 'EA', 0.0, null, 0.0),
  ('MAT-0304', 'Prefab Metal Building Package', 'Specialty', 'EA', 0.0, null, 0.0),
  ('MAT-0305', 'Metal Deck', 'Steel & Structural', 'SF', 0.0, null, 0.0),
  ('MAT-0306', 'Steel Piles (allowance)', 'Steel & Structural', 'LF', 0.0, null, 0.0),
  ('MAT-0307', 'Structural Steel', 'Steel & Structural', 'TON', 0.0, null, 0.0),
  ('MAT-0308', 'Guardrail Beam', 'Structural Steel', 'EA', 0.0, null, 0.0),
  ('MAT-0309', 'HSS Steel Tube', 'Structural Steel', 'EA', 0.0, null, 0.0),
  ('MAT-0310', 'Miscellaneous Steel', 'Structural Steel', 'EA', 0.0, null, 0.0),
  ('MAT-0311', 'Rebar #4', 'Structural Steel', 'EA', 0.0, null, 0.0),
  ('MAT-0312', 'Rebar #5', 'Structural Steel', 'EA', 0.0, null, 0.0),
  ('MAT-0313', 'Sign Post', 'Structural Steel', 'EA', 0.0, null, 0.0),
  ('MAT-0314', 'Steel Deck', 'Structural Steel', 'EA', 0.0, null, 0.0),
  ('MAT-0315', 'Steel Plate', 'Structural Steel', 'EA', 0.0, null, 0.0),
  ('MAT-0316', 'Wide Flange Steel Beam', 'Structural Steel', 'EA', 0.0, null, 0.0),
  ('MAT-0317', 'WWM 6x6 W2.9', 'Structural Steel', 'EA', 0.0, null, 0.0),
  ('MAT-0318', 'Mortar Mix', 'Tile & Masonry', 'EA', 0.0, null, 0.0),
  ('MAT-0319', 'Brick', 'Tile & Masonry', 'EA', 0.0, null, 0.0),
  ('MAT-0320', 'Ceramic Tile', 'Tile & Masonry', 'EA', 0.0, null, 0.0),
  ('MAT-0321', 'Grout Sealer', 'Tile & Masonry', 'EA', 0.0, null, 0.0),
  ('MAT-0322', 'Porcelain Tile', 'Tile & Masonry', 'EA', 0.0, null, 0.0),
  ('MAT-0323', 'Stone Tile', 'Tile & Masonry', 'EA', 0.0, null, 0.0),
  ('MAT-0324', 'Thinset Mortar', 'Tile & Masonry', 'EA', 0.0, null, 0.0),
  ('MAT-0325', 'Tile Grout', 'Tile & Masonry', 'EA', 0.0, null, 0.0),
  ('MAT-0326', 'Baseboard Trim (primed)', 'Trim & Millwork', 'LF', 0.0, null, 0.0),
  ('MAT-0327', 'Casework', 'Trim & Millwork', 'LF', 0.0, null, 0.0),
  ('MAT-0328', 'Closet Shelf Board', 'Trim & Millwork', 'EA', 0.0, null, 0.0),
  ('MAT-0329', 'Crown Molding', 'Trim & Millwork', 'EA', 0.0, null, 0.0),
  ('MAT-0330', 'Door/Window Casing (primed)', 'Trim & Millwork', 'LF', 0.0, null, 0.0),
  ('MAT-0331', 'MDF Baseboard', 'Trim & Millwork', 'EA', 0.0, null, 0.0),
  ('MAT-0332', 'Pine Casing', 'Trim & Millwork', 'EA', 0.0, null, 0.0),
  ('MAT-0333', 'Window Stool', 'Trim & Millwork', 'EA', 0.0, null, 0.0)
) as v(code, name, category, unit, unit_cost, density, waste)
on conflict do nothing;
