/**
 * Every door in the schema is opened by something.
 *
 * The most expensive defect this build produces is not a wrong answer. It is a
 * complete, tested, governed feature that no screen reaches, and it has
 * happened at least eleven times: lead intake, assemblies, unit cost, resource
 * suggestions, the equipment-rate importer, `document_sheets`, the parametric
 * rate, the line-price write-back, Plans & Specs, `line_unit_note`, and the
 * services with no breakdown.
 *
 * Not one was caught by a test, and each time every layer was green: the
 * migration was tested, the function was tested, the payload was tested, the
 * component was tested. **Nothing tested the joint.** Four thousand green tests
 * shipped a billing page showing every customer somebody else's numbers.
 *
 * So the joint is tested here. A `public.*` function or a `my_*` view exists to
 * be opened from a browser — it was granted to `authenticated` on purpose — and
 * one with no caller anywhere in `apps/web/src` or `supabase/functions` is
 * either an unfinished feature or an exception that has to say, in writing, why
 * a browser does not open it.
 *
 * The inventory itself lives in `governance/DOORS.md` and is generated by
 * `scripts/build-door-inventory.mjs`. This test runs the same script in
 * `--check` mode, so a door arrives with a reader or with a stated reason on
 * the commit that adds it, rather than on the day somebody goes looking.
 */
import { describe, expect, it } from 'vitest';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../..');

describe('the doors in the schema', () => {
  it('all have a reader, or a written reason they do not', () => {
    /*
     * `--check` prints the offenders and exits non-zero. Running it here rather
     * than reimplementing the scan means the gate and this suite can never
     * disagree about what a door is.
     */
    let output = '';
    let failed = false;
    try {
      output = execFileSync('node', ['scripts/build-door-inventory.mjs', '--check'],
        { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
    } catch (err) {
      failed = true;
      const e = err as { stdout?: string; stderr?: string };
      output = `${e.stdout ?? ''}${e.stderr ?? ''}`;
    }
    expect(failed, output).toBe(false);
    expect(output).toMatch(/0 with no reader/);
  });

  it('is written down, so the count can be read without running anything', () => {
    const doors = readFileSync(join(ROOT, 'governance/DOORS.md'), 'utf8');
    expect(doors).toContain('# Doors');
    expect(doors).toContain('Every door in the schema is opened by something.');
  });

  it('records a reason for each door a browser is not meant to open', () => {
    /*
     * An entry in `SERVER_SIDE` with no reason would be a defect being written
     * down rather than fixed, so the table must carry a sentence beside every
     * name.
     */
    const doors = readFileSync(join(ROOT, 'governance/DOORS.md'), 'utf8');
    const section = doors.split('## Server-side by design')[1]?.split('\n## ')[0] ?? '';
    const rows = section.split('\n').filter((l) => l.startsWith('| `'));
    expect(rows.length).toBeGreaterThan(0);
    for (const row of rows) {
      const [, name, reason] = row.split('|').map((c) => c.trim());
      expect(name, row).toBeTruthy();
      expect(reason?.length ?? 0, `${name} has no reason beside it`).toBeGreaterThan(20);
    }
  });
});
