-- =============================================================================
-- GrounUp Enterprise — 0010 Row Level Security
--
-- Every table in `public` is force-enabled for RLS. Policies are generated by
-- two audited helpers rather than hand-written sixty times, because a
-- hand-written policy set is exactly where a single omitted table becomes a
-- cross-tenant data leak.
--
-- 0011 asserts that no table in `public` was left without RLS, so adding a table
-- without a policy fails the build rather than shipping open.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Policy generators
-- -----------------------------------------------------------------------------

/**
 * Standard policy set for a table whose company_id is NOT NULL.
 *
 * SELECT   : the row's company is one the user is an active member of.
 * INSERT   : same, plus the write permission, and the new row's company must be
 *            one the user belongs to — a member of two companies cannot insert
 *            into the one they are not writing as.
 * UPDATE   : USING and WITH CHECK both applied, so a row cannot be moved
 *            between tenants by updating company_id.
 * DELETE   : membership plus the delete permission.
 */
create or replace function app.apply_tenant_rls(
  p_table text,
  p_read_permission text default null,
  p_write_permission text default null,
  p_delete_permission text default null
)
returns void
language plpgsql
as $$
declare
  v_read  text := case when p_read_permission is null
                       then format('app.is_member(%I.company_id)', p_table)
                       else format('(app.is_member(%I.company_id) and app.has_permission(%I.company_id, %L))',
                                   p_table, p_table, p_read_permission) end;
  v_write text := case when p_write_permission is null
                       then format('app.is_member(company_id)')
                       else format('(app.is_member(company_id) and app.has_permission(company_id, %L))', p_write_permission) end;
  v_del   text := case when coalesce(p_delete_permission, p_write_permission) is null
                       then format('app.is_member(%I.company_id)', p_table)
                       else format('(app.is_member(%I.company_id) and app.has_permission(%I.company_id, %L))',
                                   p_table, p_table, coalesce(p_delete_permission, p_write_permission)) end;
begin
  execute format('alter table %I enable row level security', p_table);
  execute format('alter table %I force row level security', p_table);

  execute format('drop policy if exists %I on %I', p_table || '_select', p_table);
  execute format('create policy %I on %I for select to authenticated using (%s)',
                 p_table || '_select', p_table, v_read);

  execute format('drop policy if exists %I on %I', p_table || '_insert', p_table);
  execute format('create policy %I on %I for insert to authenticated with check (%s)',
                 p_table || '_insert', p_table, v_write);

  execute format('drop policy if exists %I on %I', p_table || '_update', p_table);
  execute format('create policy %I on %I for update to authenticated using (%s) with check (%s)',
                 p_table || '_update', p_table,
                 replace(v_write, 'app.is_member(company_id)', format('app.is_member(%I.company_id)', p_table)),
                 v_write);

  execute format('drop policy if exists %I on %I', p_table || '_delete', p_table);
  execute format('create policy %I on %I for delete to authenticated using (%s)',
                 p_table || '_delete', p_table, v_del);
end;
$$;

/**
 * Policy set for a three-tier library table (global / enterprise group / company).
 *
 * SELECT lets a member read the GrounUp global seed, their group's corporate
 * standard, and their own company's overrides. Writes are confined to their own
 * company: no tenant can edit the global seed or another group's standard, which
 * is what keeps a shared library trustworthy.
 */
create or replace function app.apply_library_rls(
  p_table text,
  p_write_permission text default 'libraries.write'
)
returns void
language plpgsql
as $$
declare
  v_read text := format($f$(
      (%1$I.company_id is null and %1$I.enterprise_group_id is null)
      or app.is_member(%1$I.company_id)
      or %1$I.enterprise_group_id in (
        select c.enterprise_group_id from companies c
        where c.id in (select app.current_company_ids()) and c.enterprise_group_id is not null
      )
    )$f$, p_table);
  v_write text := format(
    '(company_id is not null and app.is_member(company_id) and app.has_permission(company_id, %L))',
    p_write_permission);
  v_write_using text := format(
    '(%1$I.company_id is not null and app.is_member(%1$I.company_id) and app.has_permission(%1$I.company_id, %2$L))',
    p_table, p_write_permission);
begin
  execute format('alter table %I enable row level security', p_table);
  execute format('alter table %I force row level security', p_table);

  execute format('drop policy if exists %I on %I', p_table || '_select', p_table);
  execute format('create policy %I on %I for select to authenticated using (%s)',
                 p_table || '_select', p_table, v_read);

  execute format('drop policy if exists %I on %I', p_table || '_insert', p_table);
  execute format('create policy %I on %I for insert to authenticated with check (%s)',
                 p_table || '_insert', p_table, v_write);

  execute format('drop policy if exists %I on %I', p_table || '_update', p_table);
  execute format('create policy %I on %I for update to authenticated using (%s) with check (%s)',
                 p_table || '_update', p_table, v_write_using, v_write);

  execute format('drop policy if exists %I on %I', p_table || '_delete', p_table);
  execute format('create policy %I on %I for delete to authenticated using (%s)',
                 p_table || '_delete', p_table, v_write_using);
end;
$$;

-- -----------------------------------------------------------------------------
-- Three-tier library tables
-- -----------------------------------------------------------------------------
select app.apply_library_rls('cost_codes');
select app.apply_library_rls('services');
select app.apply_library_rls('tasks');
select app.apply_library_rls('labor_rates');
select app.apply_library_rls('equipment');
select app.apply_library_rls('crews');
select app.apply_library_rls('assemblies');
select app.apply_library_rls('materials');
select app.apply_library_rls('production_rates');
select app.apply_library_rls('condition_modifiers');
select app.apply_library_rls('pricing_profiles');
select app.apply_library_rls('regional_factors');

-- -----------------------------------------------------------------------------
-- Company-scoped tables
-- -----------------------------------------------------------------------------
select app.apply_tenant_rls('divisions', null, 'company.manage');
select app.apply_tenant_rls('equipment_rates', null, 'libraries.write');
select app.apply_tenant_rls('crew_members', null, 'libraries.write');
select app.apply_tenant_rls('assembly_components', null, 'libraries.write');
select app.apply_tenant_rls('markup_components', null, 'libraries.write');
select app.apply_tenant_rls('vendors', null, 'libraries.write');
select app.apply_tenant_rls('disposal_sites', null, 'libraries.write');
select app.apply_tenant_rls('trucking_rates', null, 'libraries.write');

select app.apply_tenant_rls('customers', null, 'crm.write');
select app.apply_tenant_rls('contacts', null, 'crm.write');
select app.apply_tenant_rls('leads', null, 'crm.write');
select app.apply_tenant_rls('opportunities', null, 'crm.write');
select app.apply_tenant_rls('crm_activities', null, 'crm.write');

select app.apply_tenant_rls('documents', null, 'documents.write');
select app.apply_tenant_rls('document_versions', null, 'documents.write');
select app.apply_tenant_rls('document_sheets', null, 'documents.write');

select app.apply_tenant_rls('estimates', null, 'estimates.write');
select app.apply_tenant_rls('estimate_versions', null, 'estimates.write');
select app.apply_tenant_rls('estimate_line_items', null, 'estimates.write');
select app.apply_tenant_rls('estimate_line_resources', null, 'estimates.write');
select app.apply_tenant_rls('estimate_line_modifiers', null, 'estimates.write');
select app.apply_tenant_rls('estimate_indirects', null, 'estimates.write');
select app.apply_tenant_rls('estimate_assumptions', null, 'estimates.write');
select app.apply_tenant_rls('estimate_exclusions', null, 'estimates.write');
select app.apply_tenant_rls('document_conflicts', null, 'estimates.write');
select app.apply_tenant_rls('bid_reconciliations', null, 'estimates.write');
select app.apply_tenant_rls('rfis', null, 'estimates.write');
select app.apply_tenant_rls('proposals', null, 'estimates.write');

select app.apply_tenant_rls('projects', null, 'projects.write');
select app.apply_tenant_rls('project_tasks', null, 'projects.write');
select app.apply_tenant_rls('task_dependencies', null, 'projects.write');
select app.apply_tenant_rls('project_costs', null, 'projects.write');
select app.apply_tenant_rls('daily_reports', null, 'projects.write');
select app.apply_tenant_rls('production_actuals', null, 'projects.write');
select app.apply_tenant_rls('change_orders', null, 'projects.write');

select app.apply_tenant_rls('ai_conversations');
select app.apply_tenant_rls('ai_messages');
select app.apply_tenant_rls('risks', null, 'estimates.write');
select app.apply_tenant_rls('approval_requests');

-- -----------------------------------------------------------------------------
-- Tables needing bespoke policies
-- -----------------------------------------------------------------------------

-- Enterprise groups: readable by members of any company in the group.
alter table enterprise_groups enable row level security;
alter table enterprise_groups force row level security;
create policy enterprise_groups_select on enterprise_groups for select to authenticated
  using (id in (select c.enterprise_group_id from companies c
                where c.id in (select app.current_company_ids()) and c.enterprise_group_id is not null));

-- Companies: a member reads their own company; an owner may update it.
alter table companies enable row level security;
alter table companies force row level security;
create policy companies_select on companies for select to authenticated
  using (id in (select app.current_company_ids()));
create policy companies_update on companies for update to authenticated
  using (app.has_permission(id, 'company.manage'))
  with check (app.has_permission(id, 'company.manage'));
-- Company creation goes through the provisioning function, never a raw insert.

-- User profiles: a user reads and edits their own, and reads co-members'.
alter table user_profiles enable row level security;
alter table user_profiles force row level security;
create policy user_profiles_select_self on user_profiles for select to authenticated
  using (id = auth.uid());
create policy user_profiles_select_colleagues on user_profiles for select to authenticated
  using (exists (
    select 1 from company_memberships m
    where m.user_id = user_profiles.id
      and m.company_id in (select app.current_company_ids())
      and m.status = 'active'
  ));
create policy user_profiles_insert_self on user_profiles for insert to authenticated
  with check (id = auth.uid());
create policy user_profiles_update_self on user_profiles for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());

-- Roles: system roles are readable by everyone; company roles by their members.
alter table roles enable row level security;
alter table roles force row level security;
create policy roles_select on roles for select to authenticated
  using (company_id is null or app.is_member(company_id));
create policy roles_insert on roles for insert to authenticated
  with check (company_id is not null and app.has_permission(company_id, 'users.manage') and not is_system);
create policy roles_update on roles for update to authenticated
  using (company_id is not null and not is_system and app.has_permission(company_id, 'users.manage'))
  with check (company_id is not null and not is_system and app.has_permission(company_id, 'users.manage'));
create policy roles_delete on roles for delete to authenticated
  using (company_id is not null and not is_system and app.has_permission(company_id, 'users.manage'));

-- Memberships: a user always sees their own; administrators see the company's.
alter table company_memberships enable row level security;
alter table company_memberships force row level security;
create policy company_memberships_select on company_memberships for select to authenticated
  using (user_id = auth.uid() or app.is_member(company_id));
create policy company_memberships_insert on company_memberships for insert to authenticated
  with check (app.has_permission(company_id, 'users.manage'));
create policy company_memberships_update on company_memberships for update to authenticated
  using (app.has_permission(company_id, 'users.manage'))
  with check (app.has_permission(company_id, 'users.manage'));
create policy company_memberships_delete on company_memberships for delete to authenticated
  using (app.has_permission(company_id, 'users.manage'));

alter table company_invitations enable row level security;
alter table company_invitations force row level security;
create policy company_invitations_all on company_invitations for all to authenticated
  using (app.has_permission(company_id, 'users.manage'))
  with check (app.has_permission(company_id, 'users.manage'));

-- Audit ledger: readable by members with the audit permission, append-only.
-- No UPDATE or DELETE policy exists, so those are denied for every tenant role
-- in addition to being blocked by trigger.
alter table audit_events enable row level security;
alter table audit_events force row level security;
create policy audit_events_select on audit_events for select to authenticated
  using (company_id is not null and app.has_permission(company_id, 'audit.read'));
create policy audit_events_insert on audit_events for insert to authenticated
  with check (company_id is null or app.is_member(company_id));

-- AI findings: readable by members; a human with permission accepts or rejects.
alter table ai_findings enable row level security;
alter table ai_findings force row level security;
create policy ai_findings_select on ai_findings for select to authenticated
  using (app.is_member(company_id));
create policy ai_findings_insert on ai_findings for insert to authenticated
  with check (app.is_member(company_id) and state = 'proposed');
create policy ai_findings_update on ai_findings for update to authenticated
  using (app.has_permission(company_id, 'ai.accept_findings'))
  with check (app.has_permission(company_id, 'ai.accept_findings'));

-- The AI agent registry is global, read-only to tenants.
alter table ai_agents enable row level security;
alter table ai_agents force row level security;
create policy ai_agents_select on ai_agents for select to authenticated using (true);

-- Calibration proposals need the library-approval permission to decide.
alter table production_calibrations enable row level security;
alter table production_calibrations force row level security;
create policy production_calibrations_select on production_calibrations for select to authenticated
  using (app.is_member(company_id));
create policy production_calibrations_insert on production_calibrations for insert to authenticated
  with check (app.is_member(company_id) and state = 'pending');
create policy production_calibrations_update on production_calibrations for update to authenticated
  using (app.has_permission(company_id, 'libraries.approve'))
  with check (app.has_permission(company_id, 'libraries.approve'));

-- -----------------------------------------------------------------------------
-- Billing
-- -----------------------------------------------------------------------------

-- The plan catalog is public: the pricing page must render before sign-in.
alter table plans enable row level security;
alter table plans force row level security;
create policy plans_select on plans for select to anon, authenticated
  using (is_active and is_public);

alter table plan_prices enable row level security;
alter table plan_prices force row level security;
create policy plan_prices_select on plan_prices for select to anon, authenticated
  using (is_active and exists (select 1 from plans p where p.id = plan_prices.plan_id and p.is_active and p.is_public));

/*
 * Subscriptions, entitlements and invoices are readable by billing
 * administrators and writable by nobody holding a tenant role.
 *
 * There is deliberately no INSERT or UPDATE policy for `authenticated`: these
 * rows are written exclusively by the stripe-webhook Edge Function using the
 * service role, which bypasses RLS. That is the structural enforcement of
 * "never trust a browser redirect to activate paid access".
 */
alter table subscriptions enable row level security;
alter table subscriptions force row level security;
create policy subscriptions_select on subscriptions for select to authenticated
  using (app.has_permission(company_id, 'billing.read'));

alter table subscription_items enable row level security;
alter table subscription_items force row level security;
create policy subscription_items_select on subscription_items for select to authenticated
  using (app.has_permission(company_id, 'billing.read'));

alter table entitlements enable row level security;
alter table entitlements force row level security;
-- Entitlement is readable by any member: the UI must know which features to show.
create policy entitlements_select on entitlements for select to authenticated
  using (app.is_member(company_id));

alter table billing_invoices enable row level security;
alter table billing_invoices force row level security;
create policy billing_invoices_select on billing_invoices for select to authenticated
  using (app.has_permission(company_id, 'billing.read'));

alter table usage_events enable row level security;
alter table usage_events force row level security;
create policy usage_events_select on usage_events for select to authenticated
  using (app.has_permission(company_id, 'billing.read'));
create policy usage_events_insert on usage_events for insert to authenticated
  with check (app.is_member(company_id));

-- Raw Stripe payloads are service-role only. No tenant policy exists at all,
-- so with RLS forced this table is unreadable through the public API.
alter table stripe_events enable row level security;
alter table stripe_events force row level security;
