-- =============================================================================
-- 0082 — Suspending an account, and giving it back
--
-- Until now the only lever an operator had over a company that stopped paying
-- was revoking its entitlement — the same control used to end a comp. So "they
-- are three months in arrears" and "we gave them a free year and it ran out"
-- left identical records, and neither told the customer anything.
--
-- A suspension here is **read-only, not a lockout**, and that is the whole
-- design decision:
--
--   * They can still sign in.
--   * They can still open, read, print and export every estimate, project,
--     document and cost record they ever made.
--   * They cannot create or change anything until it is lifted.
--
-- Holding a customer's own records hostage over an unpaid invoice is not
-- leverage, it is a hostage situation — and it is the thing that makes a
-- contractor tell every other contractor never to use you. The same reasoning
-- already governs the free tier in migration 0077: gates refuse new work and
-- never hide old work.
--
-- Two carve-outs, both deliberate:
--
--   * **Machine writes are never blocked.** A suspended company still receives
--     Stripe webhooks, and one of them may be the payment that lifts the
--     suspension. A trigger that refused those would make a suspension
--     impossible to end by paying.
--   * **A legal hold is stricter by convention, not by code.** Nothing here
--     deletes or hides. If a court order requires more than read-only, that is
--     a conversation with a lawyer, not a button.
-- =============================================================================

create table company_suspensions (
  id               uuid primary key default gen_random_uuid(),
  company_id       uuid not null references companies(id) on delete cascade,
  /*
   * Why, in a word, because the four reasons behave differently in a review:
   * non-payment ends when they pay, abuse ends when it stops, a legal hold ends
   * when somebody says so, and a customer who asked can be given it back on
   * request.
   */
  kind             text not null check (kind in ('nonpayment', 'abuse', 'legal_hold', 'requested')),
  reason           text not null check (length(trim(reason)) >= 10),
  /*
   * What the customer is shown. Separate from `reason` on purpose: the internal
   * note and the message to a paying business are not the same sentence, and
   * writing one and displaying the other is how an operator ends up sending a
   * customer a line they did not intend to send.
   */
  customer_message text not null check (length(trim(customer_message)) >= 10),
  suspended_by     uuid references auth.users(id) on delete set null,
  suspended_at     timestamptz not null default now(),
  lifted_at        timestamptz,
  lifted_by        uuid references auth.users(id) on delete set null,
  lift_reason      text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint company_suspensions_lift check (lifted_at is null or lift_reason is not null)
);

comment on table company_suspensions is
  'A company put into read-only, why, and what the customer was told. ENTITY. A suspension never hides or deletes anything: the customer keeps reading and exporting everything they built and simply cannot add to it. Kept after it is lifted, because "were we ever suspended, and why" is a question asked long afterwards.';

-- One live suspension per company. Two would be a question with two answers.
create unique index if not exists company_suspensions_one_live
  on company_suspensions (company_id) where lifted_at is null;
create index if not exists company_suspensions_company on company_suspensions (company_id, suspended_at desc);

select app.apply_tenant_rls('company_suspensions');
select app.attach_standard_triggers('public.company_suspensions'::regclass);

-- A customer reads their own; nobody writes one except through the functions
-- below, which are definer and record who and why.
drop policy if exists company_suspensions_insert on company_suspensions;
drop policy if exists company_suspensions_update on company_suspensions;
drop policy if exists company_suspensions_delete on company_suspensions;

/** Is this company in read-only right now? */
create or replace function app.is_suspended(p_company uuid)
returns boolean
language sql stable security definer set search_path = public, pg_catalog
as $$
  select exists (
    select 1 from company_suspensions s
    where s.company_id = p_company and s.lifted_at is null
  );
$$;

grant execute on function app.is_suspended(uuid) to authenticated, service_role, anon;

/**
 * Refuses a write from a person while their company is suspended.
 *
 * Attached to every tenant-owned table rather than expressed in policies,
 * because the policies were generated by `app.apply_tenant_rls` with
 * per-table permission arguments that cannot be recovered to regenerate them
 * — and a suspension that covered most tables would be worse than none.
 *
 * `auth.uid() is null` means this is not a person: a Stripe webhook, the
 * pricing engine, a scheduled job. Those are never blocked, and the reason is
 * concrete — the webhook that lifts a non-payment suspension is the payment
 * itself, and refusing it would make a suspension impossible to end by paying.
 */
create or replace function app.refuse_when_suspended()
returns trigger
language plpgsql security definer set search_path = public, pg_catalog
as $$
declare
  v_company uuid;
  v_message text;
begin
  if auth.uid() is null then
    return case when tg_op = 'DELETE' then old else new end;
  end if;

  v_company := case when tg_op = 'DELETE' then old.company_id else new.company_id end;
  if v_company is null then
    -- A global library row belongs to no tenant and cannot be suspended.
    return case when tg_op = 'DELETE' then old else new end;
  end if;

  select s.customer_message into v_message
  from company_suspensions s
  where s.company_id = v_company and s.lifted_at is null;

  if v_message is null then
    return case when tg_op = 'DELETE' then old else new end;
  end if;

  raise exception '%', v_message
    using errcode = 'insufficient_privilege',
          hint = 'Your records are all still here and can be read and exported.';
end;
$$;

comment on function app.refuse_when_suspended() is
  'Refuses a person''s write while their company is suspended, and says why in the words the operator wrote for them. Reads are untouched, and machine writes are never blocked — the Stripe webhook that ends a non-payment suspension is a machine write.';

/** Put the guard on one table. What a later migration calls for a new one. */
create or replace function app.guard_suspension(p_table text)
returns void
language plpgsql
as $$
begin
  execute format('drop trigger if exists %I on public.%I',
                 p_table || '_suspension', p_table);
  execute format(
    'create trigger %I before insert or update or delete on public.%I
       for each row execute function app.refuse_when_suspended()',
    p_table || '_suspension', p_table);
end;
$$;

comment on function app.guard_suspension(text) is
  'Puts the read-only guard on one tenant table. Every table carrying a company_id needs it; a migration that adds one calls this, and the invariant test in tests/db/suspension.test.ts fails on the next run if it did not.';

/*
 * Applied to every table that has a company_id. Written as a loop over the
 * catalog rather than a list, so nothing built before today is missed — and a
 * test asserts the same coverage from the other side, so a table added later
 * that forgets `app.guard_suspension` fails on the next run rather than
 * quietly falling outside every suspension.
 */
do $$
declare
  r record;
  v_count int := 0;
begin
  for r in
    select c.relname
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    join pg_attribute a on a.attrelid = c.oid and a.attname = 'company_id'
                       and a.attnum > 0 and not a.attisdropped
    where n.nspname = 'public' and c.relkind = 'r'
      -- The ledgers are append-only and already refuse a person's write; the
      -- suspension record itself must stay writable so it can be lifted.
      and c.relname not in ('audit_events', 'api_requests', 'usage_events',
                            'company_suspensions', 'stripe_events')
    order by c.relname
  loop
    perform app.guard_suspension(r.relname);
    v_count := v_count + 1;
  end loop;

  -- A loop that covered nothing would leave a feature that reports itself as
  -- working and does not work.
  if v_count < 100 then
    raise exception 'Only % tenant tables were covered by the suspension guard', v_count;
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- Doing it
-- -----------------------------------------------------------------------------
create or replace function app.suspend_company(
  p_company uuid, p_kind text, p_reason text, p_customer_message text)
returns uuid
language plpgsql security definer set search_path = public, pg_catalog
as $$
declare v_id uuid;
begin
  if not app.operator_can('companies.manage') then
    raise exception 'You do not have permission to suspend an account'
      using errcode = 'insufficient_privilege';
  end if;
  if p_kind not in ('nonpayment', 'abuse', 'legal_hold', 'requested') then
    raise exception 'A suspension has a stated kind, not "%"', p_kind
      using errcode = 'check_violation';
  end if;
  if p_reason is null or length(trim(p_reason)) < 10 then
    raise exception 'Say why, at length; somebody will read this in a year'
      using errcode = 'check_violation';
  end if;
  if p_customer_message is null or length(trim(p_customer_message)) < 10 then
    raise exception 'Write what the customer will see. They are going to see something'
      using errcode = 'check_violation';
  end if;
  if not exists (select 1 from companies where id = p_company) then
    raise exception 'Company % not found', p_company using errcode = 'no_data_found';
  end if;
  if app.is_suspended(p_company) then
    raise exception 'That account is already suspended' using errcode = 'unique_violation';
  end if;

  insert into company_suspensions
    (company_id, kind, reason, customer_message, suspended_by)
  values (p_company, p_kind, trim(p_reason), trim(p_customer_message), auth.uid())
  returning id into v_id;

  insert into audit_events (company_id, actor_id, action, entity_table, entity_id,
                            new_state, reason)
  values (p_company, auth.uid(), 'update', 'public.company_suspensions', v_id::text,
          jsonb_build_object('kind', p_kind, 'customer_message', trim(p_customer_message)),
          trim(p_reason));
  return v_id;
end;
$$;

create or replace function app.restore_company(p_company uuid, p_reason text)
returns void
language plpgsql security definer set search_path = public, pg_catalog
as $$
begin
  if not app.operator_can('companies.manage') then
    raise exception 'You do not have permission to restore an account'
      using errcode = 'insufficient_privilege';
  end if;
  if p_reason is null or length(trim(p_reason)) < 5 then
    raise exception 'Say why it is being lifted' using errcode = 'check_violation';
  end if;
  if not app.is_suspended(p_company) then
    raise exception 'That account is not suspended' using errcode = 'no_data_found';
  end if;

  update company_suspensions
     set lifted_at = now(), lifted_by = auth.uid(),
         lift_reason = trim(p_reason), updated_at = now()
   where company_id = p_company and lifted_at is null;

  insert into audit_events (company_id, actor_id, action, entity_table, entity_id,
                            new_state, reason)
  values (p_company, auth.uid(), 'update', 'public.company_suspensions', p_company::text,
          jsonb_build_object('lifted', true), trim(p_reason));
end;
$$;

-- -----------------------------------------------------------------------------
-- Seeing it, from both sides
-- -----------------------------------------------------------------------------
create or replace view my_suspension
with (security_invoker = true) as
select
  s.company_id,
  s.kind,
  -- What the operator wrote for them. Never the internal note.
  s.customer_message,
  s.suspended_at
from company_suspensions s
where s.lifted_at is null;

comment on view my_suspension is
  'A company''s own suspension, in the words written for them. The internal reason is deliberately not in this view: the note an operator writes for their colleagues and the message to a paying business are not the same sentence.';

grant select on my_suspension to authenticated;
revoke all on my_suspension from anon;

create or replace view admin_suspensions as
select
  s.id, s.company_id, c.name as company_name,
  s.kind, s.reason, s.customer_message,
  s.suspended_at, s.lifted_at, s.lift_reason,
  up.email as suspended_by_email,
  (s.lifted_at is null) as live,
  -- What they were paying when it happened, which is the first thing anybody
  -- asks about a suspension.
  app.billable_seats(s.company_id) as seats
from company_suspensions s
join companies c on c.id = s.company_id
left join user_profiles up on up.id = s.suspended_by
where app.operator_can('companies.read')
order by s.suspended_at desc;

comment on view admin_suspensions is
  'Every suspension, live and lifted, with what the customer was told and who decided. Lifted ones are kept because "were we ever suspended, and why" is asked long after it ended.';

grant select on admin_suspensions to authenticated;
revoke all on admin_suspensions from anon;

-- Wrappers.
create or replace function public.suspend_company(
  p_company uuid, p_kind text, p_reason text, p_customer_message text)
returns uuid language plpgsql security invoker set search_path = public, pg_catalog
as $$ begin return app.suspend_company(p_company, p_kind, p_reason, p_customer_message); end; $$;

create or replace function public.restore_company(p_company uuid, p_reason text)
returns void language plpgsql security invoker set search_path = public, pg_catalog
as $$ begin perform app.restore_company(p_company, p_reason); end; $$;

do $$
declare v_sig text;
begin
  foreach v_sig in array array[
    'app.suspend_company(uuid, text, text, text)',
    'app.restore_company(uuid, text)',
    'public.suspend_company(uuid, text, text, text)',
    'public.restore_company(uuid, text)'
  ] loop
    execute format('revoke all on function %s from public, anon', v_sig);
    execute format('grant execute on function %s to authenticated', v_sig);
  end loop;
end $$;

select app.assert_security_gates();
