-- =============================================================================
-- GENERATED — do not edit.
--
-- A verbatim copy of `supabase/seed/0006_task_templates.sql`, so the catalog can be applied
-- by `supabase db push` rather than by a direct database connection. The seed
-- file is the source; this is the delivery. `npm run seed:migrations`
-- regenerates it and a governance test fails if the two ever differ.
--
-- Everything below is idempotent — `on conflict do nothing` throughout — so
-- applying it twice changes nothing, which is what makes it safe as a
-- migration.
-- =============================================================================

-- =============================================================================
-- 0006 — Nineteen ways the work actually goes
--
-- The library has thousands of tasks and nothing saying what order they happen
-- in. A concrete estimate could name every step and could not say that the
-- forms go up before the pour — which is the difference between a price and a
-- schedule.
--
-- These are nineteen ordered sequences: concrete, demolition, electrical,
-- excavation, HVAC, openings, plumbing fixtures, plumbing lines, pressure
-- washing, residential remodel, DOT, maintenance of traffic, finishes, project
-- controls, specialty systems, and four drone missions — mapping, inspection,
-- thermal and media.
--
-- **40 rows were dropped, and that is the important part.** The file held two
-- generations of the same sequences, merged and never reconciled: an older
-- four-step version and a current ten-step one, sharing step numbers 1 to 4.
-- Ten of the nineteen templates were affected. Imported as they arrived, a
-- concrete estimate would have carried "Layout" twice and treated "Form /
-- reinforce" and "Set forms / edges" as different work.
--
-- The two are cleanly separable: every superseded row has a blank
-- `trade_family` and every current one has it filled. Dropping the 40 leaves
-- all nineteen templates with an unbroken 1..n sequence, which was checked
-- rather than assumed.
--
-- **The production rates are the ones actually stated** — 19 of them, and nothing
-- is invented for the rest. 80 CY/HR to excavate and 95 to haul are numbers
-- somebody put there; a step with no rate carries none rather than a
-- placeholder that would score as knowledge.
--
-- `MISSION` became `EA`: a drone mission is one thing, flown once. `AC` became
-- `ACRE`, the same measurement under a shorter name.
-- =============================================================================

insert into library_categories (company_id, kind, name, sort_order)
select null, 'crew_discipline', v.name, v.sort
from (values ('Project Controls', 600), ('Pressure Washing', 610),
             ('Maintenance of Traffic', 620), ('Transportation', 630),
             ('Windows / Doors', 640), ('Residential Remodel', 650),
             ('Specialty', 660), ('Drone', 670), ('Demolition', 680),
             ('Excavation', 690), ('General', 700)
) as v(name, sort)
on conflict do nothing;

insert into tasks (code, name, category, default_unit, production_required,
                   crew_required, equipment_required, status, source) values
  ('TSK-TT-LAYOUT-VERIFY-ELEVATIONS', 'Layout / verify elevations', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SUBGRADE-PREP-COMPACT', 'Subgrade prep / compact', 'Support', 'SY', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SET-FORMS-EDGES', 'Set forms / edges', 'Production', 'LF', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-INSTALL-REINFORCEMENT', 'Install reinforcement', 'Production', 'SF', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PLACE-EMBEDS-DOWELS', 'Place embeds / dowels', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-POUR-PLACE-CONCRETE', 'Pour / place concrete', 'Production', 'CY', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SCREED-FLOAT-FINISH', 'Screed / float / finish', 'Production', 'SF', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-CURE-PROTECT', 'Cure / protect', 'Production', 'SF', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SAWCUT-SEAL-JOINTS', 'Sawcut / seal joints', 'Production', 'LF', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-CLEANUP-STRIP-FORMS', 'Cleanup / strip forms', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-BID-PERMIT-INSURANCE-COORDIN', 'Bid / permit / insurance coordination', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SUBMITTALS-RFIS-SCHEDULE-SET', 'Submittals / RFIs / schedule setup', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-MOBILIZATION-TEMPORARY-CONTR', 'Mobilization / temporary controls', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-DAILY-SUPERVISION-COORDINATI', 'Daily supervision / coordination', 'Production', 'DAY', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-QA-QC-INSPECTIONS-DOCUMENTAT', 'QA/QC / inspections / documentation', 'Support', 'DAY', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-WASTE-ENVIRONMENTAL-CONTROLS', 'Waste / environmental controls', 'Production', 'DAY', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PUNCH-CLOSEOUT-DOCS-WARRANTI', 'Punch / closeout docs / warranties', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SCOPE-REVIEW-SURVEY-EXISTING', 'Scope review / survey existing', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PROTECTION-ISOLATE-SYSTEMS', 'Protection / isolate systems', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-ABATEMENT-HAZARDOUS-CHECK', 'Abatement / hazardous check', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-MOBILIZE-DEMO-EQUIPMENT', 'Mobilize demo equipment', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SELECTIVE-REMOVAL', 'Selective removal', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PRIMARY-DEMOLITION', 'Primary demolition', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SEPARATE-SALVAGE-RECYCLE', 'Separate salvage / recycle', 'Production', 'TON', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-LOAD-DEBRIS', 'Load debris', 'Production', 'TON', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-HAUL-DISPOSE', 'Haul / dispose', 'Production', 'TON', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-FINAL-CLEANUP-VERIFY', 'Final cleanup / verify', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-REVIEW-PLANS-TRAFFIC-COORDIN', 'Review plans / traffic coordination', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SURVEY-LAYOUT-LOCATES', 'Survey / layout / locates', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PREP-SUBBASE-REMOVALS-IF-NEE', 'Prep subbase / removals if needed', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-INSTALL-CIVILS-STRUCTURES-SU', 'Install civils / structures / supports', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-INSTALL-PAVING-MARKINGS-DEVI', 'Install paving / markings / devices', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-INSTALL-SIGNALS-SIGNS-LIGHTI', 'Install signals / signs / lighting / ITS', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-TEST-SYSTEMS-VERIFY-GEOMETRY', 'Test systems / verify geometry', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PUNCH-ADJUST-SEAL-STRIPE', 'Punch / adjust / seal / stripe', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-AGENCY-INSPECTION-ACCEPTANCE', 'Agency inspection / acceptance', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-CLEANUP-TURNOVER', 'Cleanup / turnover', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-MISSION-PLAN-AIRSPACE-CHECKL', 'Mission plan / airspace / checklist', 'Support', 'EA', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-MOBILIZE-LAUNCH-CAPTURE', 'Mobilize / launch / capture', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PROCESS-ANNOTATE-FINDINGS', 'Process / annotate findings', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-DELIVER-REPORT-ARCHIVE-FILES', 'Deliver report / archive files', 'Support', 'EA', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-MISSION-PLAN-CONTROL-SETUP', 'Mission plan / control setup', 'Support', 'EA', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-FLY-GRID-CAPTURE-OVERLAP', 'Fly grid / capture overlap', 'Production', 'ACRE', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PROCESS-STITCH-QA', 'Process / stitch / QA', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-DELIVER-GEO-OUTPUTS', 'Deliver geo outputs', 'Support', 'EA', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-CREATIVE-BRIEF-SHOT-PLAN', 'Creative brief / shot plan', 'Support', 'EA', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-CAPTURE-PHOTO-VIDEO-PASSES', 'Capture photo / video passes', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-EDIT-COLOR-EXPORT', 'Edit / color / export', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-DELIVER-MEDIA-PACKAGE', 'Deliver media package', 'Support', 'EA', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-MISSION-PLAN-THERMAL-SETUP', 'Mission plan / thermal setup', 'Support', 'EA', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-CAPTURE-THERMAL-IMAGERY', 'Capture thermal imagery', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PROCESS-COMPARE-ANNOTATE', 'Process / compare / annotate', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-DELIVER-THERMAL-REPORT', 'Deliver thermal report', 'Support', 'EA', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SCOPE-REVIEW-VERIFY-CIRCUIT', 'Scope review / verify circuit', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-LOCKOUT-TAGOUT', 'Lockout / tagout', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-OPEN-WALLS-PATHWAYS-IF-NEEDE', 'Open walls / pathways if needed', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-INSTALL-BOXES-RACEWAY', 'Install boxes / raceway', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PULL-WIRE-CABLE', 'Pull wire / cable', 'Production', 'LF', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SET-DEVICE-FIXTURE-PANEL-ITE', 'Set device / fixture / panel item', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-TERMINATE-CONDUCTORS', 'Terminate conductors', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-LABEL-PROGRAM-IF-NEEDED', 'Label / program if needed', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-TEST-ENERGIZE-VERIFY', 'Test / energize / verify', 'Support', 'EA', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SCOPE-REVIEW-LAYOUT', 'Scope review / layout', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-UTILITY-LOCATE-SAFETY-PREP', 'Utility locate / safety prep', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-MOBILIZE-EQUIPMENT', 'Mobilize equipment', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-CLEAR-STRIP-REMOVE-TOPSOIL', 'Clear / strip / remove topsoil', 'Production', 'CY', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-EXCAVATE-TO-LINE-AND-GRADE', 'Excavate to line and grade', 'Production', 'CY', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-LOAD-HAUL-STOCKPILE', 'Load / haul / stockpile', 'Production', 'CY', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-INSTALL-BEDDING-STABILIZATIO', 'Install bedding / stabilization if needed', 'Production', 'CY', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-BACKFILL-COMPACT', 'Backfill / compact', 'Production', 'CY', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-FINE-GRADE-PROOF-VERIFY', 'Fine grade / proof / verify', 'Production', 'SY', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-CLEANUP-DEMOBILIZE', 'Cleanup / demobilize', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SCOPE-REVIEW-MOISTURE-VERIFY', 'Scope review / moisture verify', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PROTECT-ADJACENT-SURFACES', 'Protect adjacent surfaces', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-REMOVE-EXISTING-IF-NEEDED', 'Remove existing if needed', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PREP-SUBSTRATE', 'Prep substrate', 'Support', 'SF', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-LAYOUT-STAGE-MATERIALS', 'Layout / stage materials', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-INSTALL-FINISH-SYSTEM', 'Install finish system', 'Production', 'SF', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-TRIM-TRANSITIONS-DETAILING', 'Trim / transitions / detailing', 'Production', 'LF', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-COAT-SEAL-CURE-IF-NEEDED', 'Coat / seal / cure if needed', 'Production', 'SF', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-INSPECT-TOUCHUP', 'Inspect / touchup', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SCOPE-REVIEW-VERIFY-EQUIPMEN', 'Scope review / verify equipment', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PROTECT-AREA-ISOLATE-POWER', 'Protect area / isolate power', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-RECOVER-REFRIGERANT-DISCONNE', 'Recover refrigerant / disconnect', 'Support', 'EA', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-REMOVE-EXISTING-EQUIPMENT-IF', 'Remove existing equipment if needed', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SET-NEW-EQUIPMENT', 'Set new equipment', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-CONNECT-REFRIGERANT-CONDENSA', 'Connect refrigerant / condensate', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-CONNECT-DUCT-VENT-GAS-CONTRO', 'Connect duct / vent / gas / controls', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-EVACUATE-CHARGE-STARTUP', 'Evacuate / charge / startup', 'Support', 'EA', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-BALANCE-COMMISSION-VERIFY', 'Balance / commission / verify', 'Support', 'EA', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-REVIEW-MOT-PLAN-PERMIT', 'Review MOT plan / permit', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PRE-STAGE-DEVICES-INSPECT', 'Pre-stage devices / inspect', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-DEPLOY-SIGNS-ADVANCE-WARNING', 'Deploy signs / advance warning', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-DEPLOY-CHANNELIZATION-BARRIE', 'Deploy channelization / barriers', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-IMPLEMENT-CLOSURE-DETOUR-TAP', 'Implement closure / detour / taper', 'Production', 'DAY', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-DAILY-MAINTENANCE-RESET', 'Daily maintenance / reset', 'Production', 'DAY', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-INSPECT-DOCUMENT-COMPLIANCE', 'Inspect / document compliance', 'Support', 'DAY', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-RELOCATE-DEVICES-AS-WORK-SHI', 'Relocate devices as work shifts', 'Production', 'DAY', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-REMOVE-DEVICES-RESTORE-TRAFF', 'Remove devices / restore traffic', 'Support', 'DAY', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PICKUP-DEMOBILIZE', 'Pickup / demobilize', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-VERIFY-OPENING-MEASURE', 'Verify opening / measure', 'Support', 'EA', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PROTECT-AREA', 'Protect area', 'Support', 'EA', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-REMOVE-EXISTING-UNIT', 'Remove existing unit', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PREP-OPENING-REPAIR-SUBSTRAT', 'Prep opening / repair substrate', 'Support', 'EA', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-INSTALL-FLASHING-PAN-SEAL', 'Install flashing / pan / seal', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SET-FRAME-UNIT', 'Set frame / unit', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-FASTEN-PLUMB-INSULATE', 'Fasten / plumb / insulate', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-INTERIOR-EXTERIOR-TRIM', 'Interior / exterior trim', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-ADJUST-HARDWARE-VERIFY-OPERA', 'Adjust hardware / verify operation', 'Support', 'EA', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SCOPE-REVIEW-VERIFY-FIXTURE', 'Scope review / verify fixture', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SHUT-DOWN-ISOLATE-SUPPLY', 'Shut down / isolate supply', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-REMOVE-EXISTING-IF-APPLICABL', 'Remove existing if applicable', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PREP-ROUGH-IN-ANCHORAGE', 'Prep rough-in / anchorage', 'Support', 'EA', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SET-FIXTURE', 'Set fixture', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-CONNECT-SUPPLY', 'Connect supply', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-CONNECT-WASTE-VENT', 'Connect waste / vent', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SEAL-TRIM-CAULK', 'Seal / trim / caulk', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-TEST-LEAK-CHECK-ADJUST', 'Test / leak check / adjust', 'Support', 'EA', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-LOCATE-LINE-VERIFY-ROUTING', 'Locate line / verify routing', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-OPEN-ACCESS-TRENCH-EXPOSE', 'Open access / trench / expose', 'Support', 'LF', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-REMOVE-EXISTING-LINE-IF-NEED', 'Remove existing line if needed', 'Production', 'LF', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-INSTALL-HANGERS-SUPPORTS', 'Install hangers / supports', 'Production', 'LF', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-INSTALL-PIPE-FITTINGS', 'Install pipe / fittings', 'Production', 'LF', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-CONNECT-TIE-IN', 'Connect / tie in', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-INSULATE-WRAP-IF-NEEDED', 'Insulate / wrap if needed', 'Production', 'LF', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PRESSURE-FLOW-SMOKE-TEST', 'Pressure / flow / smoke test', 'Support', 'LF', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PATCH-RESTORE-SURFACES', 'Patch / restore surfaces', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SCOPE-REVIEW-SURFACE-CHECK', 'Scope review / surface check', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PROTECT-OUTLETS-PLANTS-ADJAC', 'Protect outlets / plants / adjacencies', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SETUP-WATER-HOSES-CONTAINMEN', 'Setup water / hoses / containment', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-APPLY-DETERGENT-PRETREAT', 'Apply detergent / pretreat', 'Support', 'SF', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-MAIN-WASH-PASS', 'Main wash pass', 'Production', 'SF', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-DETAIL-CORNERS-EDGES-STAINS', 'Detail corners / edges / stains', 'Production', 'SF', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-RINSE-NEUTRALIZE-POST-TREAT', 'Rinse / neutralize / post-treat', 'Production', 'SF', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-EQUIPMENT-RINSE-RESET-SITE', 'Equipment rinse / reset site', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-FINAL-VISUAL-INSPECTION', 'Final visual inspection', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SCOPE-REVIEW-SELECTIONS-VERI', 'Scope review / selections verify', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PROTECT-OCCUPIED-AREAS', 'Protect occupied areas', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SELECTIVE-DEMOLITION', 'Selective demolition', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-FRAMING-BLOCKING-ROUGH-CARPE', 'Framing / blocking / rough carpentry', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-MEP-ROUGH-COORDINATION', 'MEP rough coordination', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-DRYWALL-PATCH-PREP', 'Drywall / patch / prep', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-FINISH-INSTALL-TRIM-ACCESSOR', 'Finish install / trim / accessories', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PAINT-TOUCHUP', 'Paint / touchup', 'Production', 'LS', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-PUNCH-LIST-CORRECTIONS', 'Punch list / corrections', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-FINAL-CLEAN-TURNOVER', 'Final clean / turnover', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-VERIFY-MANUFACTURER-SUBMITTA', 'Verify manufacturer submittals', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-COORDINATE-UTILITIES-CLEARAN', 'Coordinate utilities / clearances', 'Support', 'LS', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SET-BASE-ANCHORAGE', 'Set base / anchorage', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-SET-EQUIPMENT-SPECIALTY-UNIT', 'Set equipment / specialty unit', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-CONNECT-MECHANICAL-ELECTRICA', 'Connect mechanical / electrical / controls', 'Production', 'EA', true, true, true, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-STARTUP-CALIBRATION', 'Startup / calibration', 'Support', 'EA', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-TRAINING-OWNER-DEMO', 'Training / owner demo', 'Support', 'EA', false, false, false, 'active', 'GrounUp task templates v1'),
  ('TSK-TT-LABEL-DOCUMENT', 'Label / document', 'Support', 'EA', false, false, false, 'active', 'GrounUp task templates v1')
on conflict do nothing;

insert into assemblies (code, name, assembly_type, quantity_unit, status, source) values
  ('ASM-TT-CONC-STD', 'Concrete Template', 'Concrete', 'LS', 'active', 'GrounUp task templates v1'),
  ('ASM-TT-CTRL-STD', 'Project Controls Template', 'Project Controls', 'LS', 'active', 'GrounUp task templates v1'),
  ('ASM-TT-DEM-STD', 'Demolition Template', 'Demolition', 'LS', 'active', 'GrounUp task templates v1'),
  ('ASM-TT-DOT-STD', 'Transportation Template', 'Transportation', 'LS', 'active', 'GrounUp task templates v1'),
  ('ASM-TT-DRN-INSP', 'Drone Inspection Template', 'Drone', 'LS', 'active', 'GrounUp task templates v1'),
  ('ASM-TT-DRN-MAP', 'Drone Mapping Template', 'Drone', 'LS', 'active', 'GrounUp task templates v1'),
  ('ASM-TT-DRN-MED', 'Drone Media Template', 'Drone', 'LS', 'active', 'GrounUp task templates v1'),
  ('ASM-TT-DRN-THM', 'Drone Thermal Template', 'Drone', 'LS', 'active', 'GrounUp task templates v1'),
  ('ASM-TT-ELEC-STD', 'Electrical Template', 'Electrical', 'LS', 'active', 'GrounUp task templates v1'),
  ('ASM-TT-EXC-STD', 'Excavation Template', 'Excavation', 'LS', 'active', 'GrounUp task templates v1'),
  ('ASM-TT-FINI-STD', 'Finishes Template', 'Finishes', 'LS', 'active', 'GrounUp task templates v1'),
  ('ASM-TT-HVAC-STD', 'HVAC Template', 'HVAC', 'LS', 'active', 'GrounUp task templates v1'),
  ('ASM-TT-MOT-STD', 'MOT Template', 'Maintenance of Traffic', 'LS', 'active', 'GrounUp task templates v1'),
  ('ASM-TT-OPEN-STD', 'Openings Template', 'Windows / Doors', 'LS', 'active', 'GrounUp task templates v1'),
  ('ASM-TT-PLBG-FIX', 'Plumbing Fixture Template', 'Plumbing', 'LS', 'active', 'GrounUp task templates v1'),
  ('ASM-TT-PLBG-LINE', 'Plumbing Line Template', 'Plumbing', 'LS', 'active', 'GrounUp task templates v1'),
  ('ASM-TT-PW-STD', 'Pressure Washing Template', 'Pressure Washing', 'LS', 'active', 'GrounUp task templates v1'),
  ('ASM-TT-RMOD-STD', 'Residential Remodel Template', 'Residential Remodel', 'LS', 'active', 'GrounUp task templates v1'),
  ('ASM-TT-SPCL-STD', 'Specialty Systems Template', 'Specialty', 'LS', 'active', 'GrounUp task templates v1')
on conflict do nothing;

insert into assembly_components (company_id, assembly_id, component_kind, task_id,
                                 quantity_per_unit, sort_order)
select null, a.id, 'task', t.id, 1, v.sort
from (values
  ('ASM-TT-CONC-STD', 'TSK-TT-LAYOUT-VERIFY-ELEVATIONS', 10),
  ('ASM-TT-CONC-STD', 'TSK-TT-SUBGRADE-PREP-COMPACT', 20),
  ('ASM-TT-CONC-STD', 'TSK-TT-SET-FORMS-EDGES', 30),
  ('ASM-TT-CONC-STD', 'TSK-TT-INSTALL-REINFORCEMENT', 40),
  ('ASM-TT-CONC-STD', 'TSK-TT-PLACE-EMBEDS-DOWELS', 50),
  ('ASM-TT-CONC-STD', 'TSK-TT-POUR-PLACE-CONCRETE', 60),
  ('ASM-TT-CONC-STD', 'TSK-TT-SCREED-FLOAT-FINISH', 70),
  ('ASM-TT-CONC-STD', 'TSK-TT-CURE-PROTECT', 80),
  ('ASM-TT-CONC-STD', 'TSK-TT-SAWCUT-SEAL-JOINTS', 90),
  ('ASM-TT-CONC-STD', 'TSK-TT-CLEANUP-STRIP-FORMS', 100),
  ('ASM-TT-CTRL-STD', 'TSK-TT-BID-PERMIT-INSURANCE-COORDIN', 10),
  ('ASM-TT-CTRL-STD', 'TSK-TT-SUBMITTALS-RFIS-SCHEDULE-SET', 20),
  ('ASM-TT-CTRL-STD', 'TSK-TT-MOBILIZATION-TEMPORARY-CONTR', 30),
  ('ASM-TT-CTRL-STD', 'TSK-TT-DAILY-SUPERVISION-COORDINATI', 40),
  ('ASM-TT-CTRL-STD', 'TSK-TT-QA-QC-INSPECTIONS-DOCUMENTAT', 50),
  ('ASM-TT-CTRL-STD', 'TSK-TT-WASTE-ENVIRONMENTAL-CONTROLS', 60),
  ('ASM-TT-CTRL-STD', 'TSK-TT-PUNCH-CLOSEOUT-DOCS-WARRANTI', 70),
  ('ASM-TT-DEM-STD', 'TSK-TT-SCOPE-REVIEW-SURVEY-EXISTING', 10),
  ('ASM-TT-DEM-STD', 'TSK-TT-PROTECTION-ISOLATE-SYSTEMS', 20),
  ('ASM-TT-DEM-STD', 'TSK-TT-ABATEMENT-HAZARDOUS-CHECK', 30),
  ('ASM-TT-DEM-STD', 'TSK-TT-MOBILIZE-DEMO-EQUIPMENT', 40),
  ('ASM-TT-DEM-STD', 'TSK-TT-SELECTIVE-REMOVAL', 50),
  ('ASM-TT-DEM-STD', 'TSK-TT-PRIMARY-DEMOLITION', 60),
  ('ASM-TT-DEM-STD', 'TSK-TT-SEPARATE-SALVAGE-RECYCLE', 70),
  ('ASM-TT-DEM-STD', 'TSK-TT-LOAD-DEBRIS', 80),
  ('ASM-TT-DEM-STD', 'TSK-TT-HAUL-DISPOSE', 90),
  ('ASM-TT-DEM-STD', 'TSK-TT-FINAL-CLEANUP-VERIFY', 100),
  ('ASM-TT-DOT-STD', 'TSK-TT-REVIEW-PLANS-TRAFFIC-COORDIN', 10),
  ('ASM-TT-DOT-STD', 'TSK-TT-SURVEY-LAYOUT-LOCATES', 20),
  ('ASM-TT-DOT-STD', 'TSK-TT-PREP-SUBBASE-REMOVALS-IF-NEE', 30),
  ('ASM-TT-DOT-STD', 'TSK-TT-INSTALL-CIVILS-STRUCTURES-SU', 40),
  ('ASM-TT-DOT-STD', 'TSK-TT-INSTALL-PAVING-MARKINGS-DEVI', 50),
  ('ASM-TT-DOT-STD', 'TSK-TT-INSTALL-SIGNALS-SIGNS-LIGHTI', 60),
  ('ASM-TT-DOT-STD', 'TSK-TT-TEST-SYSTEMS-VERIFY-GEOMETRY', 70),
  ('ASM-TT-DOT-STD', 'TSK-TT-PUNCH-ADJUST-SEAL-STRIPE', 80),
  ('ASM-TT-DOT-STD', 'TSK-TT-AGENCY-INSPECTION-ACCEPTANCE', 90),
  ('ASM-TT-DOT-STD', 'TSK-TT-CLEANUP-TURNOVER', 100),
  ('ASM-TT-DRN-INSP', 'TSK-TT-MISSION-PLAN-AIRSPACE-CHECKL', 10),
  ('ASM-TT-DRN-INSP', 'TSK-TT-MOBILIZE-LAUNCH-CAPTURE', 20),
  ('ASM-TT-DRN-INSP', 'TSK-TT-PROCESS-ANNOTATE-FINDINGS', 30),
  ('ASM-TT-DRN-INSP', 'TSK-TT-DELIVER-REPORT-ARCHIVE-FILES', 40),
  ('ASM-TT-DRN-MAP', 'TSK-TT-MISSION-PLAN-CONTROL-SETUP', 10),
  ('ASM-TT-DRN-MAP', 'TSK-TT-FLY-GRID-CAPTURE-OVERLAP', 20),
  ('ASM-TT-DRN-MAP', 'TSK-TT-PROCESS-STITCH-QA', 30),
  ('ASM-TT-DRN-MAP', 'TSK-TT-DELIVER-GEO-OUTPUTS', 40),
  ('ASM-TT-DRN-MED', 'TSK-TT-CREATIVE-BRIEF-SHOT-PLAN', 10),
  ('ASM-TT-DRN-MED', 'TSK-TT-CAPTURE-PHOTO-VIDEO-PASSES', 20),
  ('ASM-TT-DRN-MED', 'TSK-TT-EDIT-COLOR-EXPORT', 30),
  ('ASM-TT-DRN-MED', 'TSK-TT-DELIVER-MEDIA-PACKAGE', 40),
  ('ASM-TT-DRN-THM', 'TSK-TT-MISSION-PLAN-THERMAL-SETUP', 10),
  ('ASM-TT-DRN-THM', 'TSK-TT-CAPTURE-THERMAL-IMAGERY', 20),
  ('ASM-TT-DRN-THM', 'TSK-TT-PROCESS-COMPARE-ANNOTATE', 30),
  ('ASM-TT-DRN-THM', 'TSK-TT-DELIVER-THERMAL-REPORT', 40),
  ('ASM-TT-ELEC-STD', 'TSK-TT-SCOPE-REVIEW-VERIFY-CIRCUIT', 10),
  ('ASM-TT-ELEC-STD', 'TSK-TT-LOCKOUT-TAGOUT', 20),
  ('ASM-TT-ELEC-STD', 'TSK-TT-OPEN-WALLS-PATHWAYS-IF-NEEDE', 30),
  ('ASM-TT-ELEC-STD', 'TSK-TT-INSTALL-BOXES-RACEWAY', 40),
  ('ASM-TT-ELEC-STD', 'TSK-TT-PULL-WIRE-CABLE', 50),
  ('ASM-TT-ELEC-STD', 'TSK-TT-SET-DEVICE-FIXTURE-PANEL-ITE', 60),
  ('ASM-TT-ELEC-STD', 'TSK-TT-TERMINATE-CONDUCTORS', 70),
  ('ASM-TT-ELEC-STD', 'TSK-TT-LABEL-PROGRAM-IF-NEEDED', 80),
  ('ASM-TT-ELEC-STD', 'TSK-TT-TEST-ENERGIZE-VERIFY', 90),
  ('ASM-TT-ELEC-STD', 'TSK-TT-CLEANUP-TURNOVER', 100),
  ('ASM-TT-EXC-STD', 'TSK-TT-SCOPE-REVIEW-LAYOUT', 10),
  ('ASM-TT-EXC-STD', 'TSK-TT-UTILITY-LOCATE-SAFETY-PREP', 20),
  ('ASM-TT-EXC-STD', 'TSK-TT-MOBILIZE-EQUIPMENT', 30),
  ('ASM-TT-EXC-STD', 'TSK-TT-CLEAR-STRIP-REMOVE-TOPSOIL', 40),
  ('ASM-TT-EXC-STD', 'TSK-TT-EXCAVATE-TO-LINE-AND-GRADE', 50),
  ('ASM-TT-EXC-STD', 'TSK-TT-LOAD-HAUL-STOCKPILE', 60),
  ('ASM-TT-EXC-STD', 'TSK-TT-INSTALL-BEDDING-STABILIZATIO', 70),
  ('ASM-TT-EXC-STD', 'TSK-TT-BACKFILL-COMPACT', 80),
  ('ASM-TT-EXC-STD', 'TSK-TT-FINE-GRADE-PROOF-VERIFY', 90),
  ('ASM-TT-EXC-STD', 'TSK-TT-CLEANUP-DEMOBILIZE', 100),
  ('ASM-TT-FINI-STD', 'TSK-TT-SCOPE-REVIEW-MOISTURE-VERIFY', 10),
  ('ASM-TT-FINI-STD', 'TSK-TT-PROTECT-ADJACENT-SURFACES', 20),
  ('ASM-TT-FINI-STD', 'TSK-TT-REMOVE-EXISTING-IF-NEEDED', 30),
  ('ASM-TT-FINI-STD', 'TSK-TT-PREP-SUBSTRATE', 40),
  ('ASM-TT-FINI-STD', 'TSK-TT-LAYOUT-STAGE-MATERIALS', 50),
  ('ASM-TT-FINI-STD', 'TSK-TT-INSTALL-FINISH-SYSTEM', 60),
  ('ASM-TT-FINI-STD', 'TSK-TT-TRIM-TRANSITIONS-DETAILING', 70),
  ('ASM-TT-FINI-STD', 'TSK-TT-COAT-SEAL-CURE-IF-NEEDED', 80),
  ('ASM-TT-FINI-STD', 'TSK-TT-INSPECT-TOUCHUP', 90),
  ('ASM-TT-FINI-STD', 'TSK-TT-CLEANUP-TURNOVER', 100),
  ('ASM-TT-HVAC-STD', 'TSK-TT-SCOPE-REVIEW-VERIFY-EQUIPMEN', 10),
  ('ASM-TT-HVAC-STD', 'TSK-TT-PROTECT-AREA-ISOLATE-POWER', 20),
  ('ASM-TT-HVAC-STD', 'TSK-TT-RECOVER-REFRIGERANT-DISCONNE', 30),
  ('ASM-TT-HVAC-STD', 'TSK-TT-REMOVE-EXISTING-EQUIPMENT-IF', 40),
  ('ASM-TT-HVAC-STD', 'TSK-TT-SET-NEW-EQUIPMENT', 50),
  ('ASM-TT-HVAC-STD', 'TSK-TT-CONNECT-REFRIGERANT-CONDENSA', 60),
  ('ASM-TT-HVAC-STD', 'TSK-TT-CONNECT-DUCT-VENT-GAS-CONTRO', 70),
  ('ASM-TT-HVAC-STD', 'TSK-TT-EVACUATE-CHARGE-STARTUP', 80),
  ('ASM-TT-HVAC-STD', 'TSK-TT-BALANCE-COMMISSION-VERIFY', 90),
  ('ASM-TT-HVAC-STD', 'TSK-TT-CLEANUP-TURNOVER', 100),
  ('ASM-TT-MOT-STD', 'TSK-TT-REVIEW-MOT-PLAN-PERMIT', 10),
  ('ASM-TT-MOT-STD', 'TSK-TT-PRE-STAGE-DEVICES-INSPECT', 20),
  ('ASM-TT-MOT-STD', 'TSK-TT-DEPLOY-SIGNS-ADVANCE-WARNING', 30),
  ('ASM-TT-MOT-STD', 'TSK-TT-DEPLOY-CHANNELIZATION-BARRIE', 40),
  ('ASM-TT-MOT-STD', 'TSK-TT-IMPLEMENT-CLOSURE-DETOUR-TAP', 50),
  ('ASM-TT-MOT-STD', 'TSK-TT-DAILY-MAINTENANCE-RESET', 60),
  ('ASM-TT-MOT-STD', 'TSK-TT-INSPECT-DOCUMENT-COMPLIANCE', 70),
  ('ASM-TT-MOT-STD', 'TSK-TT-RELOCATE-DEVICES-AS-WORK-SHI', 80),
  ('ASM-TT-MOT-STD', 'TSK-TT-REMOVE-DEVICES-RESTORE-TRAFF', 90),
  ('ASM-TT-MOT-STD', 'TSK-TT-PICKUP-DEMOBILIZE', 100),
  ('ASM-TT-OPEN-STD', 'TSK-TT-VERIFY-OPENING-MEASURE', 10),
  ('ASM-TT-OPEN-STD', 'TSK-TT-PROTECT-AREA', 20),
  ('ASM-TT-OPEN-STD', 'TSK-TT-REMOVE-EXISTING-UNIT', 30),
  ('ASM-TT-OPEN-STD', 'TSK-TT-PREP-OPENING-REPAIR-SUBSTRAT', 40),
  ('ASM-TT-OPEN-STD', 'TSK-TT-INSTALL-FLASHING-PAN-SEAL', 50),
  ('ASM-TT-OPEN-STD', 'TSK-TT-SET-FRAME-UNIT', 60),
  ('ASM-TT-OPEN-STD', 'TSK-TT-FASTEN-PLUMB-INSULATE', 70),
  ('ASM-TT-OPEN-STD', 'TSK-TT-INTERIOR-EXTERIOR-TRIM', 80),
  ('ASM-TT-OPEN-STD', 'TSK-TT-ADJUST-HARDWARE-VERIFY-OPERA', 90),
  ('ASM-TT-OPEN-STD', 'TSK-TT-CLEANUP-TURNOVER', 100),
  ('ASM-TT-PLBG-FIX', 'TSK-TT-SCOPE-REVIEW-VERIFY-FIXTURE', 10),
  ('ASM-TT-PLBG-FIX', 'TSK-TT-SHUT-DOWN-ISOLATE-SUPPLY', 20),
  ('ASM-TT-PLBG-FIX', 'TSK-TT-REMOVE-EXISTING-IF-APPLICABL', 30),
  ('ASM-TT-PLBG-FIX', 'TSK-TT-PREP-ROUGH-IN-ANCHORAGE', 40),
  ('ASM-TT-PLBG-FIX', 'TSK-TT-SET-FIXTURE', 50),
  ('ASM-TT-PLBG-FIX', 'TSK-TT-CONNECT-SUPPLY', 60),
  ('ASM-TT-PLBG-FIX', 'TSK-TT-CONNECT-WASTE-VENT', 70),
  ('ASM-TT-PLBG-FIX', 'TSK-TT-SEAL-TRIM-CAULK', 80),
  ('ASM-TT-PLBG-FIX', 'TSK-TT-TEST-LEAK-CHECK-ADJUST', 90),
  ('ASM-TT-PLBG-FIX', 'TSK-TT-CLEANUP-TURNOVER', 100),
  ('ASM-TT-PLBG-LINE', 'TSK-TT-LOCATE-LINE-VERIFY-ROUTING', 10),
  ('ASM-TT-PLBG-LINE', 'TSK-TT-OPEN-ACCESS-TRENCH-EXPOSE', 20),
  ('ASM-TT-PLBG-LINE', 'TSK-TT-REMOVE-EXISTING-LINE-IF-NEED', 30),
  ('ASM-TT-PLBG-LINE', 'TSK-TT-INSTALL-HANGERS-SUPPORTS', 40),
  ('ASM-TT-PLBG-LINE', 'TSK-TT-INSTALL-PIPE-FITTINGS', 50),
  ('ASM-TT-PLBG-LINE', 'TSK-TT-CONNECT-TIE-IN', 60),
  ('ASM-TT-PLBG-LINE', 'TSK-TT-INSULATE-WRAP-IF-NEEDED', 70),
  ('ASM-TT-PLBG-LINE', 'TSK-TT-PRESSURE-FLOW-SMOKE-TEST', 80),
  ('ASM-TT-PLBG-LINE', 'TSK-TT-PATCH-RESTORE-SURFACES', 90),
  ('ASM-TT-PLBG-LINE', 'TSK-TT-CLEANUP-TURNOVER', 100),
  ('ASM-TT-PW-STD', 'TSK-TT-SCOPE-REVIEW-SURFACE-CHECK', 10),
  ('ASM-TT-PW-STD', 'TSK-TT-PROTECT-OUTLETS-PLANTS-ADJAC', 20),
  ('ASM-TT-PW-STD', 'TSK-TT-SETUP-WATER-HOSES-CONTAINMEN', 30),
  ('ASM-TT-PW-STD', 'TSK-TT-APPLY-DETERGENT-PRETREAT', 40),
  ('ASM-TT-PW-STD', 'TSK-TT-MAIN-WASH-PASS', 50),
  ('ASM-TT-PW-STD', 'TSK-TT-DETAIL-CORNERS-EDGES-STAINS', 60),
  ('ASM-TT-PW-STD', 'TSK-TT-RINSE-NEUTRALIZE-POST-TREAT', 70),
  ('ASM-TT-PW-STD', 'TSK-TT-EQUIPMENT-RINSE-RESET-SITE', 80),
  ('ASM-TT-PW-STD', 'TSK-TT-FINAL-VISUAL-INSPECTION', 90),
  ('ASM-TT-PW-STD', 'TSK-TT-CLEANUP-DEMOBILIZE', 100),
  ('ASM-TT-RMOD-STD', 'TSK-TT-SCOPE-REVIEW-SELECTIONS-VERI', 10),
  ('ASM-TT-RMOD-STD', 'TSK-TT-PROTECT-OCCUPIED-AREAS', 20),
  ('ASM-TT-RMOD-STD', 'TSK-TT-SELECTIVE-DEMOLITION', 30),
  ('ASM-TT-RMOD-STD', 'TSK-TT-FRAMING-BLOCKING-ROUGH-CARPE', 40),
  ('ASM-TT-RMOD-STD', 'TSK-TT-MEP-ROUGH-COORDINATION', 50),
  ('ASM-TT-RMOD-STD', 'TSK-TT-DRYWALL-PATCH-PREP', 60),
  ('ASM-TT-RMOD-STD', 'TSK-TT-FINISH-INSTALL-TRIM-ACCESSOR', 70),
  ('ASM-TT-RMOD-STD', 'TSK-TT-PAINT-TOUCHUP', 80),
  ('ASM-TT-RMOD-STD', 'TSK-TT-PUNCH-LIST-CORRECTIONS', 90),
  ('ASM-TT-RMOD-STD', 'TSK-TT-FINAL-CLEAN-TURNOVER', 100),
  ('ASM-TT-SPCL-STD', 'TSK-TT-VERIFY-MANUFACTURER-SUBMITTA', 10),
  ('ASM-TT-SPCL-STD', 'TSK-TT-COORDINATE-UTILITIES-CLEARAN', 20),
  ('ASM-TT-SPCL-STD', 'TSK-TT-SET-BASE-ANCHORAGE', 30),
  ('ASM-TT-SPCL-STD', 'TSK-TT-SET-EQUIPMENT-SPECIALTY-UNIT', 40),
  ('ASM-TT-SPCL-STD', 'TSK-TT-CONNECT-MECHANICAL-ELECTRICA', 50),
  ('ASM-TT-SPCL-STD', 'TSK-TT-STARTUP-CALIBRATION', 60),
  ('ASM-TT-SPCL-STD', 'TSK-TT-TRAINING-OWNER-DEMO', 70),
  ('ASM-TT-SPCL-STD', 'TSK-TT-LABEL-DOCUMENT', 80)
) as v(assembly_code, task_code, sort)
join assemblies a on a.code = v.assembly_code and a.company_id is null
join tasks t on t.code = v.task_code and t.company_id is null
on conflict do nothing;

/*
 * The rates that were stated. `seed_benchmark` at a confidence of 0.4: this is
 * a considered starting point rather than a measured actual, and RULE-010 says
 * where a number came from travels with it.
 */
insert into production_rates (code, task_id, rate_per_hour, rate_unit, source_type,
                              confidence_score, sample_size, status, source)
select 'PR-' || t.code, t.id, v.rate, v.unit::app.unit_code,
       'seed_benchmark', 0.4, 0, 'active', 'GrounUp task templates v1'
from (values
  ('TSK-TT-SUBGRADE-PREP-COMPACT', 220.0, 'SY'),
  ('TSK-TT-SET-FORMS-EDGES', 65.0, 'LF'),
  ('TSK-TT-INSTALL-REINFORCEMENT', 180.0, 'SF'),
  ('TSK-TT-POUR-PLACE-CONCRETE', 10.0, 'CY'),
  ('TSK-TT-SCREED-FLOAT-FINISH', 250.0, 'SF'),
  ('TSK-TT-SAWCUT-SEAL-JOINTS', 120.0, 'LF'),
  ('TSK-TT-SET-DEVICE-FIXTURE-PANEL-ITE', 1.0, 'EA'),
  ('TSK-TT-CLEAR-STRIP-REMOVE-TOPSOIL', 90.0, 'CY'),
  ('TSK-TT-EXCAVATE-TO-LINE-AND-GRADE', 80.0, 'CY'),
  ('TSK-TT-LOAD-HAUL-STOCKPILE', 95.0, 'CY'),
  ('TSK-TT-INSTALL-BEDDING-STABILIZATIO', 50.0, 'CY'),
  ('TSK-TT-BACKFILL-COMPACT', 60.0, 'CY'),
  ('TSK-TT-FINE-GRADE-PROOF-VERIFY', 250.0, 'SY'),
  ('TSK-TT-SET-NEW-EQUIPMENT', 1.0, 'EA'),
  ('TSK-TT-SET-FRAME-UNIT', 1.0, 'EA'),
  ('TSK-TT-SET-FIXTURE', 1.0, 'EA'),
  ('TSK-TT-INSTALL-PIPE-FITTINGS', 55.0, 'LF'),
  ('TSK-TT-MAIN-WASH-PASS', 600.0, 'SF'),
  ('TSK-TT-SET-EQUIPMENT-SPECIALTY-UNIT', 1.0, 'EA')
) as v(task_code, rate, unit)
join tasks t on t.code = v.task_code and t.company_id is null
on conflict do nothing;
