import { supabase, isSupabaseConfigured } from '@/lib/supabase';

/**
 * Counting the people who look, without following them.
 *
 * The identifier here is generated by the browser, for the browser, and stored
 * where the browser can lose it. It is not derived from an address, a screen
 * size or anything else about the person, it is never sent anywhere but this
 * platform's own database, and clearing site data makes somebody a new visitor
 * — which is the correct outcome, not a gap to close.
 *
 * What that buys is the only question worth asking: how many people looked,
 * where they came from, and how far they got. Not who they are.
 */
const KEY = 'grounup.visitor';

function visitorId(): string | null {
  try {
    const held = localStorage.getItem(KEY);
    if (held) return held;
    const made = crypto.randomUUID();
    localStorage.setItem(KEY, made);
    return made;
  } catch {
    // A private window, or storage turned off. The visit is still counted; it
    // simply is not grouped with any other, which is the honest result.
    return null;
  }
}

/** Desktop, tablet or phone. Deliberately the coarsest thing worth knowing. */
function device(): 'desktop' | 'tablet' | 'phone' {
  const w = window.innerWidth;
  return w < 768 ? 'phone' : w < 1024 ? 'tablet' : 'desktop';
}

function campaign() {
  const q = new URLSearchParams(window.location.search);
  return {
    source: q.get('utm_source'),
    medium: q.get('utm_medium'),
    name: q.get('utm_campaign'),
  };
}

/** Remember the campaign that brought somebody, so a signup can name it. */
function rememberCampaign(source: string | null) {
  if (!source) return;
  try { sessionStorage.setItem('grounup.utm_source', source); } catch { /* fine */ }
}

function heldCampaign(): string | null {
  try { return sessionStorage.getItem('grounup.utm_source'); } catch { return null; }
}

/**
 * Record one page view.
 *
 * Never throws and never blocks: a page view is not worth breaking a page for,
 * and somebody reading the site should never wait on it.
 */
export function recordVisit(path: string): void {
  if (!isSupabaseConfigured || !supabase) return;
  // The console and the application are not traffic. The database refuses them
  // too; this saves the round trip.
  if (path.startsWith('/admin') || path.startsWith('/app')) return;

  const utm = campaign();
  rememberCampaign(utm.source);

  void supabase.rpc('record_visit', {
    p_path: path,
    p_visitor: visitorId(),
    // The referring page, not the query string on it: a search URL carries
    // somebody's search terms, which is not ours to keep.
    p_referrer: document.referrer || null,
    p_utm_source: utm.source,
    p_utm_medium: utm.medium,
    p_utm_campaign: utm.name,
    p_device: device(),
  }).then(undefined, () => { /* counted or not; the page does not care */ });
}

/**
 * Record that somebody submitted the signup form, and what happened.
 *
 * On submit, never on a keystroke. An address typed and thought better of is
 * not an attempt, and recording one would mean collecting an email from
 * somebody who decided not to give it.
 */
export function recordSignupAttempt(
  email: string,
  outcome: 'started' | 'failed' | 'completed',
  failure?: string | null,
): void {
  if (!isSupabaseConfigured || !supabase) return;
  if (!email.includes('@')) return;

  void supabase.rpc('record_signup_attempt', {
    p_email: email.trim(),
    p_outcome: outcome,
    p_failure: failure ?? null,
    p_visitor: visitorId(),
    p_utm_source: heldCampaign(),
  }).then(undefined, () => { /* the signup matters; the record of it does not */ });
}
